'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace test
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'address' dallo spazio dei nomi 'http://guidewire.com/pl/wsdl' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SinistriServiceForAgenzieServiceSoap11Binding", [Namespace]:="http://sx.unipol.it/webservice/serviziagenzia/service")>  _
    Partial Public Class SinistriServiceForAgenzieService
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol

        Private authenticationValueField As authentication
        
        Private gw_languageValueField As gw_language
        
        Private gw_localeValueField As gw_locale
        
        Private traceability_idValueField As traceability_id
        
        Private getListaSinistriDelGiornoPerUtenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getSinistroDettaglioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://lxfmjbliqcc.servizi.gr-u.it/essigSXCC/ws/it/unipol/sx/webservice/serviziag"& _ 
                "enzia/service/SinistriServiceForAgenzieService/soap11"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property authenticationValue() As authentication
            Get
                Return Me.authenticationValueField
            End Get
            Set
                Me.authenticationValueField = value
            End Set
        End Property
        
        Public Property gw_languageValue() As gw_language
            Get
                Return Me.gw_languageValueField
            End Get
            Set
                Me.gw_languageValueField = value
            End Set
        End Property
        
        Public Property gw_localeValue() As gw_locale
            Get
                Return Me.gw_localeValueField
            End Get
            Set
                Me.gw_localeValueField = value
            End Set
        End Property
        
        Public Property traceability_idValue() As traceability_id
            Get
                Return Me.traceability_idValueField
            End Get
            Set
                Me.traceability_idValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getListaSinistriDelGiornoPerUtenteCompleted As getListaSinistriDelGiornoPerUtenteCompletedEventHandler
        
        '''<remarks/>
        Public Event getSinistroDettaglioCompleted As getSinistroDettaglioCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("gw_localeValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("traceability_idValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("authenticationValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("gw_languageValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://sx.unipol.it/webservice/serviziagenzia/service", ResponseNamespace:="http://sx.unipol.it/webservice/serviziagenzia/service", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getListaSinistriDelGiornoPerUtente(ByVal username As String, ByVal dataCreazioneInizio As String) As <System.Xml.Serialization.XmlElementAttribute("return")> Result
            Dim results() As Object = Me.Invoke("getListaSinistriDelGiornoPerUtente", New Object() {username, dataCreazioneInizio})
            Return CType(results(0),Result)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getListaSinistriDelGiornoPerUtenteAsync(ByVal username As String, ByVal dataCreazioneInizio As String)
            Me.getListaSinistriDelGiornoPerUtenteAsync(username, dataCreazioneInizio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getListaSinistriDelGiornoPerUtenteAsync(ByVal username As String, ByVal dataCreazioneInizio As String, ByVal userState As Object)
            If (Me.getListaSinistriDelGiornoPerUtenteOperationCompleted Is Nothing) Then
                Me.getListaSinistriDelGiornoPerUtenteOperationCompleted = AddressOf Me.OngetListaSinistriDelGiornoPerUtenteOperationCompleted
            End If
            Me.InvokeAsync("getListaSinistriDelGiornoPerUtente", New Object() {username, dataCreazioneInizio}, Me.getListaSinistriDelGiornoPerUtenteOperationCompleted, userState)
        End Sub
        
        Private Sub OngetListaSinistriDelGiornoPerUtenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.getListaSinistriDelGiornoPerUtenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getListaSinistriDelGiornoPerUtenteCompleted(Me, New getListaSinistriDelGiornoPerUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("gw_localeValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("traceability_idValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("authenticationValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("gw_languageValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://sx.unipol.it/webservice/serviziagenzia/service", ResponseNamespace:="http://sx.unipol.it/webservice/serviziagenzia/service", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getSinistroDettaglio(ByVal username As String, ByVal numeroSinistro As String) As <System.Xml.Serialization.XmlElementAttribute("return")> Result
            Dim results() As Object = Me.Invoke("getSinistroDettaglio", New Object() {username, numeroSinistro})
            Return CType(results(0),Result)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getSinistroDettaglioAsync(ByVal username As String, ByVal numeroSinistro As String)
            Me.getSinistroDettaglioAsync(username, numeroSinistro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getSinistroDettaglioAsync(ByVal username As String, ByVal numeroSinistro As String, ByVal userState As Object)
            If (Me.getSinistroDettaglioOperationCompleted Is Nothing) Then
                Me.getSinistroDettaglioOperationCompleted = AddressOf Me.OngetSinistroDettaglioOperationCompleted
            End If
            Me.InvokeAsync("getSinistroDettaglio", New Object() {username, numeroSinistro}, Me.getSinistroDettaglioOperationCompleted, userState)
        End Sub
        
        Private Sub OngetSinistroDettaglioOperationCompleted(ByVal arg As Object)
            If (Not (Me.getSinistroDettaglioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getSinistroDettaglioCompleted(Me, New getSinistroDettaglioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://guidewire.com/ws/soapheaders"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://guidewire.com/ws/soapheaders", IsNullable:=true)>  _
    Partial Public Class gw_locale
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sx.unipol.it/webservice/serviziagenzia/service/domain")>  _
    Partial Public Class InfoSinistro
        
        Private dataAperturaField As Date
        
        Private dataAperturaFieldSpecified As Boolean
        
        Private nomeCognomeAssicuratoField As String
        
        Private numeroField As String
        
        '''<remarks/>
        Public Property DataApertura() As Date
            Get
                Return Me.dataAperturaField
            End Get
            Set
                Me.dataAperturaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataAperturaSpecified() As Boolean
            Get
                Return Me.dataAperturaFieldSpecified
            End Get
            Set
                Me.dataAperturaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeCognomeAssicurato() As String
            Get
                Return Me.nomeCognomeAssicuratoField
            End Get
            Set
                Me.nomeCognomeAssicuratoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sx.unipol.it/webservice/serviziagenzia/service/domain")>  _
    Partial Public Class DettaglioSinistro
        
        Private codiceAgenziaField As String
        
        Private codiceClgField As String
        
        Private codiceFiscaleContraenteField As String
        
        Private codicePeritoField As String
        
        Private codiceSubAgenziaField As String
        
        Private convenzioneField As String
        
        Private dataAccadimentoField As Date
        
        Private dataAccadimentoFieldSpecified As Boolean
        
        Private dataAperturaSinistroField As Date
        
        Private dataAperturaSinistroFieldSpecified As Boolean
        
        Private dataDenunciaField As Date
        
        Private dataDenunciaFieldSpecified As Boolean
        
        Private dataInterventoLegaleField As Date
        
        Private dataInterventoLegaleFieldSpecified As Boolean
        
        Private flagLegaleField As String
        
        Private liquidatoreAssegnatarioField As String
        
        Private nomeContraenteField As String
        
        Private nomeControparteField As String
        
        Private nostraQuotaField As Decimal
        
        Private nostraQuotaFieldSpecified As Boolean
        
        Private numeroPolizzaField As String
        
        Private numeroPosizioniField As Integer
        
        Private numeroPosizioniFieldSpecified As Boolean
        
        Private numeroSinistroField As String
        
        Private presenzaCoseLesioniField As String
        
        Private prodottoField As String
        
        Private profiloSinistroField As String
        
        Private ramoPolizzaField As String
        
        Private ramoSinistroField As String
        
        Private riservaTecnicaField As Decimal
        
        Private riservaTecnicaFieldSpecified As Boolean
        
        Private statoTecnicoField As String
        
        Private targaAssicuratoField As String
        
        Private targaControparteField As String
        
        '''<remarks/>
        Public Property CodiceAgenzia() As String
            Get
                Return Me.codiceAgenziaField
            End Get
            Set
                Me.codiceAgenziaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceClg() As String
            Get
                Return Me.codiceClgField
            End Get
            Set
                Me.codiceClgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceFiscaleContraente() As String
            Get
                Return Me.codiceFiscaleContraenteField
            End Get
            Set
                Me.codiceFiscaleContraenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodicePerito() As String
            Get
                Return Me.codicePeritoField
            End Get
            Set
                Me.codicePeritoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceSubAgenzia() As String
            Get
                Return Me.codiceSubAgenziaField
            End Get
            Set
                Me.codiceSubAgenziaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Convenzione() As String
            Get
                Return Me.convenzioneField
            End Get
            Set
                Me.convenzioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAccadimento() As Date
            Get
                Return Me.dataAccadimentoField
            End Get
            Set
                Me.dataAccadimentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataAccadimentoSpecified() As Boolean
            Get
                Return Me.dataAccadimentoFieldSpecified
            End Get
            Set
                Me.dataAccadimentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAperturaSinistro() As Date
            Get
                Return Me.dataAperturaSinistroField
            End Get
            Set
                Me.dataAperturaSinistroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataAperturaSinistroSpecified() As Boolean
            Get
                Return Me.dataAperturaSinistroFieldSpecified
            End Get
            Set
                Me.dataAperturaSinistroFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataDenuncia() As Date
            Get
                Return Me.dataDenunciaField
            End Get
            Set
                Me.dataDenunciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataDenunciaSpecified() As Boolean
            Get
                Return Me.dataDenunciaFieldSpecified
            End Get
            Set
                Me.dataDenunciaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataInterventoLegale() As Date
            Get
                Return Me.dataInterventoLegaleField
            End Get
            Set
                Me.dataInterventoLegaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DataInterventoLegaleSpecified() As Boolean
            Get
                Return Me.dataInterventoLegaleFieldSpecified
            End Get
            Set
                Me.dataInterventoLegaleFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FlagLegale() As String
            Get
                Return Me.flagLegaleField
            End Get
            Set
                Me.flagLegaleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LiquidatoreAssegnatario() As String
            Get
                Return Me.liquidatoreAssegnatarioField
            End Get
            Set
                Me.liquidatoreAssegnatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeContraente() As String
            Get
                Return Me.nomeContraenteField
            End Get
            Set
                Me.nomeContraenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeControparte() As String
            Get
                Return Me.nomeControparteField
            End Get
            Set
                Me.nomeControparteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NostraQuota() As Decimal
            Get
                Return Me.nostraQuotaField
            End Get
            Set
                Me.nostraQuotaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NostraQuotaSpecified() As Boolean
            Get
                Return Me.nostraQuotaFieldSpecified
            End Get
            Set
                Me.nostraQuotaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroPolizza() As String
            Get
                Return Me.numeroPolizzaField
            End Get
            Set
                Me.numeroPolizzaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroPosizioni() As Integer
            Get
                Return Me.numeroPosizioniField
            End Get
            Set
                Me.numeroPosizioniField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NumeroPosizioniSpecified() As Boolean
            Get
                Return Me.numeroPosizioniFieldSpecified
            End Get
            Set
                Me.numeroPosizioniFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroSinistro() As String
            Get
                Return Me.numeroSinistroField
            End Get
            Set
                Me.numeroSinistroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PresenzaCoseLesioni() As String
            Get
                Return Me.presenzaCoseLesioniField
            End Get
            Set
                Me.presenzaCoseLesioniField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Prodotto() As String
            Get
                Return Me.prodottoField
            End Get
            Set
                Me.prodottoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProfiloSinistro() As String
            Get
                Return Me.profiloSinistroField
            End Get
            Set
                Me.profiloSinistroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RamoPolizza() As String
            Get
                Return Me.ramoPolizzaField
            End Get
            Set
                Me.ramoPolizzaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RamoSinistro() As String
            Get
                Return Me.ramoSinistroField
            End Get
            Set
                Me.ramoSinistroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RiservaTecnica() As Decimal
            Get
                Return Me.riservaTecnicaField
            End Get
            Set
                Me.riservaTecnicaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RiservaTecnicaSpecified() As Boolean
            Get
                Return Me.riservaTecnicaFieldSpecified
            End Get
            Set
                Me.riservaTecnicaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatoTecnico() As String
            Get
                Return Me.statoTecnicoField
            End Get
            Set
                Me.statoTecnicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TargaAssicurato() As String
            Get
                Return Me.targaAssicuratoField
            End Get
            Set
                Me.targaAssicuratoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TargaControparte() As String
            Get
                Return Me.targaControparteField
            End Get
            Set
                Me.targaControparteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sx.unipol.it/webservice/serviziagenzia/service/domain")>  _
    Partial Public Class Result
        
        Private dettaglioSinistroField As DettaglioSinistro
        
        Private errorCodeField As String
        
        Private errorDescriptionField As String
        
        Private sinistroInfoField() As InfoSinistro
        
        '''<remarks/>
        Public Property DettaglioSinistro() As DettaglioSinistro
            Get
                Return Me.dettaglioSinistroField
            End Get
            Set
                Me.dettaglioSinistroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Entry")>  _
        Public Property SinistroInfo() As InfoSinistro()
            Get
                Return Me.sinistroInfoField
            End Get
            Set
                Me.sinistroInfoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://guidewire.com/ws/soapheaders"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://guidewire.com/ws/soapheaders", IsNullable:=true)>  _
    Partial Public Class traceability_id
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://guidewire.com/ws/soapheaders"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://guidewire.com/ws/soapheaders", IsNullable:=true)>  _
    Partial Public Class authentication
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://guidewire.com/ws/soapheaders"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://guidewire.com/ws/soapheaders", IsNullable:=true)>  _
    Partial Public Class gw_language
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getListaSinistriDelGiornoPerUtenteCompletedEventHandler(ByVal sender As Object, ByVal e As getListaSinistriDelGiornoPerUtenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getListaSinistriDelGiornoPerUtenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Result
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Result)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getSinistroDettaglioCompletedEventHandler(ByVal sender As Object, ByVal e As getSinistroDettaglioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getSinistroDettaglioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Result
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Result)
            End Get
        End Property
    End Class
End Namespace
