'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace Rete
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GestioneReteSoap", [Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class GestioneRete
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SalvaFlagPuntiVenditaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SalvaFlagSoggettiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SalvaFlagUtenzeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SalvaFlagCipOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_Rete_Rete1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SalvaFlagPuntiVenditaCompleted As SalvaFlagPuntiVenditaCompletedEventHandler
        
        '''<remarks/>
        Public Event SalvaFlagSoggettiCompleted As SalvaFlagSoggettiCompletedEventHandler
        
        '''<remarks/>
        Public Event SalvaFlagUtenzeCompleted As SalvaFlagUtenzeCompletedEventHandler
        
        '''<remarks/>
        Public Event SalvaFlagCipCompleted As SalvaFlagCipCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/SalvaFlagPuntiVendita", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SalvaFlagPuntiVendita(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.Invoke("SalvaFlagPuntiVendita", New Object() {CodiceAgenzia, dt, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagPuntiVenditaAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.SalvaFlagPuntiVenditaAsync(CodiceAgenzia, dt, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagPuntiVenditaAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String, userState As Object)
            If (Me.SalvaFlagPuntiVenditaOperationCompleted Is Nothing) Then
                Me.SalvaFlagPuntiVenditaOperationCompleted = AddressOf Me.OnSalvaFlagPuntiVenditaOperationCompleted
            End If
            Me.InvokeAsync("SalvaFlagPuntiVendita", New Object() {CodiceAgenzia, dt, Token}, Me.SalvaFlagPuntiVenditaOperationCompleted, userState)
        End Sub
        
        Private Sub OnSalvaFlagPuntiVenditaOperationCompleted(arg As Object)
            If (Not (Me.SalvaFlagPuntiVenditaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SalvaFlagPuntiVenditaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/SalvaFlagSoggetti", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SalvaFlagSoggetti(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.Invoke("SalvaFlagSoggetti", New Object() {CodiceAgenzia, dt, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagSoggettiAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.SalvaFlagSoggettiAsync(CodiceAgenzia, dt, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagSoggettiAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String, userState As Object)
            If (Me.SalvaFlagSoggettiOperationCompleted Is Nothing) Then
                Me.SalvaFlagSoggettiOperationCompleted = AddressOf Me.OnSalvaFlagSoggettiOperationCompleted
            End If
            Me.InvokeAsync("SalvaFlagSoggetti", New Object() {CodiceAgenzia, dt, Token}, Me.SalvaFlagSoggettiOperationCompleted, userState)
        End Sub
        
        Private Sub OnSalvaFlagSoggettiOperationCompleted(arg As Object)
            If (Not (Me.SalvaFlagSoggettiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SalvaFlagSoggettiCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/SalvaFlagUtenze", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SalvaFlagUtenze(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.Invoke("SalvaFlagUtenze", New Object() {CodiceAgenzia, dt, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagUtenzeAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.SalvaFlagUtenzeAsync(CodiceAgenzia, dt, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagUtenzeAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String, userState As Object)
            If (Me.SalvaFlagUtenzeOperationCompleted Is Nothing) Then
                Me.SalvaFlagUtenzeOperationCompleted = AddressOf Me.OnSalvaFlagUtenzeOperationCompleted
            End If
            Me.InvokeAsync("SalvaFlagUtenze", New Object() {CodiceAgenzia, dt, Token}, Me.SalvaFlagUtenzeOperationCompleted, userState)
        End Sub
        
        Private Sub OnSalvaFlagUtenzeOperationCompleted(arg As Object)
            If (Not (Me.SalvaFlagUtenzeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SalvaFlagUtenzeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/SalvaFlagCip", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SalvaFlagCip(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.Invoke("SalvaFlagCip", New Object() {CodiceAgenzia, dt, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagCipAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String)
            Me.SalvaFlagCipAsync(CodiceAgenzia, dt, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaFlagCipAsync(CodiceAgenzia As String, dt As System.Data.DataTable, Token As String, userState As Object)
            If (Me.SalvaFlagCipOperationCompleted Is Nothing) Then
                Me.SalvaFlagCipOperationCompleted = AddressOf Me.OnSalvaFlagCipOperationCompleted
            End If
            Me.InvokeAsync("SalvaFlagCip", New Object() {CodiceAgenzia, dt, Token}, Me.SalvaFlagCipOperationCompleted, userState)
        End Sub
        
        Private Sub OnSalvaFlagCipOperationCompleted(arg As Object)
            If (Not (Me.SalvaFlagCipCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SalvaFlagCipCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub SalvaFlagPuntiVenditaCompletedEventHandler(sender As Object, e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub SalvaFlagSoggettiCompletedEventHandler(sender As Object, e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub SalvaFlagUtenzeCompletedEventHandler(sender As Object, e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub SalvaFlagCipCompletedEventHandler(sender As Object, e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
