'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace AdempimentiOMW
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AdempimentiSoap", [Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class Adempimenti
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private LeggiDocDaIncassiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_AdempimentiOMW_Adempimenti
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LeggiDocDaIncassiCompleted As LeggiDocDaIncassiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/LeggiDocDaIncassi", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub LeggiDocDaIncassi(CodiceAgenzia As String, Token As String)
            Me.Invoke("LeggiDocDaIncassi", New Object() {CodiceAgenzia, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LeggiDocDaIncassiAsync(CodiceAgenzia As String, Token As String)
            Me.LeggiDocDaIncassiAsync(CodiceAgenzia, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LeggiDocDaIncassiAsync(CodiceAgenzia As String, Token As String, userState As Object)
            If (Me.LeggiDocDaIncassiOperationCompleted Is Nothing) Then
                Me.LeggiDocDaIncassiOperationCompleted = AddressOf Me.OnLeggiDocDaIncassiOperationCompleted
            End If
            Me.InvokeAsync("LeggiDocDaIncassi", New Object() {CodiceAgenzia, Token}, Me.LeggiDocDaIncassiOperationCompleted, userState)
        End Sub
        
        Private Sub OnLeggiDocDaIncassiOperationCompleted(arg As Object)
            If (Not (Me.LeggiDocDaIncassiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LeggiDocDaIncassiCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub LeggiDocDaIncassiCompletedEventHandler(sender As Object, e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
