Namespace PSMART
    Public Class PSMARTDE
        Inherits P00000DE

        Public DecodeClasseTerritorialeFurto As New Dizionario(Of Integer, String)
        Public DecodeCasaIncendioScelta As New Dizionario(Of Integer, String)
        Public DecodeCasaDurataPoliennale As New Dizionario(Of Integer, String)
        Public DecodeInfortuniScelta As New Dizionario(Of Integer, String)
        Public DecodeInfortuniDurataPoliennale As New Dizionario(Of Integer, String)
        Public DecodeAttivitaTipo As New Dizionario(Of Integer, String)
        Public DecodeAttivitaScelta As New Dizionario(Of Integer, String)
        Public DecodeAttivitaDurataPoliennale As New Dizionario(Of Integer, String)
        Public DecodeProvinciaToClasseTerritorialeFurto As New Dizionario(Of Integer, Integer)

        Sub New()
            With DecodeSezione
                .Add(TipoSezione.CasaIncendio, "Casa Smart - Incendio")
                .Add(TipoSezione.CasaFurto, "Casa Smart - Furto")
                .Add(TipoSezione.CasaRC, "Casa Smart - Responsabilità civile")
                .Add(TipoSezione.CasaAssistenza, "Casa Smart - Assistenza")
                .Add(TipoSezione.Infortuni, "Infortuni Smart")
                .Add(TipoSezione.AttivitaRC, "Attivita Smart - Responsabilità civile")
                .Add(TipoSezione.AttivitaIncendio, "Attivita Smart - incendio")
                .Add(TipoSezione.Tcm1, "Vita Assicurato")
                .Add(TipoSezione.Tcm2, "Vita Familiare")
                .Add(TipoSezione.Rca, "Rca")
            End With

            With DecodePartita
                .Add(TipoPartita.CasaIncendio, "Casa Smart - Incendio")
                .Add(TipoPartita.CasaFurto, "Casa Smart - Furto")
                .Add(TipoPartita.CasaRC, "Casa Smart - Responsabilità civile")
                .Add(TipoPartita.CasaAssistenza, "Casa Smart - Assistenza")
                .Add(TipoPartita.Infortuni, "Infortuni Smart")
                .Add(TipoPartita.AttivitaRC, "Attivita Smart - Responsabilità civile")
                .Add(TipoPartita.AttivitaIncendio, "Attivita Smart - incendio")
                .Add(TipoPartita.Tcm1, "Vita Assicurato")
                .Add(TipoPartita.Tcm2, "Vita Familiare")
                .Add(TipoPartita.Rca, "Rca")
            End With

            With DecodeGaranzia
                .Add(TipoGaranzia.CasaIncendioBase, "Incendio")
                .Add(TipoGaranzia.CasaPoliennale, "Sconto polizza poliennale")
                .Add(TipoGaranzia.CasaFurtoBase, "Furto")
                .Add(TipoGaranzia.CasaRCBase, "Responsabilità civile")
                .Add(TipoGaranzia.CasaAssistenzaBase, "Assistenza")
                .Add(TipoGaranzia.InfortuniBase, "Garanzia base")
                .Add(TipoGaranzia.InfortuniMorte, "Morte")
                .Add(TipoGaranzia.InfortuniIP, "Invalidità Permanente")
                .Add(TipoGaranzia.InfortuniSpeseMediche, "Rimborso spese mediche")
                .Add(TipoGaranzia.InfortuniDiarieDegenza, "Indennità per ricovero e convalescenza Degenza")
                .Add(TipoGaranzia.InfortuniDiarieDayHospital, "Indennità per ricovero e convalescenza Day Hospital")
                .Add(TipoGaranzia.InfortuniDiarieImmobilizzazione, "Indennità per immobilizzazione")
                .Add(TipoGaranzia.InfortuniFamiglia, "Estensione al Nucleo Famigliare")
                .Add(TipoGaranzia.InfortuniFranchigia, "Deroga Franchigia Invalidità Permanente")
                .Add(TipoGaranzia.InfortuniPoliennale, "Sconto polizza poliennale")
                .Add(TipoGaranzia.AttivitaRCBase, "Responsabilità civile")
                .Add(TipoGaranzia.AttivitaRCT, "Responsabilità civile verso terzi")
                .Add(TipoGaranzia.AttivitaRCL, "Responsabilità civile verso lavoratori")
                .Add(TipoGaranzia.AttivitaIncendioBase, "Garanzia base")
                .Add(TipoGaranzia.AttivitaIncendioFC, "Incendio Fabbricato + Contenuto")
                .Add(TipoGaranzia.AttivitaAttiVandalici, "Atti vandalici e dolosi")
                .Add(TipoGaranzia.AttivitaPoliennale, "Sconto polizza poliennale")
                .Add(TipoGaranzia.Tcm1Base, "Garanzia base")
                .Add(TipoGaranzia.Tcm1Assicurato, "Assicurato")
                .Add(TipoGaranzia.Tcm2Base, "Garanzia base")
                .Add(TipoGaranzia.Tcm2Assicurato, "Familiare")
                .Add(TipoGaranzia.RcaBase, "Rca")
                .Add(TipoGaranzia.RcaSconto, "Sconto")
            End With

            With DecodeFrazionamenti
                .Add(FrazionamentiEnum.annuale, "annuale")
                .Add(FrazionamentiEnum.semestrale, "semestrale")
                .Add(FrazionamentiEnum.quadrimestrale, "quadrimestrale")
                .Add(FrazionamentiEnum.trimestrale, "trimestrale")
                .Add(FrazionamentiEnum.bimestrale, "bimestrale")
                .Add(FrazionamentiEnum.mensile, "mensile")
            End With

            With DecodeClasseTerritorialeFurto
                .Add(ClasseTerritorialeFurtoEnum.Classe1, "1")
                .Add(ClasseTerritorialeFurtoEnum.Classe2, "2")
                .Add(ClasseTerritorialeFurtoEnum.Classe3, "3")
            End With

            With DecodeCasaIncendioScelta
                .Add(CasaSceltaEnum.SceltaA, "Scelta A")
                .Add(CasaSceltaEnum.SceltaB, "Scelta B")
                .Add(CasaSceltaEnum.SceltaC, "Scelta C")
                .Add(CasaSceltaEnum.SceltaD, "Scelta D")
            End With

            With DecodeCasaDurataPoliennale
                .Add(CasaDurataPoliennaleEnum.Anni2, "2 anni")
                .Add(CasaDurataPoliennaleEnum.Anni3, "3 anni")
                .Add(CasaDurataPoliennaleEnum.Anni4, "4 anni")
                .Add(CasaDurataPoliennaleEnum.Anni5, "5 anni")
            End With

            With DecodeInfortuniScelta
                .Add(InfortuniSceltaEnum.SceltaA, "Scelta A")
                .Add(InfortuniSceltaEnum.SceltaB, "Scelta B")
                .Add(InfortuniSceltaEnum.SceltaC, "Scelta C")
                .Add(InfortuniSceltaEnum.SceltaD, "Scelta D")
            End With

            With DecodeInfortuniDurataPoliennale
                .Add(InfortuniDurataPoliennaleEnum.Anni2, "2 anni")
                .Add(InfortuniDurataPoliennaleEnum.Anni3, "3 anni")
                .Add(InfortuniDurataPoliennaleEnum.Anni4, "4 anni")
                .Add(InfortuniDurataPoliennaleEnum.Anni5, "5 anni")
            End With

            With DecodeAttivitaTipo
                .Add(AttivitaTipoEnum.Commerciali, "Commerciali")
                .Add(AttivitaTipoEnum.Artigianali, "Artigianali")
            End With

            With DecodeAttivitaScelta
                .Add(AttivitaSceltaEnum.SceltaA, "A - RCT")
                .Add(AttivitaSceltaEnum.SceltaB, "B - RCT + Incendio")
                .Add(AttivitaSceltaEnum.SceltaC, "C - RCT + Incendio + Atti Vandalici")
            End With

            With DecodeAttivitaDurataPoliennale
                .Add(AttivitaDurataPoliennaleEnum.Anni2, "2 anni")
                .Add(AttivitaDurataPoliennaleEnum.Anni3, "3 anni")
                .Add(AttivitaDurataPoliennaleEnum.Anni4, "4 anni")
                .Add(AttivitaDurataPoliennaleEnum.Anni5, "5 anni")
            End With

            With DecodeProvinciaToClasseTerritorialeFurto
                .Add(ProvinciaEnum.SiglaAG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAL, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAQ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBL, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBN, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBZ, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCA, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCH, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCL, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCN, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCZ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaEN, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFC, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFE, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFG, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFM, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaGE, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaIM, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaIS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaKR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLE, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLT, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLU, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaMB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaME, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMT, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaNO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNU, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOT, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPD, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPG, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPI, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPU, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPZ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRA, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRG, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRM, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRN, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRSM, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTV, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaUD, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVC, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVV, ClasseTerritorialeFurtoEnum.Classe2)
            End With
        End Sub
    End Class
End Namespace
