'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace Sinistri

    'CODEGEN: L'elemento di estensione WSDL facoltativo 'UsingAddressing' dallo spazio dei nomi 'http://www.w3.org/2006/05/addressing/wsdl' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="SinistriServiceForAgenzieSoapBinding", [Namespace]:="http://service.serviziagenzia.websphere.sx.unipol.it")>
    Partial Public Class SinistriServiceForAgenzieService
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol

        Private getListaSinistriDelGiornoPerUtenteOperationCompleted As System.Threading.SendOrPostCallback

        Private getSinistroDettaglioOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_Sinistri_SinistriServiceForAgenzieService
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                            AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
                    MyBase.UseDefaultCredentials = False
                End If
                MyBase.Url = Value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = Value
                Me.useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        '''<remarks/>
        Public Event getListaSinistriDelGiornoPerUtenteCompleted As getListaSinistriDelGiornoPerUtenteCompletedEventHandler

        '''<remarks/>
        Public Event getSinistroDettaglioCompleted As getSinistroDettaglioCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("getListaSinistriDelGiornoPerUtente", RequestNamespace:="http://service.serviziagenzia.websphere.sx.unipol.it", ResponseNamespace:="http://service.serviziagenzia.websphere.sx.unipol.it", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function getListaSinistriDelGiornoPerUtente(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> username As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> aDataCreazioneInizioString As String) As <System.Xml.Serialization.XmlElementAttribute("getListaSinistriDelGiornoPerUtenteReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> Result
            Dim results() As Object = Me.Invoke("getListaSinistriDelGiornoPerUtente", New Object() {username, aDataCreazioneInizioString})
            Return CType(results(0), Result)
        End Function

        '''<remarks/>
        Public Overloads Sub getListaSinistriDelGiornoPerUtenteAsync(username As String, aDataCreazioneInizioString As String)
            Me.getListaSinistriDelGiornoPerUtenteAsync(username, aDataCreazioneInizioString, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getListaSinistriDelGiornoPerUtenteAsync(username As String, aDataCreazioneInizioString As String, userState As Object)
            If (Me.getListaSinistriDelGiornoPerUtenteOperationCompleted Is Nothing) Then
                Me.getListaSinistriDelGiornoPerUtenteOperationCompleted = AddressOf Me.OngetListaSinistriDelGiornoPerUtenteOperationCompleted
            End If
            Me.InvokeAsync("getListaSinistriDelGiornoPerUtente", New Object() {username, aDataCreazioneInizioString}, Me.getListaSinistriDelGiornoPerUtenteOperationCompleted, userState)
        End Sub

        Private Sub OngetListaSinistriDelGiornoPerUtenteOperationCompleted(arg As Object)
            If (Not (Me.getListaSinistriDelGiornoPerUtenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getListaSinistriDelGiornoPerUtenteCompleted(Me, New getListaSinistriDelGiornoPerUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("getSinistroDettaglio", RequestNamespace:="http://service.serviziagenzia.websphere.sx.unipol.it", ResponseNamespace:="http://service.serviziagenzia.websphere.sx.unipol.it", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function getSinistroDettaglio(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> username As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> aNumeroSinistro As String) As <System.Xml.Serialization.XmlElementAttribute("getSinistroDettaglioReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)> Result
            Dim results() As Object = Me.Invoke("getSinistroDettaglio", New Object() {username, aNumeroSinistro})
            Return CType(results(0), Result)
        End Function

        '''<remarks/>
        Public Overloads Sub getSinistroDettaglioAsync(username As String, aNumeroSinistro As String)
            Me.getSinistroDettaglioAsync(username, aNumeroSinistro, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub getSinistroDettaglioAsync(username As String, aNumeroSinistro As String, userState As Object)
            If (Me.getSinistroDettaglioOperationCompleted Is Nothing) Then
                Me.getSinistroDettaglioOperationCompleted = AddressOf Me.OngetSinistroDettaglioOperationCompleted
            End If
            Me.InvokeAsync("getSinistroDettaglio", New Object() {username, aNumeroSinistro}, Me.getSinistroDettaglioOperationCompleted, userState)
        End Sub

        Private Sub OngetSinistroDettaglioOperationCompleted(arg As Object)
            If (Not (Me.getSinistroDettaglioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getSinistroDettaglioCompleted(Me, New getSinistroDettaglioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                Return False
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024) _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return True
            End If
            Return False
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://domain.serviziagenzia.websphere.sx.unipol.it")>
    Partial Public Class Result

        Private dettaglioSinistroField As DettaglioSinistro

        Private errorDescriptionField As String

        Private sinistroInfoListField() As InfoSinistro

        Private errorCodeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dettaglioSinistro() As DettaglioSinistro
            Get
                Return Me.dettaglioSinistroField
            End Get
            Set
                Me.dettaglioSinistroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property errorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True),
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property sinistroInfoList() As InfoSinistro()
            Get
                Return Me.sinistroInfoListField
            End Get
            Set
                Me.sinistroInfoListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property errorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://domain.serviziagenzia.websphere.sx.unipol.it")>
    Partial Public Class DettaglioSinistro

        Private codiceAgenziaField As String

        Private codiceClgField As String

        Private codiceFiscaleContraenteField As String

        Private codicePeritoField As String

        Private codiceSubAgenziaField As String

        Private convenzioneField As String

        Private dataAccadimentoField As System.Nullable(Of Date)

        Private dataAperturaSinistroField As System.Nullable(Of Date)

        Private dataDenunciaField As System.Nullable(Of Date)

        Private dataInterventoLegaleField As System.Nullable(Of Date)

        Private flagLegaleField As String

        Private liquidatoreAssegnatarioField As String

        Private nomeContraenteField As String

        Private nomeControparteField As String

        Private nostraQuotaField As System.Nullable(Of Decimal)

        Private numeroPolizzaField As String

        Private numeroPosizioniField As System.Nullable(Of Integer)

        Private numeroSinistroField As String

        Private presenzaCoseLesioniField As String

        Private prodottoField As String

        Private profiloSinistroField As String

        Private ramoPolizzaField As String

        Private ramoSinistroField As String

        Private riservaTecnicaField As System.Nullable(Of Decimal)

        Private statoTecnicoField As String

        Private targaAssicuratoField As String

        Private targaControparteField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property codiceAgenzia() As String
            Get
                Return Me.codiceAgenziaField
            End Get
            Set
                Me.codiceAgenziaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property codiceClg() As String
            Get
                Return Me.codiceClgField
            End Get
            Set
                Me.codiceClgField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property codiceFiscaleContraente() As String
            Get
                Return Me.codiceFiscaleContraenteField
            End Get
            Set
                Me.codiceFiscaleContraenteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property codicePerito() As String
            Get
                Return Me.codicePeritoField
            End Get
            Set
                Me.codicePeritoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property codiceSubAgenzia() As String
            Get
                Return Me.codiceSubAgenziaField
            End Get
            Set
                Me.codiceSubAgenziaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property convenzione() As String
            Get
                Return Me.convenzioneField
            End Get
            Set
                Me.convenzioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dataAccadimento() As System.Nullable(Of Date)
            Get
                Return Me.dataAccadimentoField
            End Get
            Set
                Me.dataAccadimentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dataAperturaSinistro() As System.Nullable(Of Date)
            Get
                Return Me.dataAperturaSinistroField
            End Get
            Set
                Me.dataAperturaSinistroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dataDenuncia() As System.Nullable(Of Date)
            Get
                Return Me.dataDenunciaField
            End Get
            Set
                Me.dataDenunciaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dataInterventoLegale() As System.Nullable(Of Date)
            Get
                Return Me.dataInterventoLegaleField
            End Get
            Set
                Me.dataInterventoLegaleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property flagLegale() As String
            Get
                Return Me.flagLegaleField
            End Get
            Set
                Me.flagLegaleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property liquidatoreAssegnatario() As String
            Get
                Return Me.liquidatoreAssegnatarioField
            End Get
            Set
                Me.liquidatoreAssegnatarioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property nomeContraente() As String
            Get
                Return Me.nomeContraenteField
            End Get
            Set
                Me.nomeContraenteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property nomeControparte() As String
            Get
                Return Me.nomeControparteField
            End Get
            Set
                Me.nomeControparteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property nostraQuota() As System.Nullable(Of Decimal)
            Get
                Return Me.nostraQuotaField
            End Get
            Set
                Me.nostraQuotaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property numeroPolizza() As String
            Get
                Return Me.numeroPolizzaField
            End Get
            Set
                Me.numeroPolizzaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property numeroPosizioni() As System.Nullable(Of Integer)
            Get
                Return Me.numeroPosizioniField
            End Get
            Set
                Me.numeroPosizioniField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property numeroSinistro() As String
            Get
                Return Me.numeroSinistroField
            End Get
            Set
                Me.numeroSinistroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property presenzaCoseLesioni() As String
            Get
                Return Me.presenzaCoseLesioniField
            End Get
            Set
                Me.presenzaCoseLesioniField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property prodotto() As String
            Get
                Return Me.prodottoField
            End Get
            Set
                Me.prodottoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property profiloSinistro() As String
            Get
                Return Me.profiloSinistroField
            End Get
            Set
                Me.profiloSinistroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property ramoPolizza() As String
            Get
                Return Me.ramoPolizzaField
            End Get
            Set
                Me.ramoPolizzaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property ramoSinistro() As String
            Get
                Return Me.ramoSinistroField
            End Get
            Set
                Me.ramoSinistroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property riservaTecnica() As System.Nullable(Of Decimal)
            Get
                Return Me.riservaTecnicaField
            End Get
            Set
                Me.riservaTecnicaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property statoTecnico() As String
            Get
                Return Me.statoTecnicoField
            End Get
            Set
                Me.statoTecnicoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property targaAssicurato() As String
            Get
                Return Me.targaAssicuratoField
            End Get
            Set
                Me.targaAssicuratoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property targaControparte() As String
            Get
                Return Me.targaControparteField
            End Get
            Set
                Me.targaControparteField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://domain.serviziagenzia.websphere.sx.unipol.it")>
    Partial Public Class InfoSinistro

        Private dataAperturaField As System.Nullable(Of Date)

        Private nomeCognomeAssicuratoField As String

        Private numeroField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property dataApertura() As System.Nullable(Of Date)
            Get
                Return Me.dataAperturaField
            End Get
            Set
                Me.dataAperturaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property nomeCognomeAssicurato() As String
            Get
                Return Me.nomeCognomeAssicuratoField
            End Get
            Set
                Me.nomeCognomeAssicuratoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=True)>
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>
    Public Delegate Sub getListaSinistriDelGiornoPerUtenteCompletedEventHandler(sender As Object, e As getListaSinistriDelGiornoPerUtenteCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class getListaSinistriDelGiornoPerUtenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Result
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Result)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>
    Public Delegate Sub getSinistroDettaglioCompletedEventHandler(sender As Object, e As getSinistroDettaglioCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class getSinistroDettaglioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Result
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Result)
            End Get
        End Property
    End Class
End Namespace
