Namespace P07263
    Public Class P07263DE
        Inherits P00000DE

        Public DecodeTipoContraenza As New Dizionario(Of Integer, String)
        Public DecodeFormaAssicurazione As New Dizionario(Of Integer, String)
        Public DecodeTipoDimora As New Dizionario(Of Integer, String)
        Public DecodeTipoAbitazione As New Dizionario(Of Integer, String)
        Public DecodeTipoUtilizzo As New Dizionario(Of Integer, String)
        Public DecodeTipologiaCostruzione As New Dizionario(Of Integer, String)
        Public DecodeAntisismico As New Dizionario(Of Integer, String)
        Public DecodeAlluvionato As New Dizionario(Of Integer, String)
        Public DecodePianoAssicurato As New Dizionario(Of Integer, String)
        Public DecodeClasseTerritorialeFurto As New Dizionario(Of Integer, String)
        Public DecodeClasseTerritorialeEventiAtmosferici As New Dizionario(Of Integer, String)
        Public DecodeClasseTerritorialeDanniAcqua As New Dizionario(Of Integer, String)
        Public DecodeClasseTerritorialeRCT As New Dizionario(Of Integer, String)
        Public DecodeRiparazionediretta As New Dizionario(Of Integer, String)
        Public DecodeDanniBeniAbitazioneFormaGaranzia As New Dizionario(Of Integer, String)
        Public DecodeDanniBeniContenutoFormaGaranzia As New Dizionario(Of Integer, String)
        Public DecodeAssistenzaPlus As New Dizionario(Of Integer, String)
        Public DecodeDanniBeniFenomeniElettricifranchigia As New Dizionario(Of Decimal, String)
        Public DecodeDanniBeniFenomeniElettricimassimale As New Dizionario(Of Decimal, String)
        Public DecodeDanniBeniFenomeniElettriciPannelliSolarifranchigia As New Dizionario(Of Decimal, String)
        Public DecodeDanniBeniFenomeniElettriciPannelliSolarimassimale As New Dizionario(Of Decimal, String)
        Public DecodeDanniBeniVetriCristallimassimale As New Dizionario(Of Decimal, String)
        Public DecodeCatastrofaliTerremotoAbitazionecombinazione As New Dizionario(Of Decimal, String)
        Public DecodeDanniTerziVitaPrivatamassimale As New Dizionario(Of Decimal, String)
        Public DecodeDanniTerziProprietamassimale As New Dizionario(Of Decimal, String)
        Public DecodeTutelaLegaleBasemassimale As New Dizionario(Of Decimal, String)
        Public DecodeProtezioneBenessereBasecombinazione As New Dizionario(Of Decimal, String)
        Public DecodeProvinciaToClasseTerritorialeEventiAtmosferici As New Dizionario(Of Integer, Integer)
        Public DecodeProvinciaToClasseTerritorialeDanniAcqua As New Dizionario(Of Integer, Integer)
        Public DecodeProvinciaToClasseTerritorialeRCT As New Dizionario(Of Integer, Integer)
        Public DecodeProvinciaToClasseTerritorialeFurto As New Dizionario(Of Integer, Integer)
        Public DecodeAlluvioneGruppoRischio As New Dizionario(Of Decimal, String)

        Sub New()
            With DecodeSezione
                .Add(TipoSezione.DanniBeni, "Danni ai beni")
                .Add(TipoSezione.Catastrofali, "Eventi Catastrofali")
                .Add(TipoSezione.AssistenzaPlus, "Assistenza Plus")
                .Add(TipoSezione.ProtezioneEmergenza, "Pack Emergenza")
                .Add(TipoSezione.Furto, "Furto e rapina")
                .Add(TipoSezione.DanniTerzi, "Danni a terzi")
                .Add(TipoSezione.TutelaLegale, "Tutela Legale")
                .Add(TipoSezione.Assistenza, "Assistenza")
                .Add(TipoSezione.ProtezioneDigitale, "Pack Protezione digitale")
                .Add(TipoSezione.ProtezioneBenessere, "Pack Protezione Benessere")
                .Add(TipoSezione.ProtezioneFamiglia, "Pack Protezione Famiglia")
            End With

            With DecodePartita
                .Add(TipoPartita.DanniBeni, "Danni ai beni")
                .Add(TipoPartita.Catastrofali, "Eventi Catastrofali")
                .Add(TipoPartita.AssistenzaPlus, "Assistenza Plus")
                .Add(TipoPartita.ProtezioneEmergenza, "Pack Emergenza")
                .Add(TipoPartita.Furto, "Furto e rapina")
                .Add(TipoPartita.DanniTerzi, "Danni a terzi")
                .Add(TipoPartita.TutelaLegale, "Tutela Legale")
                .Add(TipoPartita.Assistenza, "Assistenza")
                .Add(TipoPartita.ProtezioneDigitale, "Pack Protezione digitale")
                .Add(TipoPartita.ProtezioneBenessere, "Pack Protezione Benessere")
                .Add(TipoPartita.ProtezioneFamiglia, "Pack Protezione Famiglia")
            End With

            With DecodeGaranzia
                .Add(TipoGaranzia.DanniBeniBase, "Garanzia base")
                .Add(TipoGaranzia.DanniBeniAbitazione, "Abitazione")
                .Add(TipoGaranzia.DanniBeniContenuto, "Contenuto")
                .Add(TipoGaranzia.DanniBeniGaranziaPlus, "Garanzia Plus")
                .Add(TipoGaranzia.DanniBeniFenomeniElettrici, "Fenomeni elettrici")
                .Add(TipoGaranzia.DanniBeniFenomeniElettriciPannelliSolari, "Fenomeni Elettrici su pannelli solari e fotovoltaici")
                .Add(TipoGaranzia.DanniBeniFenomeniAtmosferici, "Fenomeni Atmosferici")
                .Add(TipoGaranzia.DanniBeniDanniDaAcqua, "Danni da acqua")
                .Add(TipoGaranzia.DanniBeniRicercaGuasto, "Ricerca Guasto")
                .Add(TipoGaranzia.DanniBeniPerditeOcculte, "Perdite occulte d'acqua")
                .Add(TipoGaranzia.DanniBeniVetriCristalli, "Vetri e cristalli")
                .Add(TipoGaranzia.CatastrofaliBase, "CatastrofaliBase")
                .Add(TipoGaranzia.CatastrofaliTerremotoAbitazione, "Terremoto Abitazione")
                .Add(TipoGaranzia.CatastrofaliTerremotoContenuto, "Terremoto Contenuto")
                .Add(TipoGaranzia.CatastrofaliAlluvioneAbitazione, "Alluvione Abitazione")
                .Add(TipoGaranzia.CatastrofaliAlluvioneContenuto, "Alluvione Contenuto")
                .Add(TipoGaranzia.AssistenzaPlusBase, "Assistenza Plus")
                .Add(TipoGaranzia.EmergenzaBase, "Pack Emergenza")
                .Add(TipoGaranzia.EmergenzaIndennitaForfettaria, "Indennità forfettaria")
                .Add(TipoGaranzia.EmergenzaRiassettoAbitazione, "Riassetto abitazione")
                .Add(TipoGaranzia.EmergenzaRiassettoPotenziamentoMezziChiusura, "Potenziamento mezzi di chiusura")
                .Add(TipoGaranzia.EmergenzaRimborsoSpeseMediche, "Rimborso spese mediche da infortunio")
                .Add(TipoGaranzia.FurtoBase, "FurtoBase")
                .Add(TipoGaranzia.DanniFurtoContenuto, "Contenuto")
                .Add(TipoGaranzia.DanniFurtoGaranziaPlus, "Garanzia Plus")
                .Add(TipoGaranzia.DanniFurtoValoriNonCustoditi, "Preziosi e Valori ovunque posti")
                .Add(TipoGaranzia.DanniFurtoValoriCustoditi, "Preziosi e Valori nei mezzi di custodia")
                '.Add(TipoGaranzia.DanniFurtoSocioPolitico, "Furto e Rapina avvenuta in occasione di eventi sociopolitici")
                .Add(TipoGaranzia.DanniFurtoSocioPolitico, "Furto e Rapina causati da eventi sociopolitici")
                .Add(TipoGaranzia.DanniFurtoPannelli, "Furto e Rapina Pannelli solari e fotovoltaici")
                .Add(TipoGaranzia.DanniFurtoEsterno, "Furto, Scippo e Rapina all' esterno dell'abitazione")
                .Add(TipoGaranzia.DanniFurtoImpiantoAllarme, "Impianto d'allarme")
                .Add(TipoGaranzia.DanniTerziBase, "Danni a terzi Base")
                .Add(TipoGaranzia.DanniTerziIncendio, "Danni a Terzi da Incendio")
                .Add(TipoGaranzia.DanniTerziVitaPrivata, "Vita privata")
                .Add(TipoGaranzia.DanniTerziProprieta, "Proprietà dell'Abitazione")
                .Add(TipoGaranzia.DanniTerziPlus, "Garanzie Plus")
                .Add(TipoGaranzia.DanniTerziLavoro, "Lavoratori domestici e malattie professionali")
                .Add(TipoGaranzia.DanniTerziBeB, "Bed & Breakfast e affittacamere")
                .Add(TipoGaranzia.DanniTerziLocazione, "Abitazione locata a terzi")
                .Add(TipoGaranzia.DanniTerziStage, "Stage e tirocini")
                .Add(TipoGaranzia.TutelaLegaleBase, "Garanzia base")
                .Add(TipoGaranzia.TutelaLegaleDivorzio, "Separazione e Divorzio")
                .Add(TipoGaranzia.AssistenzaBase, "Garanzia base")
                .Add(TipoGaranzia.ProtezioneDigitaleBase, "Pack Protezione digitale")
                .Add(TipoGaranzia.ProtezioneDigitaleAssistenzaMalware, "Assistenza Malware")
                .Add(TipoGaranzia.ProtezioneDigitaleCyberBullismo, "Cyber Bullismo")
                .Add(TipoGaranzia.ProtezioneDigitaleLesioneReputazione, "Lesione reputazione")
                .Add(TipoGaranzia.ProtezioneDigitaleProtezioneLegale, "Protezione legale")
                .Add(TipoGaranzia.ProtezioneBenessereBase, "Pack Protezione Benessere")
                .Add(TipoGaranzia.ProtezioneBenessere45gg, "Infortuni con prognosi più di 45gg")
                .Add(TipoGaranzia.ProtezioneBenesserePerditaImpiego, "Perdita di impiego")
                .Add(TipoGaranzia.ProtezioneFamigliaBase, "Pack Protezione Famiglia")
                .Add(TipoGaranzia.ProtezioneFamigliaSostegnoFigli, "Sostegno figli")
                .Add(TipoGaranzia.ProtezioneFamigliaSostegnoEducazione, "Sostegno educazione")
                .Add(TipoGaranzia.ProtezioneSostegnoDisabilita, "Sostegno disabilità")
                .Add(TipoGaranzia.ProtezioneFamigliaSostegnoDomestico, "Sostegno Domestico")
            End With

            With DecodeFrazionamenti
                .Add(FrazionamentiEnum.temporaneo, "temporaneo")
                .Add(FrazionamentiEnum.annuale, "annuale")
                .Add(FrazionamentiEnum.semestrale, "semestrale")
                .Add(FrazionamentiEnum.mensile, "mensile (SDD)")
                .Add(FrazionamentiEnum.unicoAnticipato, "unico anticipato")
            End With

            With DecodeTipoContraenza
                .Add(TipoContraenzaEnum.PersonaFisica, "Persona fisica")
                .Add(TipoContraenzaEnum.PersonaGiudirica, "Persona giudirica")
            End With

            With DecodeFormaAssicurazione
                .Add(FormaAssicurazioneEnum.ValoreInteroNuovo, "Valore intero e a nuovo")
                .Add(FormaAssicurazioneEnum.ValoreInteroCommerciale, "Valore intero e commerciale")
                .Add(FormaAssicurazioneEnum.valorePrimoRischioNuovo, "Valore primo rischio e a nuovo")
                .Add(FormaAssicurazioneEnum.valorePrimoRischioCommerciale, "Valore primo rischio e commerciale")
            End With

            With DecodeTipoDimora
                .Add(TipoDimoraEnum.Abituale, "Abituale")
                .Add(TipoDimoraEnum.NonAbituale, "Non abituale")
                .Add(TipoDimoraEnum.Locata, "Locata")
            End With

            With DecodeTipoAbitazione
                .Add(TipoAbitazioneEnum.Appartamento, "Appartamento")
                .Add(TipoAbitazioneEnum.VillaSingola, "Villa singola")
                .Add(TipoAbitazioneEnum.VillaSchiera, "Villa a schiera")
            End With

            With DecodeTipoUtilizzo
                .Add(TipoUtilizzoEnum.Proprietario, "Proprietario")
                .Add(TipoUtilizzoEnum.Affittuario, "Affittuario")
            End With

            With DecodeTipologiaCostruzione
                .Add(TipologiaCostruzioneEnum.CementoArmato, "Cemento armato")
                .Add(TipologiaCostruzioneEnum.Muratura, "Muratura")
                .Add(TipologiaCostruzioneEnum.Bioedilizia, "Bioedilizia")
                .Add(TipologiaCostruzioneEnum.Legno, "Legno")
            End With

            With DecodeAntisismico
                .Add(AntisismicoEnum.SI, "Si")
                .Add(AntisismicoEnum.NO, "No")
            End With

            With DecodeAlluvionato
                .Add(AlluvionatoEnum.SI, "Si")
                .Add(AlluvionatoEnum.NO, "No")
            End With

            With DecodePianoAssicurato
                .Add(PianoAssicuratoEnum.Sotterraneo, "Sotterraneo")
                .Add(PianoAssicuratoEnum.Interrato, "Interrato")
                .Add(PianoAssicuratoEnum.PianoTerra, "Piano terra")
                .Add(PianoAssicuratoEnum.PianoRialzato, "Piano rialzato")
                .Add(PianoAssicuratoEnum.PrimoAlto, "Primo piano ed altri")
                .Add(PianoAssicuratoEnum.FabbricatoIntero, "Intero fabbricato")
            End With

            With DecodeClasseTerritorialeFurto
                .Add(ClasseTerritorialeFurtoEnum.Classe1, "1")
                .Add(ClasseTerritorialeFurtoEnum.Classe2, "2")
                .Add(ClasseTerritorialeFurtoEnum.Classe3, "3")
            End With

            With DecodeClasseTerritorialeEventiAtmosferici
                .Add(ClasseTerritorialeEventiAtmosfericiEnum.Classe1, "Classe 1")
                .Add(ClasseTerritorialeEventiAtmosfericiEnum.Classe2, "Classe 2")
                .Add(ClasseTerritorialeEventiAtmosfericiEnum.Classe3, "Classe 3")
            End With

            With DecodeClasseTerritorialeDanniAcqua
                .Add(ClasseTerritorialeDanniAcquaEnum.Classe1, "Classe 1")
                .Add(ClasseTerritorialeDanniAcquaEnum.Classe2, "Classe 2")
                .Add(ClasseTerritorialeDanniAcquaEnum.Classe3, "Classe 3")
            End With

            With DecodeClasseTerritorialeRCT
                .Add(ClasseTerritorialeRCTEnum.Classe1, "Classe 1")
                .Add(ClasseTerritorialeRCTEnum.Classe2, "Classe 2")
                .Add(ClasseTerritorialeRCTEnum.Classe3, "Classe 3")
            End With

            With DecodeRiparazionediretta
                .Add(RiparazionedirettaEnum.SI, "Riparazione diretta Si")
                .Add(RiparazionedirettaEnum.NO, "Riparazione diretta No")
            End With

            With DecodeDanniBeniAbitazioneFormaGaranzia
                .Add(DanniBeniAbitazioneFormaGaranziaEnum.ValoreIntero, "Valore intero")
                .Add(DanniBeniAbitazioneFormaGaranziaEnum.ValorePRA50, "Valore primo rischio assoluto 50.000")
                .Add(DanniBeniAbitazioneFormaGaranziaEnum.ValorePRA100, "Valore primo rischio assoluto 100.000")
            End With

            With DecodeDanniBeniContenutoFormaGaranzia
                .Add(DanniBeniContenutoFormaGaranziaEnum.ValoreIntero, "Valore intero")
                .Add(DanniBeniContenutoFormaGaranziaEnum.ValorePRA, "Valore primo rischio assoluto")
            End With

            With DecodeAssistenzaPlus
                .Add(AssistenzaPlusEnum.Easy, "Easy")
                .Add(AssistenzaPlusEnum.Full, "Full")
                .Add(AssistenzaPlusEnum.Top, "Top")
            End With
            With DecodeDanniBeniFenomeniElettricifranchigia
                .Add(150, "Franchigia E. 150,00")
                .Add(250, "Franchigia E. 250,00")
            End With
            With DecodeDanniBeniFenomeniElettricimassimale
                .Add(500, "E. 500,00")
                .Add(1000, "E. 1.000,00")
                .Add(2000, "E. 2.000,00")
                .Add(5000, "E. 5.000,00")
                .Add(10000, "E. 10.000,00")
                .Add(20000, "E. 20.000,00")
            End With
            With DecodeDanniBeniFenomeniElettriciPannelliSolarifranchigia
                .Add(150, "Franchigia E. 150,00")
                .Add(250, "Franchigia E. 250,00")
            End With
            With DecodeDanniBeniFenomeniElettriciPannelliSolarimassimale
                .Add(10000, "E. 10.000,00")
                .Add(20000, "E. 20.000,00")
            End With
            With DecodeDanniBeniVetriCristallimassimale
                .Add(500, "E. 500,00")
                .Add(1000, "E. 1.000,00")
                .Add(2000, "E. 2.000,00")
                .Add(5000, "E. 5.000,00")
                .Add(10000, "E. 10.000,00")
            End With
            With DecodeCatastrofaliTerremotoAbitazionecombinazione
                .Add(70, "Limite 70%, scoperto 10% minimo 10.000,00")
                .Add(100, "Limite 100%, scoperto 10% minimo 10.000,00")
            End With
            With DecodeDanniTerziVitaPrivatamassimale
                .Add(500000, "Massimale E. 500.000,00")
                .Add(1000000, "Massimale E. 1.000.000,00")
                .Add(3000000, "Massimale E. 3.000.000,00")
                .Add(5000000, "Massimale E. 5.000.000,00")
            End With
            With DecodeDanniTerziProprietamassimale
                .Add(500000, "Massimale E. 500.000,00")
                .Add(1000000, "Massimale E. 1.000.000,00")
                .Add(3000000, "Massimale E. 3.000.000,00")
                .Add(5000000, "Massimale E. 5.000.000,00")
            End With
            With DecodeTutelaLegaleBasemassimale
                .Add(10000, "Massimale E. 10.000,00")
                .Add(20000, "Massimale E. 20.000,00")
            End With
            With DecodeProtezioneBenessereBasecombinazione
                .Add(1500, "Indennizzo forfettario 1.500,00")
                .Add(3000, "Indennizzo forfettario 3.000,00")
            End With

            With DecodeAlluvioneGruppoRischio
                .Add(AlluvioneGruppoRischioEnum.P0, "Rischio P0")
                .Add(AlluvioneGruppoRischioEnum.P1, "Rischio P1")
                .Add(AlluvioneGruppoRischioEnum.P2, "Rischio P2")
                .Add(AlluvioneGruppoRischioEnum.P3, "Rischio P3")
            End With

            With DecodeProvinciaToClasseTerritorialeEventiAtmosferici
                .Add(ProvinciaEnum.SiglaAN, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAP, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAQ, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAT, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBI, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBS, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCH, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCR, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCZ, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFM, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaKR, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLE, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLU, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaMC, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaMS, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaMT, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPD, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPE, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPN, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPT, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPU, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPV, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPZ, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSP, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTE, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTV, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVE, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVI, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVR, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVV, ClasseTerritorialeEventiAtmosfericiEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAL, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAR, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAV, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBA, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBG, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBN, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBT, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCB, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCE, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCN, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCS, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCT, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaEN, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFC, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFE, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFR, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaIS, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLC, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLT, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMN, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNA, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNU, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOG, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOT, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPC, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPG, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPI, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRC, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRG, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRN, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRSM, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSA, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSR, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSS, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTA, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTO, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTR, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaUD, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVA, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVB, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVC, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVT, ClasseTerritorialeEventiAtmosfericiEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAG, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAO, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBL, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBO, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBR, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBZ, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCA, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCL, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFG, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGE, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGO, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGR, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaIM, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVS, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaME, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMB, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaOR, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPA, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPR, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRA, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRE, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRM, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSCV, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSI, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSO, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSV, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTN, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTP, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTS, ClasseTerritorialeEventiAtmosfericiEnum.Classe3)
            End With
            With DecodeProvinciaToClasseTerritorialeDanniAcqua
                .Add(ProvinciaEnum.SiglaAL, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAP, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAQ, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAR, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBS, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCA, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCB, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCH, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCI, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCR, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCS, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCT, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCZ, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFG, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFI, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFM, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaGR, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaIM, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaKR, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLO, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLT, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVS, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaME, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaMS, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaNA, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaOT, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPA, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPE, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPG, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPI, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPO, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPT, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPV, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRC, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRG, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRI, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRM, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSCV, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSI, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSP, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSS, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTE, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTR, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVT, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVV, ClasseTerritorialeDanniAcquaEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAG, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAN, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAV, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBA, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBN, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBT, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCL, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCN, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaEN, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaGE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaGO, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaIS, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLI, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLU, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMC, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMI, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMN, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMO, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMT, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMB, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNO, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNU, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOG, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPD, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPU, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPZ, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRO, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSA, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSV, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTA, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTO, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTP, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVC, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVE, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVI, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVR, ClasseTerritorialeDanniAcquaEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAO, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAT, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBG, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBI, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBL, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBO, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBZ, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCO, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFC, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLC, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPC, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPN, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRA, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRN, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRSM, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSO, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTN, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTS, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTV, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaUD, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVA, ClasseTerritorialeDanniAcquaEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVB, ClasseTerritorialeDanniAcquaEnum.Classe3)
            End With
            With DecodeProvinciaToClasseTerritorialeRCT
                .Add(ProvinciaEnum.SiglaAL, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAT, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBA, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBI, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBL, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBN, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBT, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCA, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCI, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFE, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaGO, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaIS, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaKR, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLC, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLE, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLO, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaVS, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaNO, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaOR, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPC, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPN, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPZ, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRO, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSR, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTA, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTP, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaUD, ClasseTerritorialeRCTEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBG, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBR, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBS, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBZ, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCL, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCO, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCR, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaEN, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFC, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFG, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFI, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaGR, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaIM, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLT, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMC, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMI, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMN, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMO, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMT, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMB, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOT, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPG, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPR, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPT, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPU, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPV, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRE, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSA, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSI, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSO, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSS, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSV, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTO, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTV, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVB, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVE, ClasseTerritorialeRCTEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAG, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAN, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAO, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAP, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAQ, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAR, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAV, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBO, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCB, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCE, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCH, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCN, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCS, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCT, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCZ, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFM, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFR, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGE, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLI, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLU, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaME, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMS, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaNA, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaNU, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaOG, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPA, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPD, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPE, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPI, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPO, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRA, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRC, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRG, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRI, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRM, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRN, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRSM, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSCV, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSP, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTE, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTN, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTR, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTS, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVA, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVC, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVI, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVR, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVT, ClasseTerritorialeRCTEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVV, ClasseTerritorialeRCTEnum.Classe3)
            End With
            With DecodeProvinciaToClasseTerritorialeFurto
                .Add(ProvinciaEnum.SiglaAP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaBT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCN, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaCT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFG, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaFM, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLE, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaLU, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaNA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPI, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaPT, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRG, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRN, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaRSM, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaSP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTA, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaTP, ClasseTerritorialeFurtoEnum.Classe1)
                .Add(ProvinciaEnum.SiglaAG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAQ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBN, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaBS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCH, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCL, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaCZ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaEN, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaFR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaIS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaKR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaLT, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMS, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMT, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaMB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaNU, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOG, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaOR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPU, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaPZ, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRC, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaRM, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSCV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaSV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTO, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaTR, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVA, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVB, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVE, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVI, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaVV, ClasseTerritorialeFurtoEnum.Classe2)
                .Add(ProvinciaEnum.SiglaAL, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaAO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBL, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaBZ, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCA, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaCS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFC, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFE, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaFI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGE, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaGR, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaIM, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaLO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaME, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaMN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaOT, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPD, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPG, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaPO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRA, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaRO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSI, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSO, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaSS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTN, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTS, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaTV, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaUD, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVC, ClasseTerritorialeFurtoEnum.Classe3)
                .Add(ProvinciaEnum.SiglaVR, ClasseTerritorialeFurtoEnum.Classe3)
            End With
        End Sub
    End Class
End Namespace
