'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace UploadSia
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FileUploaderSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FileUploader
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private UploadFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastDateUploaderOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsAgeActiveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastRealDateUploaderOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListDateTransferOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WsAutheticatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_UploadSia_FileUploader
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event UploadFileCompleted As UploadFileCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastDateUploaderCompleted As GetLastDateUploaderCompletedEventHandler
        
        '''<remarks/>
        Public Event IsAgeActiveCompleted As IsAgeActiveCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastRealDateUploaderCompleted As GetLastRealDateUploaderCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListDateTransferCompleted As GetListDateTransferCompletedEventHandler
        
        '''<remarks/>
        Public Event WsAutheticatesCompleted As WsAutheticatesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UploadFile(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> f() As Byte, fileName As String) As String
            Dim results() As Object = Me.Invoke("UploadFile", New Object() {f, fileName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(f() As Byte, fileName As String)
            Me.UploadFileAsync(f, fileName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(f() As Byte, fileName As String, userState As Object)
            If (Me.UploadFileOperationCompleted Is Nothing) Then
                Me.UploadFileOperationCompleted = AddressOf Me.OnUploadFileOperationCompleted
            End If
            Me.InvokeAsync("UploadFile", New Object() {f, fileName}, Me.UploadFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnUploadFileOperationCompleted(arg As Object)
            If (Not (Me.UploadFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UploadFileCompleted(Me, New UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastDateUploader", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastDateUploader(CodAge As String) As Date
            Dim results() As Object = Me.Invoke("GetLastDateUploader", New Object() {CodAge})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastDateUploaderAsync(CodAge As String)
            Me.GetLastDateUploaderAsync(CodAge, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastDateUploaderAsync(CodAge As String, userState As Object)
            If (Me.GetLastDateUploaderOperationCompleted Is Nothing) Then
                Me.GetLastDateUploaderOperationCompleted = AddressOf Me.OnGetLastDateUploaderOperationCompleted
            End If
            Me.InvokeAsync("GetLastDateUploader", New Object() {CodAge}, Me.GetLastDateUploaderOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastDateUploaderOperationCompleted(arg As Object)
            If (Not (Me.GetLastDateUploaderCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastDateUploaderCompleted(Me, New GetLastDateUploaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsAgeActive", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsAgeActive(CodAge As String) As Boolean
            Dim results() As Object = Me.Invoke("IsAgeActive", New Object() {CodAge})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsAgeActiveAsync(CodAge As String)
            Me.IsAgeActiveAsync(CodAge, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsAgeActiveAsync(CodAge As String, userState As Object)
            If (Me.IsAgeActiveOperationCompleted Is Nothing) Then
                Me.IsAgeActiveOperationCompleted = AddressOf Me.OnIsAgeActiveOperationCompleted
            End If
            Me.InvokeAsync("IsAgeActive", New Object() {CodAge}, Me.IsAgeActiveOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsAgeActiveOperationCompleted(arg As Object)
            If (Not (Me.IsAgeActiveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsAgeActiveCompleted(Me, New IsAgeActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastRealDateUploader", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastRealDateUploader(CodAge As String) As Date
            Dim results() As Object = Me.Invoke("GetLastRealDateUploader", New Object() {CodAge})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastRealDateUploaderAsync(CodAge As String)
            Me.GetLastRealDateUploaderAsync(CodAge, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastRealDateUploaderAsync(CodAge As String, userState As Object)
            If (Me.GetLastRealDateUploaderOperationCompleted Is Nothing) Then
                Me.GetLastRealDateUploaderOperationCompleted = AddressOf Me.OnGetLastRealDateUploaderOperationCompleted
            End If
            Me.InvokeAsync("GetLastRealDateUploader", New Object() {CodAge}, Me.GetLastRealDateUploaderOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastRealDateUploaderOperationCompleted(arg As Object)
            If (Not (Me.GetLastRealDateUploaderCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastRealDateUploaderCompleted(Me, New GetLastRealDateUploaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDateTransfer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListDateTransfer(CodAge As String, From As Date, [To] As Date) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetListDateTransfer", New Object() {CodAge, From, [To]})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListDateTransferAsync(CodAge As String, From As Date, [To] As Date)
            Me.GetListDateTransferAsync(CodAge, From, [To], Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListDateTransferAsync(CodAge As String, From As Date, [To] As Date, userState As Object)
            If (Me.GetListDateTransferOperationCompleted Is Nothing) Then
                Me.GetListDateTransferOperationCompleted = AddressOf Me.OnGetListDateTransferOperationCompleted
            End If
            Me.InvokeAsync("GetListDateTransfer", New Object() {CodAge, From, [To]}, Me.GetListDateTransferOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListDateTransferOperationCompleted(arg As Object)
            If (Not (Me.GetListDateTransferCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListDateTransferCompleted(Me, New GetListDateTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WsAutheticates", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WsAutheticates(CodAge As String, UserName As String, Password As String) As String
            Dim results() As Object = Me.Invoke("WsAutheticates", New Object() {CodAge, UserName, Password})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WsAutheticatesAsync(CodAge As String, UserName As String, Password As String)
            Me.WsAutheticatesAsync(CodAge, UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WsAutheticatesAsync(CodAge As String, UserName As String, Password As String, userState As Object)
            If (Me.WsAutheticatesOperationCompleted Is Nothing) Then
                Me.WsAutheticatesOperationCompleted = AddressOf Me.OnWsAutheticatesOperationCompleted
            End If
            Me.InvokeAsync("WsAutheticates", New Object() {CodAge, UserName, Password}, Me.WsAutheticatesOperationCompleted, userState)
        End Sub
        
        Private Sub OnWsAutheticatesOperationCompleted(arg As Object)
            If (Not (Me.WsAutheticatesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WsAutheticatesCompleted(Me, New WsAutheticatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UploadFileCompletedEventHandler(sender As Object, e As UploadFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UploadFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetLastDateUploaderCompletedEventHandler(sender As Object, e As GetLastDateUploaderCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastDateUploaderCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub IsAgeActiveCompletedEventHandler(sender As Object, e As IsAgeActiveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsAgeActiveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetLastRealDateUploaderCompletedEventHandler(sender As Object, e As GetLastRealDateUploaderCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastRealDateUploaderCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetListDateTransferCompletedEventHandler(sender As Object, e As GetListDateTransferCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListDateTransferCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub WsAutheticatesCompletedEventHandler(sender As Object, e As WsAutheticatesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WsAutheticatesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
