'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SettingAgenzia
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConfiguraSedeSoap", [Namespace]:="http://www.utools.it/asp/SettingAgenzia")>  _
    Partial Public Class ConfiguraSede
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CodiciDownloadExOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AbilitazioniSedeStringaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ForzatureDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AgenzieCollegateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TabellaAgenzieCollegateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AgenziaBloccataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TipologiaAgenziaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AgenziaBloccataAspOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CercaAggiornamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListinoSmsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProvinceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DatiVersioneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DatiVersioneLivelloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VersioneLivelloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Assicoop2CodiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CodiciSubOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConfigAgenziaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AbilitazioniOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InviaProdottiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InviaDatiSinistriOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InvioProdottiEffettuatoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InvioDatiSinistriOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraLogUsoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReferentiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Comunicazioni.My.MySettings.Default.Comunicazioni_SettingAgenzia_ConfiguraSede
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CodiciDownloadExCompleted As CodiciDownloadExCompletedEventHandler
        
        '''<remarks/>
        Public Event AbilitazioniSedeStringaCompleted As AbilitazioniSedeStringaCompletedEventHandler
        
        '''<remarks/>
        Public Event ForzatureDLCompleted As ForzatureDLCompletedEventHandler
        
        '''<remarks/>
        Public Event AgenzieCollegateCompleted As AgenzieCollegateCompletedEventHandler
        
        '''<remarks/>
        Public Event TabellaAgenzieCollegateCompleted As TabellaAgenzieCollegateCompletedEventHandler
        
        '''<remarks/>
        Public Event AgenziaBloccataCompleted As AgenziaBloccataCompletedEventHandler
        
        '''<remarks/>
        Public Event TipologiaAgenziaCompleted As TipologiaAgenziaCompletedEventHandler
        
        '''<remarks/>
        Public Event AgenziaBloccataAspCompleted As AgenziaBloccataAspCompletedEventHandler
        
        '''<remarks/>
        Public Event CercaAggiornamentoCompleted As CercaAggiornamentoCompletedEventHandler
        
        '''<remarks/>
        Public Event ListinoSmsCompleted As ListinoSmsCompletedEventHandler
        
        '''<remarks/>
        Public Event ProvinceCompleted As ProvinceCompletedEventHandler
        
        '''<remarks/>
        Public Event DatiVersioneCompleted As DatiVersioneCompletedEventHandler
        
        '''<remarks/>
        Public Event DatiVersioneLivelloCompleted As DatiVersioneLivelloCompletedEventHandler
        
        '''<remarks/>
        Public Event VersioneLivelloCompleted As VersioneLivelloCompletedEventHandler
        
        '''<remarks/>
        Public Event Assicoop2CodiceCompleted As Assicoop2CodiceCompletedEventHandler
        
        '''<remarks/>
        Public Event CodiciSubCompleted As CodiciSubCompletedEventHandler
        
        '''<remarks/>
        Public Event ConfigAgenziaCompleted As ConfigAgenziaCompletedEventHandler
        
        '''<remarks/>
        Public Event AbilitazioniCompleted As AbilitazioniCompletedEventHandler
        
        '''<remarks/>
        Public Event InviaProdottiCompleted As InviaProdottiCompletedEventHandler
        
        '''<remarks/>
        Public Event InviaDatiSinistriCompleted As InviaDatiSinistriCompletedEventHandler
        
        '''<remarks/>
        Public Event InvioProdottiEffettuatoCompleted As InvioProdottiEffettuatoCompletedEventHandler
        
        '''<remarks/>
        Public Event InvioDatiSinistriCompleted As InvioDatiSinistriCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraLogUsoCompleted As RegistraLogUsoCompletedEventHandler
        
        '''<remarks/>
        Public Event ReferentiCompleted As ReferentiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/CodiciDownloadEx", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CodiciDownloadEx(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, CodiceControllo As Integer, ByRef ConsensoImportazione As Boolean, ByRef Errore As String, ByRef ErroreForzature As String, ByRef ErroreListe As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("CodiciDownloadEx", New Object() {Compagnia, CodiceAgenzia, CodiceSede, CodiceControllo, ConsensoImportazione, Errore, ErroreForzature, ErroreListe})
            ConsensoImportazione = CType(results(1),Boolean)
            Errore = CType(results(2),String)
            ErroreForzature = CType(results(3),String)
            ErroreListe = CType(results(4),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CodiciDownloadExAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, CodiceControllo As Integer, ConsensoImportazione As Boolean, Errore As String, ErroreForzature As String, ErroreListe As String)
            Me.CodiciDownloadExAsync(Compagnia, CodiceAgenzia, CodiceSede, CodiceControllo, ConsensoImportazione, Errore, ErroreForzature, ErroreListe, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CodiciDownloadExAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, CodiceControllo As Integer, ConsensoImportazione As Boolean, Errore As String, ErroreForzature As String, ErroreListe As String, userState As Object)
            If (Me.CodiciDownloadExOperationCompleted Is Nothing) Then
                Me.CodiciDownloadExOperationCompleted = AddressOf Me.OnCodiciDownloadExOperationCompleted
            End If
            Me.InvokeAsync("CodiciDownloadEx", New Object() {Compagnia, CodiceAgenzia, CodiceSede, CodiceControllo, ConsensoImportazione, Errore, ErroreForzature, ErroreListe}, Me.CodiciDownloadExOperationCompleted, userState)
        End Sub
        
        Private Sub OnCodiciDownloadExOperationCompleted(arg As Object)
            If (Not (Me.CodiciDownloadExCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CodiciDownloadExCompleted(Me, New CodiciDownloadExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/AbilitazioniSedeStringa", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AbilitazioniSedeStringa(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String) As String
            Dim results() As Object = Me.Invoke("AbilitazioniSedeStringa", New Object() {Compagnia, CodiceAgenzia, CodiceSede})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AbilitazioniSedeStringaAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String)
            Me.AbilitazioniSedeStringaAsync(Compagnia, CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AbilitazioniSedeStringaAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.AbilitazioniSedeStringaOperationCompleted Is Nothing) Then
                Me.AbilitazioniSedeStringaOperationCompleted = AddressOf Me.OnAbilitazioniSedeStringaOperationCompleted
            End If
            Me.InvokeAsync("AbilitazioniSedeStringa", New Object() {Compagnia, CodiceAgenzia, CodiceSede}, Me.AbilitazioniSedeStringaOperationCompleted, userState)
        End Sub
        
        Private Sub OnAbilitazioniSedeStringaOperationCompleted(arg As Object)
            If (Not (Me.AbilitazioniSedeStringaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AbilitazioniSedeStringaCompleted(Me, New AbilitazioniSedeStringaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/ForzatureDL", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ForzatureDL(CodiceAgenzia As String, CodiceSede As String) As String
            Dim results() As Object = Me.Invoke("ForzatureDL", New Object() {CodiceAgenzia, CodiceSede})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ForzatureDLAsync(CodiceAgenzia As String, CodiceSede As String)
            Me.ForzatureDLAsync(CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ForzatureDLAsync(CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.ForzatureDLOperationCompleted Is Nothing) Then
                Me.ForzatureDLOperationCompleted = AddressOf Me.OnForzatureDLOperationCompleted
            End If
            Me.InvokeAsync("ForzatureDL", New Object() {CodiceAgenzia, CodiceSede}, Me.ForzatureDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnForzatureDLOperationCompleted(arg As Object)
            If (Not (Me.ForzatureDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ForzatureDLCompleted(Me, New ForzatureDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/AgenzieCollegate", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AgenzieCollegate(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String) As String
            Dim results() As Object = Me.Invoke("AgenzieCollegate", New Object() {Compagnia, CodiceAgenzia, CodiceSede})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AgenzieCollegateAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String)
            Me.AgenzieCollegateAsync(Compagnia, CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AgenzieCollegateAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.AgenzieCollegateOperationCompleted Is Nothing) Then
                Me.AgenzieCollegateOperationCompleted = AddressOf Me.OnAgenzieCollegateOperationCompleted
            End If
            Me.InvokeAsync("AgenzieCollegate", New Object() {Compagnia, CodiceAgenzia, CodiceSede}, Me.AgenzieCollegateOperationCompleted, userState)
        End Sub
        
        Private Sub OnAgenzieCollegateOperationCompleted(arg As Object)
            If (Not (Me.AgenzieCollegateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AgenzieCollegateCompleted(Me, New AgenzieCollegateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/TabellaAgenzieCollegate", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TabellaAgenzieCollegate(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TabellaAgenzieCollegate", New Object() {Compagnia, CodiceAgenzia, CodiceSede})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TabellaAgenzieCollegateAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String)
            Me.TabellaAgenzieCollegateAsync(Compagnia, CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TabellaAgenzieCollegateAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.TabellaAgenzieCollegateOperationCompleted Is Nothing) Then
                Me.TabellaAgenzieCollegateOperationCompleted = AddressOf Me.OnTabellaAgenzieCollegateOperationCompleted
            End If
            Me.InvokeAsync("TabellaAgenzieCollegate", New Object() {Compagnia, CodiceAgenzia, CodiceSede}, Me.TabellaAgenzieCollegateOperationCompleted, userState)
        End Sub
        
        Private Sub OnTabellaAgenzieCollegateOperationCompleted(arg As Object)
            If (Not (Me.TabellaAgenzieCollegateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TabellaAgenzieCollegateCompleted(Me, New TabellaAgenzieCollegateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/AgenziaBloccata", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AgenziaBloccata(Compagnia As Integer, CodiceAgenzia As Integer, Pc As String, VersioneUt As String, ByRef Prod As String, ByRef Test As String, ByRef Lab As String, ByRef Gruppo As String, ByRef Errore As String) As Boolean
            Dim results() As Object = Me.Invoke("AgenziaBloccata", New Object() {Compagnia, CodiceAgenzia, Pc, VersioneUt, Prod, Test, Lab, Gruppo, Errore})
            Prod = CType(results(1),String)
            Test = CType(results(2),String)
            Lab = CType(results(3),String)
            Gruppo = CType(results(4),String)
            Errore = CType(results(5),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AgenziaBloccataAsync(Compagnia As Integer, CodiceAgenzia As Integer, Pc As String, VersioneUt As String, Prod As String, Test As String, Lab As String, Gruppo As String, Errore As String)
            Me.AgenziaBloccataAsync(Compagnia, CodiceAgenzia, Pc, VersioneUt, Prod, Test, Lab, Gruppo, Errore, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AgenziaBloccataAsync(Compagnia As Integer, CodiceAgenzia As Integer, Pc As String, VersioneUt As String, Prod As String, Test As String, Lab As String, Gruppo As String, Errore As String, userState As Object)
            If (Me.AgenziaBloccataOperationCompleted Is Nothing) Then
                Me.AgenziaBloccataOperationCompleted = AddressOf Me.OnAgenziaBloccataOperationCompleted
            End If
            Me.InvokeAsync("AgenziaBloccata", New Object() {Compagnia, CodiceAgenzia, Pc, VersioneUt, Prod, Test, Lab, Gruppo, Errore}, Me.AgenziaBloccataOperationCompleted, userState)
        End Sub
        
        Private Sub OnAgenziaBloccataOperationCompleted(arg As Object)
            If (Not (Me.AgenziaBloccataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AgenziaBloccataCompleted(Me, New AgenziaBloccataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/TipologiaAgenzia", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TipologiaAgenzia(Compagnia As Integer, Agenzia As Integer, ByRef Prod As String, ByRef Test As String, ByRef Lab As String, ByRef Gruppo As String) As String
            Dim results() As Object = Me.Invoke("TipologiaAgenzia", New Object() {Compagnia, Agenzia, Prod, Test, Lab, Gruppo})
            Prod = CType(results(1),String)
            Test = CType(results(2),String)
            Lab = CType(results(3),String)
            Gruppo = CType(results(4),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TipologiaAgenziaAsync(Compagnia As Integer, Agenzia As Integer, Prod As String, Test As String, Lab As String, Gruppo As String)
            Me.TipologiaAgenziaAsync(Compagnia, Agenzia, Prod, Test, Lab, Gruppo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TipologiaAgenziaAsync(Compagnia As Integer, Agenzia As Integer, Prod As String, Test As String, Lab As String, Gruppo As String, userState As Object)
            If (Me.TipologiaAgenziaOperationCompleted Is Nothing) Then
                Me.TipologiaAgenziaOperationCompleted = AddressOf Me.OnTipologiaAgenziaOperationCompleted
            End If
            Me.InvokeAsync("TipologiaAgenzia", New Object() {Compagnia, Agenzia, Prod, Test, Lab, Gruppo}, Me.TipologiaAgenziaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTipologiaAgenziaOperationCompleted(arg As Object)
            If (Not (Me.TipologiaAgenziaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TipologiaAgenziaCompleted(Me, New TipologiaAgenziaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/AgenziaBloccataAsp", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AgenziaBloccataAsp(Compagnia As Integer, CodiceAgenzia As Integer) As Boolean
            Dim results() As Object = Me.Invoke("AgenziaBloccataAsp", New Object() {Compagnia, CodiceAgenzia})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AgenziaBloccataAspAsync(Compagnia As Integer, CodiceAgenzia As Integer)
            Me.AgenziaBloccataAspAsync(Compagnia, CodiceAgenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AgenziaBloccataAspAsync(Compagnia As Integer, CodiceAgenzia As Integer, userState As Object)
            If (Me.AgenziaBloccataAspOperationCompleted Is Nothing) Then
                Me.AgenziaBloccataAspOperationCompleted = AddressOf Me.OnAgenziaBloccataAspOperationCompleted
            End If
            Me.InvokeAsync("AgenziaBloccataAsp", New Object() {Compagnia, CodiceAgenzia}, Me.AgenziaBloccataAspOperationCompleted, userState)
        End Sub
        
        Private Sub OnAgenziaBloccataAspOperationCompleted(arg As Object)
            If (Not (Me.AgenziaBloccataAspCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AgenziaBloccataAspCompleted(Me, New AgenziaBloccataAspCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/CercaAggiornamento", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CercaAggiornamento(Compagnia As Integer, Agenzia As Integer, VersioneCorrente As Integer, SubVersioneCorrente As Integer, ByRef NuovaVersione As Integer, ByRef NuovaSubVersione As Integer, ByRef NuovoTipo As String) As String
            Dim results() As Object = Me.Invoke("CercaAggiornamento", New Object() {Compagnia, Agenzia, VersioneCorrente, SubVersioneCorrente, NuovaVersione, NuovaSubVersione, NuovoTipo})
            NuovaVersione = CType(results(1),Integer)
            NuovaSubVersione = CType(results(2),Integer)
            NuovoTipo = CType(results(3),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CercaAggiornamentoAsync(Compagnia As Integer, Agenzia As Integer, VersioneCorrente As Integer, SubVersioneCorrente As Integer, NuovaVersione As Integer, NuovaSubVersione As Integer, NuovoTipo As String)
            Me.CercaAggiornamentoAsync(Compagnia, Agenzia, VersioneCorrente, SubVersioneCorrente, NuovaVersione, NuovaSubVersione, NuovoTipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CercaAggiornamentoAsync(Compagnia As Integer, Agenzia As Integer, VersioneCorrente As Integer, SubVersioneCorrente As Integer, NuovaVersione As Integer, NuovaSubVersione As Integer, NuovoTipo As String, userState As Object)
            If (Me.CercaAggiornamentoOperationCompleted Is Nothing) Then
                Me.CercaAggiornamentoOperationCompleted = AddressOf Me.OnCercaAggiornamentoOperationCompleted
            End If
            Me.InvokeAsync("CercaAggiornamento", New Object() {Compagnia, Agenzia, VersioneCorrente, SubVersioneCorrente, NuovaVersione, NuovaSubVersione, NuovoTipo}, Me.CercaAggiornamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCercaAggiornamentoOperationCompleted(arg As Object)
            If (Not (Me.CercaAggiornamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CercaAggiornamentoCompleted(Me, New CercaAggiornamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/ListinoSms", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListinoSms(Compagnia As Integer, CodiceAgenzia As Integer) As String
            Dim results() As Object = Me.Invoke("ListinoSms", New Object() {Compagnia, CodiceAgenzia})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListinoSmsAsync(Compagnia As Integer, CodiceAgenzia As Integer)
            Me.ListinoSmsAsync(Compagnia, CodiceAgenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListinoSmsAsync(Compagnia As Integer, CodiceAgenzia As Integer, userState As Object)
            If (Me.ListinoSmsOperationCompleted Is Nothing) Then
                Me.ListinoSmsOperationCompleted = AddressOf Me.OnListinoSmsOperationCompleted
            End If
            Me.InvokeAsync("ListinoSms", New Object() {Compagnia, CodiceAgenzia}, Me.ListinoSmsOperationCompleted, userState)
        End Sub
        
        Private Sub OnListinoSmsOperationCompleted(arg As Object)
            If (Not (Me.ListinoSmsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListinoSmsCompleted(Me, New ListinoSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/Province", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Province(ByRef Errore As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Province", New Object() {Errore})
            Errore = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProvinceAsync(Errore As String)
            Me.ProvinceAsync(Errore, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProvinceAsync(Errore As String, userState As Object)
            If (Me.ProvinceOperationCompleted Is Nothing) Then
                Me.ProvinceOperationCompleted = AddressOf Me.OnProvinceOperationCompleted
            End If
            Me.InvokeAsync("Province", New Object() {Errore}, Me.ProvinceOperationCompleted, userState)
        End Sub
        
        Private Sub OnProvinceOperationCompleted(arg As Object)
            If (Not (Me.ProvinceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProvinceCompleted(Me, New ProvinceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/DatiVersione", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DatiVersione(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, ByRef LogON As Boolean, ByRef Errore As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("DatiVersione", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, LogON, Errore})
            LogON = CType(results(1),Boolean)
            Errore = CType(results(2),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DatiVersioneAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, LogON As Boolean, Errore As String)
            Me.DatiVersioneAsync(Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, LogON, Errore, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DatiVersioneAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, LogON As Boolean, Errore As String, userState As Object)
            If (Me.DatiVersioneOperationCompleted Is Nothing) Then
                Me.DatiVersioneOperationCompleted = AddressOf Me.OnDatiVersioneOperationCompleted
            End If
            Me.InvokeAsync("DatiVersione", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, LogON, Errore}, Me.DatiVersioneOperationCompleted, userState)
        End Sub
        
        Private Sub OnDatiVersioneOperationCompleted(arg As Object)
            If (Not (Me.DatiVersioneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DatiVersioneCompleted(Me, New DatiVersioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/DatiVersioneLivello", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DatiVersioneLivello(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, ByRef Agenzia As DatiAgenzia, ByRef Esito As EsitoServizio) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("DatiVersioneLivello", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito})
            Agenzia = CType(results(1),DatiAgenzia)
            Esito = CType(results(2),EsitoServizio)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DatiVersioneLivelloAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, Agenzia As DatiAgenzia, Esito As EsitoServizio)
            Me.DatiVersioneLivelloAsync(Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DatiVersioneLivelloAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, Agenzia As DatiAgenzia, Esito As EsitoServizio, userState As Object)
            If (Me.DatiVersioneLivelloOperationCompleted Is Nothing) Then
                Me.DatiVersioneLivelloOperationCompleted = AddressOf Me.OnDatiVersioneLivelloOperationCompleted
            End If
            Me.InvokeAsync("DatiVersioneLivello", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito}, Me.DatiVersioneLivelloOperationCompleted, userState)
        End Sub
        
        Private Sub OnDatiVersioneLivelloOperationCompleted(arg As Object)
            If (Not (Me.DatiVersioneLivelloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DatiVersioneLivelloCompleted(Me, New DatiVersioneLivelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/VersioneLivello", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VersioneLivello(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, ByRef Agenzia As DatiAgenzia, ByRef Esito As EsitoServizio) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("VersioneLivello", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito})
            Agenzia = CType(results(1),DatiAgenzia)
            Esito = CType(results(2),EsitoServizio)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VersioneLivelloAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, Agenzia As DatiAgenzia, Esito As EsitoServizio)
            Me.VersioneLivelloAsync(Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VersioneLivelloAsync(Compagnia As Integer, CodiceAgenzia As String, VersioneCorrente As String, Ambiente As String, Agenzia As DatiAgenzia, Esito As EsitoServizio, userState As Object)
            If (Me.VersioneLivelloOperationCompleted Is Nothing) Then
                Me.VersioneLivelloOperationCompleted = AddressOf Me.OnVersioneLivelloOperationCompleted
            End If
            Me.InvokeAsync("VersioneLivello", New Object() {Compagnia, CodiceAgenzia, VersioneCorrente, Ambiente, Agenzia, Esito}, Me.VersioneLivelloOperationCompleted, userState)
        End Sub
        
        Private Sub OnVersioneLivelloOperationCompleted(arg As Object)
            If (Not (Me.VersioneLivelloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VersioneLivelloCompleted(Me, New VersioneLivelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/Assicoop2Codice", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Assicoop2Codice(Sigla As String) As String
            Dim results() As Object = Me.Invoke("Assicoop2Codice", New Object() {Sigla})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Assicoop2CodiceAsync(Sigla As String)
            Me.Assicoop2CodiceAsync(Sigla, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Assicoop2CodiceAsync(Sigla As String, userState As Object)
            If (Me.Assicoop2CodiceOperationCompleted Is Nothing) Then
                Me.Assicoop2CodiceOperationCompleted = AddressOf Me.OnAssicoop2CodiceOperationCompleted
            End If
            Me.InvokeAsync("Assicoop2Codice", New Object() {Sigla}, Me.Assicoop2CodiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnAssicoop2CodiceOperationCompleted(arg As Object)
            If (Not (Me.Assicoop2CodiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Assicoop2CodiceCompleted(Me, New Assicoop2CodiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/CodiciSub", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CodiciSub(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String) As String
            Dim results() As Object = Me.Invoke("CodiciSub", New Object() {Compagnia, CodiceAgenzia, CodiceSede})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CodiciSubAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String)
            Me.CodiciSubAsync(Compagnia, CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CodiciSubAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.CodiciSubOperationCompleted Is Nothing) Then
                Me.CodiciSubOperationCompleted = AddressOf Me.OnCodiciSubOperationCompleted
            End If
            Me.InvokeAsync("CodiciSub", New Object() {Compagnia, CodiceAgenzia, CodiceSede}, Me.CodiciSubOperationCompleted, userState)
        End Sub
        
        Private Sub OnCodiciSubOperationCompleted(arg As Object)
            If (Not (Me.CodiciSubCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CodiciSubCompleted(Me, New CodiciSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/ConfigAgenzia", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConfigAgenzia(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConfigAgenzia", New Object() {Compagnia, CodiceAgenzia, CodiceSede})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConfigAgenziaAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String)
            Me.ConfigAgenziaAsync(Compagnia, CodiceAgenzia, CodiceSede, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConfigAgenziaAsync(Compagnia As Integer, CodiceAgenzia As String, CodiceSede As String, userState As Object)
            If (Me.ConfigAgenziaOperationCompleted Is Nothing) Then
                Me.ConfigAgenziaOperationCompleted = AddressOf Me.OnConfigAgenziaOperationCompleted
            End If
            Me.InvokeAsync("ConfigAgenzia", New Object() {Compagnia, CodiceAgenzia, CodiceSede}, Me.ConfigAgenziaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConfigAgenziaOperationCompleted(arg As Object)
            If (Not (Me.ConfigAgenziaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConfigAgenziaCompleted(Me, New ConfigAgenziaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/Abilitazioni", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Abilitazioni(Compagnia As Integer, Agenzia As String) As String
            Dim results() As Object = Me.Invoke("Abilitazioni", New Object() {Compagnia, Agenzia})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AbilitazioniAsync(Compagnia As Integer, Agenzia As String)
            Me.AbilitazioniAsync(Compagnia, Agenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AbilitazioniAsync(Compagnia As Integer, Agenzia As String, userState As Object)
            If (Me.AbilitazioniOperationCompleted Is Nothing) Then
                Me.AbilitazioniOperationCompleted = AddressOf Me.OnAbilitazioniOperationCompleted
            End If
            Me.InvokeAsync("Abilitazioni", New Object() {Compagnia, Agenzia}, Me.AbilitazioniOperationCompleted, userState)
        End Sub
        
        Private Sub OnAbilitazioniOperationCompleted(arg As Object)
            If (Not (Me.AbilitazioniCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AbilitazioniCompleted(Me, New AbilitazioniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/InviaProdotti", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InviaProdotti(Compagnia As Integer, Agenzia As String, dsStatistiche As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("InviaProdotti", New Object() {Compagnia, Agenzia, dsStatistiche})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InviaProdottiAsync(Compagnia As Integer, Agenzia As String, dsStatistiche As System.Data.DataSet)
            Me.InviaProdottiAsync(Compagnia, Agenzia, dsStatistiche, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InviaProdottiAsync(Compagnia As Integer, Agenzia As String, dsStatistiche As System.Data.DataSet, userState As Object)
            If (Me.InviaProdottiOperationCompleted Is Nothing) Then
                Me.InviaProdottiOperationCompleted = AddressOf Me.OnInviaProdottiOperationCompleted
            End If
            Me.InvokeAsync("InviaProdotti", New Object() {Compagnia, Agenzia, dsStatistiche}, Me.InviaProdottiOperationCompleted, userState)
        End Sub
        
        Private Sub OnInviaProdottiOperationCompleted(arg As Object)
            If (Not (Me.InviaProdottiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InviaProdottiCompleted(Me, New InviaProdottiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/InviaDatiSinistri", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InviaDatiSinistri(Agenzia As String, dsStatistiche As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("InviaDatiSinistri", New Object() {Agenzia, dsStatistiche})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InviaDatiSinistriAsync(Agenzia As String, dsStatistiche As System.Data.DataSet)
            Me.InviaDatiSinistriAsync(Agenzia, dsStatistiche, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InviaDatiSinistriAsync(Agenzia As String, dsStatistiche As System.Data.DataSet, userState As Object)
            If (Me.InviaDatiSinistriOperationCompleted Is Nothing) Then
                Me.InviaDatiSinistriOperationCompleted = AddressOf Me.OnInviaDatiSinistriOperationCompleted
            End If
            Me.InvokeAsync("InviaDatiSinistri", New Object() {Agenzia, dsStatistiche}, Me.InviaDatiSinistriOperationCompleted, userState)
        End Sub
        
        Private Sub OnInviaDatiSinistriOperationCompleted(arg As Object)
            If (Not (Me.InviaDatiSinistriCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InviaDatiSinistriCompleted(Me, New InviaDatiSinistriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/InvioProdottiEffettuato", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InvioProdottiEffettuato(Compagnia As Integer, Agenzia As Integer) As Boolean
            Dim results() As Object = Me.Invoke("InvioProdottiEffettuato", New Object() {Compagnia, Agenzia})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InvioProdottiEffettuatoAsync(Compagnia As Integer, Agenzia As Integer)
            Me.InvioProdottiEffettuatoAsync(Compagnia, Agenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InvioProdottiEffettuatoAsync(Compagnia As Integer, Agenzia As Integer, userState As Object)
            If (Me.InvioProdottiEffettuatoOperationCompleted Is Nothing) Then
                Me.InvioProdottiEffettuatoOperationCompleted = AddressOf Me.OnInvioProdottiEffettuatoOperationCompleted
            End If
            Me.InvokeAsync("InvioProdottiEffettuato", New Object() {Compagnia, Agenzia}, Me.InvioProdottiEffettuatoOperationCompleted, userState)
        End Sub
        
        Private Sub OnInvioProdottiEffettuatoOperationCompleted(arg As Object)
            If (Not (Me.InvioProdottiEffettuatoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InvioProdottiEffettuatoCompleted(Me, New InvioProdottiEffettuatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/InvioDatiSinistri", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InvioDatiSinistri(Agenzia As Integer) As Boolean
            Dim results() As Object = Me.Invoke("InvioDatiSinistri", New Object() {Agenzia})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InvioDatiSinistriAsync(Agenzia As Integer)
            Me.InvioDatiSinistriAsync(Agenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InvioDatiSinistriAsync(Agenzia As Integer, userState As Object)
            If (Me.InvioDatiSinistriOperationCompleted Is Nothing) Then
                Me.InvioDatiSinistriOperationCompleted = AddressOf Me.OnInvioDatiSinistriOperationCompleted
            End If
            Me.InvokeAsync("InvioDatiSinistri", New Object() {Agenzia}, Me.InvioDatiSinistriOperationCompleted, userState)
        End Sub
        
        Private Sub OnInvioDatiSinistriOperationCompleted(arg As Object)
            If (Not (Me.InvioDatiSinistriCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InvioDatiSinistriCompleted(Me, New InvioDatiSinistriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/RegistraLogUso", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistraLogUso(DatiLog As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("RegistraLogUso", New Object() {DatiLog})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraLogUsoAsync(DatiLog As System.Data.DataSet)
            Me.RegistraLogUsoAsync(DatiLog, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraLogUsoAsync(DatiLog As System.Data.DataSet, userState As Object)
            If (Me.RegistraLogUsoOperationCompleted Is Nothing) Then
                Me.RegistraLogUsoOperationCompleted = AddressOf Me.OnRegistraLogUsoOperationCompleted
            End If
            Me.InvokeAsync("RegistraLogUso", New Object() {DatiLog}, Me.RegistraLogUsoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraLogUsoOperationCompleted(arg As Object)
            If (Not (Me.RegistraLogUsoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraLogUsoCompleted(Me, New RegistraLogUsoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.utools.it/asp/SettingAgenzia/Referenti", RequestNamespace:="http://www.utools.it/asp/SettingAgenzia", ResponseNamespace:="http://www.utools.it/asp/SettingAgenzia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Referenti(Agenzia As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Referenti", New Object() {Agenzia})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReferentiAsync(Agenzia As Integer)
            Me.ReferentiAsync(Agenzia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReferentiAsync(Agenzia As Integer, userState As Object)
            If (Me.ReferentiOperationCompleted Is Nothing) Then
                Me.ReferentiOperationCompleted = AddressOf Me.OnReferentiOperationCompleted
            End If
            Me.InvokeAsync("Referenti", New Object() {Agenzia}, Me.ReferentiOperationCompleted, userState)
        End Sub
        
        Private Sub OnReferentiOperationCompleted(arg As Object)
            If (Not (Me.ReferentiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReferentiCompleted(Me, New ReferentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.utools.it/asp/SettingAgenzia")>  _
    Partial Public Class DatiAgenzia
        
        Private livelloField As String
        
        '''<remarks/>
        Public Property Livello() As String
            Get
                Return Me.livelloField
            End Get
            Set
                Me.livelloField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.utools.it/asp/SettingAgenzia")>  _
    Partial Public Class EsitoServizio
        
        Private esitoChiamataField As Boolean
        
        Private messaggioField As String
        
        Private codiceErroreField As String
        
        Private messaggioErroreField As String
        
        Private valoreRestituiroField As Object
        
        '''<remarks/>
        Public Property EsitoChiamata() As Boolean
            Get
                Return Me.esitoChiamataField
            End Get
            Set
                Me.esitoChiamataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Messaggio() As String
            Get
                Return Me.messaggioField
            End Get
            Set
                Me.messaggioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodiceErrore() As String
            Get
                Return Me.codiceErroreField
            End Get
            Set
                Me.codiceErroreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessaggioErrore() As String
            Get
                Return Me.messaggioErroreField
            End Get
            Set
                Me.messaggioErroreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValoreRestituiro() As Object
            Get
                Return Me.valoreRestituiroField
            End Get
            Set
                Me.valoreRestituiroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CodiciDownloadExCompletedEventHandler(sender As Object, e As CodiciDownloadExCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CodiciDownloadExCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ConsensoImportazione() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Errore() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ErroreForzature() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ErroreListe() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AbilitazioniSedeStringaCompletedEventHandler(sender As Object, e As AbilitazioniSedeStringaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AbilitazioniSedeStringaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ForzatureDLCompletedEventHandler(sender As Object, e As ForzatureDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ForzatureDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AgenzieCollegateCompletedEventHandler(sender As Object, e As AgenzieCollegateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AgenzieCollegateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub TabellaAgenzieCollegateCompletedEventHandler(sender As Object, e As TabellaAgenzieCollegateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TabellaAgenzieCollegateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AgenziaBloccataCompletedEventHandler(sender As Object, e As AgenziaBloccataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AgenziaBloccataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Prod() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Test() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Lab() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Gruppo() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Errore() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub TipologiaAgenziaCompletedEventHandler(sender As Object, e As TipologiaAgenziaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TipologiaAgenziaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Prod() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Test() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Lab() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Gruppo() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AgenziaBloccataAspCompletedEventHandler(sender As Object, e As AgenziaBloccataAspCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AgenziaBloccataAspCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CercaAggiornamentoCompletedEventHandler(sender As Object, e As CercaAggiornamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CercaAggiornamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property NuovaVersione() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property NuovaSubVersione() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property NuovoTipo() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ListinoSmsCompletedEventHandler(sender As Object, e As ListinoSmsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListinoSmsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ProvinceCompletedEventHandler(sender As Object, e As ProvinceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProvinceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Errore() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DatiVersioneCompletedEventHandler(sender As Object, e As DatiVersioneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DatiVersioneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property LogON() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Errore() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DatiVersioneLivelloCompletedEventHandler(sender As Object, e As DatiVersioneLivelloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DatiVersioneLivelloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Agenzia() As DatiAgenzia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),DatiAgenzia)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Esito() As EsitoServizio
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),EsitoServizio)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub VersioneLivelloCompletedEventHandler(sender As Object, e As VersioneLivelloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VersioneLivelloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Agenzia() As DatiAgenzia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),DatiAgenzia)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Esito() As EsitoServizio
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),EsitoServizio)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Assicoop2CodiceCompletedEventHandler(sender As Object, e As Assicoop2CodiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Assicoop2CodiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CodiciSubCompletedEventHandler(sender As Object, e As CodiciSubCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CodiciSubCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConfigAgenziaCompletedEventHandler(sender As Object, e As ConfigAgenziaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConfigAgenziaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AbilitazioniCompletedEventHandler(sender As Object, e As AbilitazioniCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AbilitazioniCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InviaProdottiCompletedEventHandler(sender As Object, e As InviaProdottiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InviaProdottiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InviaDatiSinistriCompletedEventHandler(sender As Object, e As InviaDatiSinistriCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InviaDatiSinistriCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InvioProdottiEffettuatoCompletedEventHandler(sender As Object, e As InvioProdottiEffettuatoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InvioProdottiEffettuatoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub InvioDatiSinistriCompletedEventHandler(sender As Object, e As InvioDatiSinistriCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InvioDatiSinistriCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RegistraLogUsoCompletedEventHandler(sender As Object, e As RegistraLogUsoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraLogUsoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReferentiCompletedEventHandler(sender As Object, e As ReferentiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReferentiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
