'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SettingFlag
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SettingFlagSoap", [Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class SettingFlag
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreaFlagOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EliminaFlagOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EsisteFlagOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InizializzaInteropOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValoreChiaveInteropOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SalvaChiaveInteropOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnumerazioniOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_SettingFlag_SettingFlag
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreaFlagCompleted As CreaFlagCompletedEventHandler
        
        '''<remarks/>
        Public Event EliminaFlagCompleted As EliminaFlagCompletedEventHandler
        
        '''<remarks/>
        Public Event EsisteFlagCompleted As EsisteFlagCompletedEventHandler
        
        '''<remarks/>
        Public Event InizializzaInteropCompleted As InizializzaInteropCompletedEventHandler
        
        '''<remarks/>
        Public Event ValoreChiaveInteropCompleted As ValoreChiaveInteropCompletedEventHandler
        
        '''<remarks/>
        Public Event SalvaChiaveInteropCompleted As SalvaChiaveInteropCompletedEventHandler
        
        '''<remarks/>
        Public Event EnumerazioniCompleted As EnumerazioniCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/CreaFlag", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreaFlag(ByVal CodiceAgenzia As String, ByVal Utente As String, ByVal Tipo As String, ByVal Descrizone As String, ByVal Token As String)
            Me.Invoke("CreaFlag", New Object() {CodiceAgenzia, Utente, Tipo, Descrizone, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreaFlagAsync(ByVal CodiceAgenzia As String, ByVal Utente As String, ByVal Tipo As String, ByVal Descrizone As String, ByVal Token As String)
            Me.CreaFlagAsync(CodiceAgenzia, Utente, Tipo, Descrizone, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreaFlagAsync(ByVal CodiceAgenzia As String, ByVal Utente As String, ByVal Tipo As String, ByVal Descrizone As String, ByVal Token As String, ByVal userState As Object)
            If (Me.CreaFlagOperationCompleted Is Nothing) Then
                Me.CreaFlagOperationCompleted = AddressOf Me.OnCreaFlagOperationCompleted
            End If
            Me.InvokeAsync("CreaFlag", New Object() {CodiceAgenzia, Utente, Tipo, Descrizone, Token}, Me.CreaFlagOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreaFlagOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreaFlagCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreaFlagCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/EliminaFlag", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EliminaFlag(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String)
            Me.Invoke("EliminaFlag", New Object() {CodiceAgenzia, Tipo, Token})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminaFlagAsync(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String)
            Me.EliminaFlagAsync(CodiceAgenzia, Tipo, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminaFlagAsync(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String, ByVal userState As Object)
            If (Me.EliminaFlagOperationCompleted Is Nothing) Then
                Me.EliminaFlagOperationCompleted = AddressOf Me.OnEliminaFlagOperationCompleted
            End If
            Me.InvokeAsync("EliminaFlag", New Object() {CodiceAgenzia, Tipo, Token}, Me.EliminaFlagOperationCompleted, userState)
        End Sub
        
        Private Sub OnEliminaFlagOperationCompleted(ByVal arg As Object)
            If (Not (Me.EliminaFlagCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EliminaFlagCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/EsisteFlag", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EsisteFlag(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String) As Dati
            Dim results() As Object = Me.Invoke("EsisteFlag", New Object() {CodiceAgenzia, Tipo, Token})
            Return CType(results(0),Dati)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EsisteFlagAsync(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String)
            Me.EsisteFlagAsync(CodiceAgenzia, Tipo, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EsisteFlagAsync(ByVal CodiceAgenzia As String, ByVal Tipo As String, ByVal Token As String, ByVal userState As Object)
            If (Me.EsisteFlagOperationCompleted Is Nothing) Then
                Me.EsisteFlagOperationCompleted = AddressOf Me.OnEsisteFlagOperationCompleted
            End If
            Me.InvokeAsync("EsisteFlag", New Object() {CodiceAgenzia, Tipo, Token}, Me.EsisteFlagOperationCompleted, userState)
        End Sub
        
        Private Sub OnEsisteFlagOperationCompleted(ByVal arg As Object)
            If (Not (Me.EsisteFlagCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EsisteFlagCompleted(Me, New EsisteFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/InizializzaInterop", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InizializzaInterop(ByVal CodiceAgenzia As String, ByVal Token As String) As Boolean
            Dim results() As Object = Me.Invoke("InizializzaInterop", New Object() {CodiceAgenzia, Token})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InizializzaInteropAsync(ByVal CodiceAgenzia As String, ByVal Token As String)
            Me.InizializzaInteropAsync(CodiceAgenzia, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InizializzaInteropAsync(ByVal CodiceAgenzia As String, ByVal Token As String, ByVal userState As Object)
            If (Me.InizializzaInteropOperationCompleted Is Nothing) Then
                Me.InizializzaInteropOperationCompleted = AddressOf Me.OnInizializzaInteropOperationCompleted
            End If
            Me.InvokeAsync("InizializzaInterop", New Object() {CodiceAgenzia, Token}, Me.InizializzaInteropOperationCompleted, userState)
        End Sub
        
        Private Sub OnInizializzaInteropOperationCompleted(ByVal arg As Object)
            If (Not (Me.InizializzaInteropCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InizializzaInteropCompleted(Me, New InizializzaInteropCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/ValoreChiaveInterop", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValoreChiaveInterop(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Token As String) As String
            Dim results() As Object = Me.Invoke("ValoreChiaveInterop", New Object() {CodiceAgenzia, Chiave, Token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValoreChiaveInteropAsync(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Token As String)
            Me.ValoreChiaveInteropAsync(CodiceAgenzia, Chiave, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValoreChiaveInteropAsync(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Token As String, ByVal userState As Object)
            If (Me.ValoreChiaveInteropOperationCompleted Is Nothing) Then
                Me.ValoreChiaveInteropOperationCompleted = AddressOf Me.OnValoreChiaveInteropOperationCompleted
            End If
            Me.InvokeAsync("ValoreChiaveInterop", New Object() {CodiceAgenzia, Chiave, Token}, Me.ValoreChiaveInteropOperationCompleted, userState)
        End Sub
        
        Private Sub OnValoreChiaveInteropOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValoreChiaveInteropCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValoreChiaveInteropCompleted(Me, New ValoreChiaveInteropCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/SalvaChiaveInterop", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SalvaChiaveInterop(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Valore As String, ByVal Token As String) As Boolean
            Dim results() As Object = Me.Invoke("SalvaChiaveInterop", New Object() {CodiceAgenzia, Chiave, Valore, Token})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SalvaChiaveInteropAsync(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Valore As String, ByVal Token As String)
            Me.SalvaChiaveInteropAsync(CodiceAgenzia, Chiave, Valore, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SalvaChiaveInteropAsync(ByVal CodiceAgenzia As String, ByVal Chiave As String, ByVal Valore As String, ByVal Token As String, ByVal userState As Object)
            If (Me.SalvaChiaveInteropOperationCompleted Is Nothing) Then
                Me.SalvaChiaveInteropOperationCompleted = AddressOf Me.OnSalvaChiaveInteropOperationCompleted
            End If
            Me.InvokeAsync("SalvaChiaveInterop", New Object() {CodiceAgenzia, Chiave, Valore, Token}, Me.SalvaChiaveInteropOperationCompleted, userState)
        End Sub
        
        Private Sub OnSalvaChiaveInteropOperationCompleted(ByVal arg As Object)
            If (Not (Me.SalvaChiaveInteropCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SalvaChiaveInteropCompleted(Me, New SalvaChiaveInteropCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/Enumerazioni", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Enumerazioni(ByVal Tipo As TipoFlag, ByVal Chiave As ChiaviInterop)
            Me.Invoke("Enumerazioni", New Object() {Tipo, Chiave})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnumerazioniAsync(ByVal Tipo As TipoFlag, ByVal Chiave As ChiaviInterop)
            Me.EnumerazioniAsync(Tipo, Chiave, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnumerazioniAsync(ByVal Tipo As TipoFlag, ByVal Chiave As ChiaviInterop, ByVal userState As Object)
            If (Me.EnumerazioniOperationCompleted Is Nothing) Then
                Me.EnumerazioniOperationCompleted = AddressOf Me.OnEnumerazioniOperationCompleted
            End If
            Me.InvokeAsync("Enumerazioni", New Object() {Tipo, Chiave}, Me.EnumerazioniOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnumerazioniOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnumerazioniCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnumerazioniCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class Dati
        
        Private esisteField As Boolean
        
        Private utenteField As String
        
        Private creazioneField As Date
        
        Private descrizioneField As String
        
        '''<remarks/>
        Public Property Esiste() As Boolean
            Get
                Return Me.esisteField
            End Get
            Set
                Me.esisteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Utente() As String
            Get
                Return Me.utenteField
            End Get
            Set
                Me.utenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Creazione() As Date
            Get
                Return Me.creazioneField
            End Get
            Set
                Me.creazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://utools.auaonline.it/")>  _
    Public Enum TipoFlag
        
        '''<remarks/>
        IMPORTAZIONE_MA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://utools.auaonline.it/")>  _
    Public Enum ChiaviInterop
        
        '''<remarks/>
        AUTO_IMPORT_MA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub CreaFlagCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub EliminaFlagCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub EsisteFlagCompletedEventHandler(ByVal sender As Object, ByVal e As EsisteFlagCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EsisteFlagCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Dati
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Dati)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub InizializzaInteropCompletedEventHandler(ByVal sender As Object, ByVal e As InizializzaInteropCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InizializzaInteropCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub ValoreChiaveInteropCompletedEventHandler(ByVal sender As Object, ByVal e As ValoreChiaveInteropCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValoreChiaveInteropCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub SalvaChiaveInteropCompletedEventHandler(ByVal sender As Object, ByVal e As SalvaChiaveInteropCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SalvaChiaveInteropCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub EnumerazioniCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
