DROP TABLE Titoli;

CREATE TABLE Titoli
(
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         CHAR(3),
    Polizza                                      CHAR(9),
    EffettoAppendice                             DATE,
    NumeroAppendice                              CHAR(3),
    DataEffetto                                  DATE,
    TipoCarico                                   CHAR(1),
    DataScadenza                                 DATE,
    DataEmissione                                DATE,
    DataFoglioCassa                              DATE,
    DataStorno                                   DATE,
    CodiceEsito                                  CHAR(2),
    TerminaleCassa                               CHAR(4),
    CodiceTerminale                              CHAR(4),
    PremioNetto                                  CURRENCY,
    Interessi                                    CURRENCY,
    Accessori                                    CURRENCY,
    TotaleLordo                                  CURRENCY,
    Abbuono                                      CURRENCY,
    ProvvigioneAcquisto                          CURRENCY,
    ProvvigioneAcquistoRic                       CURRENCY,
    ProvvigioneIncasso                           CURRENCY,
    ImpostaSSN                                   CURRENCY,
    Valuta                                       CHAR(3),
    TipoMatricola                                CHAR(1),
    CodiceUltimaTransazione                      CHAR(4),
    TipoQuietanza                                CHAR(1),
    DataSistema                                  DATE,
    CodiceCaricoProvvigionale                    CHAR(1),
    CodiceTipoPagamento                          CHAR(1),
    DataEffetivoPagamento                        DATE,
    FlagEmessoPregresso                          CHAR(1),
    DataEffettoMovimento                         DATE,
    CodiceSubagente                              CHAR(5),
    CodiceProduttore                             CHAR(5),
    CodiceConvenzioneProvvigionata               CHAR(5),
    CodiceConvenzione                            CHAR(5),
    DataTrasferimentoTitolo                      DATE,
    FlagTipoRamo                                 CHAR(1),
    FlagTitoloEsente                             CHAR(1),
    CodiceCombinazioneAurFF                      CHAR(1),
    ImportoAurobox                               CURRENCY,
    CodiceFiscale                                CHAR(16),
    Contraente                                   CHAR(25),
    Frazionamento                                CHAR(1),
    CodiceProdotto                               CHAR(5),
    TipoMatricolaVita                            CHAR(4),
    DataEffettoPolizza                           DATE,
    CompagniaDelegataria                         CHAR(3),
    QuotaCoass                                   CURRENCY,
    NumeroTesta                                  VARCHAR(9),
    FlagRID                                      CHAR(1),
    FlagIncassoDirezione                         CHAR(1),
    AliquotaProvvigionaleIncasso                 CURRENCY,
    AliquotaProvvigionaleAcquisto                CURRENCY,
    PremioTutela                                 CURRENCY,
    PremioAssistenza                             CURRENCY,
    ImportoCAV                                   CURRENCY
);

CREATE TABLE TitoliRipartizione
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         CHAR(3),
    Polizza                                      CHAR(9),
    EffettoAppendice                             DATE,
    NumeroAppendice                              CHAR(3),
    DataEffetto                                  DATE,
    CodiceCategoriaRischio                       CHAR(5),
    CodiceTassazione                             CHAR(4),
    PremioNetto                                  CURRENCY,
    Interessi                                    CURRENCY,
    Accessori                                    CURRENCY,
    Tasse                                        CURRENCY,
    AliquotaTasse                                CURRENCY,
    Tassabile                                    CURRENCY,
    Provvigioni                                  CURRENCY
);

CREATE TABLE TitoliScopertiCassa
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         CHAR(3),
    Polizza                                      CHAR(9),
    EffettoAppendice                             DATE,
    NumeroAppendice                              CHAR(3),
    DataEffetto                                  DATE,
    TipoCarico                                   CHAR(1),
    DataSistema                                  DATE,
    TimeSistema                                  VARCHAR(6),
    CodiceEsito                                  CHAR(2),
    DataEsito                                    DATE,
    Abbuono                                      CURRENCY,
    TerminaleCassa                               VARCHAR(4),
    CodiceUltimaTransazione                      CHAR(4),
    CodiceTerminale                              CHAR(4),
    ProvvigioniAcquisto                          CURRENCY,
    ProvvigioniIncasso                           CURRENCY,
    TariffaTassazione                            VARCHAR(4),
    AliquotaTasse                                CURRENCY,
    CodiceProdotto                               CHAR(5),
    CodiceConvenzione                            CHAR(5),
    Frazionamento                                CHAR(1),
    CompagniaDelegataria                         CHAR(3),
    AgenziaDelegataria                           CHAR(5),
    QuotaCoass                                   CURRENCY,
    FlagCaricoProvvigionale                      CHAR(1),
    CodiceSubagente                              CHAR(5),
    CodiceProduttore                             CHAR(5),
    CodiceConvenzioneProvvigionata               CHAR(5),
    CodiceValuta                                 CHAR(3),
    Contraente                                   VARCHAR(25),
    CodiceFiscale                                CHAR(16),
    CodiceTipoPagamento                          CHAR(1),
    PremioImponibile                             CURRENCY,
    ImportoSSN                                   CURRENCY,
    FlagTipoRamo                                 CHAR(1),
    FlagTitoloEsente                             CHAR(1),
    PremioLordo                                  CURRENCY
);

CREATE TABLE TitoliCancellati
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         CHAR(3),
    Polizza                                      CHAR(9),
    EffettoAppendice                             DATE,
    NumeroAppendice                              CHAR(3),
    DataEffetto                                  DATE,
    TipoCarico                                   CHAR(1),
    ScadenzaTitolo                               DATE,
    EmissioneTitolo                              DATE,
    DatatimeMovimento                            VARCHAR(26),
    PremioNetto                                  CURRENCY,
    InteressiFrazionamento                       CURRENCY,
    Accessori                                    CURRENCY,
    TotaleTitolo                                 CURRENCY,
    ProvvigioniAcquistoContante                  CURRENCY,
    ProvvigioniSuccessive                        CURRENCY,
    ProvvigioniIncasso                           CURRENCY,
    ImportoSSN                                   CURRENCY,
    Valuta                                       CHAR(3),
    TipoMatricola                                CHAR(1),
    FlagTipoQuietanza                            CHAR(1),
    DataSistema                                  DATE,
    FlagEmessoPregresso                          CHAR(1),
    DataeffettoMovimento                         DATE,
    CodiceSubagente                              CHAR(5),
    CodiceProduttore                             CHAR(5),
    CodiceConvenzione                            CHAR(5),
    FlagTipoRamo                                 CHAR(1),
    FlagTitoloEsente                             CHAR(1)
);

CREATE TABLE TitoliScopertiNonCassa
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    DataRegMovimento                             DATE,
    ImportoMovimento                             CURRENCY,
    CodiceSegno                                  CHAR(1),
    CodiceMovimento                              CHAR(3),
    CodiceTipoMovimento                          CHAR(3),
    FlagOperazione                               CHAR(1),
    DataModifica                                 DATE,
    Descrizione                                  CHAR(40),
    DataRegistrazioneDecade                      DATE,
    ProgressivoElaborazione                      CHAR(9)
);



CREATE TABLE MovimentiPrimaNota 
(
	[ProgressivoFile]               INTEGER,
	[DataElaborazione]              DATE,
	[CodicePuntoVendita]            CHAR(5),
	[Progressivo]                   CHAR(2),
	[TipoElaborazione]              CHAR(2),
	[CodiceMovimento]	            CHAR(3),
	[CodiceTipoMovimento]	        CHAR(3),
	[Descrizione]		            VARCHAR(40),
	[Categoria]		                INTEGER,
	[Ramo]			                SMALLINT,
	[Polizza]		                INTEGER,
	[DataEffettoTitolo]	            DATE,
	[Contraente]		            VARCHAR(25),
	[CodiceSegno]		            CHAR(1),
	[ImportoCassa]		            CURRENCY,
	[ImportoBanca]		            CURRENCY,
	[CodiceBanca]		            CHAR(05),
	[ProgressivoBonifico]	        INTEGER,
	[ImportoAltro]		            CURRENCY,
	[CodicePagamento]	            CHAR(01),
	[CodiceSubagente]	            CHAR(05),
	[CodiceConvenzione]	            CHAR(05),
	[DataRegistrazione]	            DATE,
	[TimestampInserimento]	        CHAR(26),
	[MovimentoConfermato]	        CHAR(01),
	[DataQuadratura]	            DATE,
	[PuntoVendita]	                CHAR(05),
	[CodiceEsito]		            CHAR(2),
	PRIMARY KEY(TimestampInserimento)
);


