DROP TABLE Polizze1;

CREATE TABLE Polizze1
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    CodiceSubagenzia                             SMALLINT,
    CodiceProduttore                             SMALLINT,
    CodiceProdotto                               CHAR(5),
    TipoPolizza                                  CHAR(5),
    Frazionamento                                CHAR(1),
    CodicePagamento                              SMALLINT,
    CodiceCampagna                               CHAR(10),
    CodiceConvenzione                            INTEGER,
    CodiceDerogaCondStamp                        CHAR(1),
    DataEffettoPolizza                           DATE,
    DataScadenzaPolizza                          DATE,
    DataProssimaQuietanza                        DATE,                                     
    DataEmissione                                DATE,
    DataRegolazionePremio                        DATE,
    DataScadenzaVincolo                          DATE,
    DataScadenzaOriginaria                       DATE,
    CodiceTipoStorno                             CHAR(2),
    DataEffettoStorno                            DATE,
    DataEmissioneStorno                          DATE,
    FlagSospesa                                  CHAR(2),
    DataEffettoSospesa                           DATE,
    NuovoCodiceRamo                              CHAR(3),
    NuovoNumeroPolizza                           VARCHAR(9),
    CodiceFiscale                                CHAR(16),
    Nominativo                                   VARCHAR(67),
    Cap                                          CHAR(5),
    CodiceValuta                                 CHAR(3),
    FlagTipoRamo                                 CHAR(1),
    PremioNetto                                  CURRENCY,
    Interessi                                    CURRENCY,
    Accessori                                    CURRENCY,
    PremioTassabile                              CURRENCY,
    NostraQuotaPremioTassabile                   CURRENCY,
    PremioLordo                                  CURRENCY,
    AliquotaInteressi                            CURRENCY,
    AliquotaAccessori                            CURRENCY,
    FlagDelega                                   CHAR(1),
    PercentualeQuotaNostra                       CURRENCY,
    CompagniaDelegata                            CHAR(3),
    AgenziaDelegata                              CHAR(5),
    PolizzaDelegata                              VARCHAR(18),
    CodiceTipoTarga                              CHAR(1),
    TargaVeicolo                                 VARCHAR(20),
    ClasseVeicolo                                CHAR(3),
    UsoVeicolo                                   CHAR(2),
    SettoreTariffa                               CHAR(1),
    DataEdizioneRca                              DATE,
    PotenzaEffettiva                             CHAR(3),
    RapportoPesoPotenza                          CHAR(6),
    UtilizzoAuto                                 CHAR(1),
    TipoAlimentazione                            CHAR(1),
    HpVeicolo                                    SMALLINT,
    PostiVeicolo                                 CHAR(3),
    QuintaliVeicolo                              CHAR(3),
    PostiRimorchio                               CHAR(3),
    QuintaliRimorchio                            CHAR(3),
    Kilowatt                                     CHAR(5),
    PesoKg                                       CHAR(5),
    Rimorchio                                    CHAR(1),
    Garage                                       CHAR(1),
    Antifurto                                    CHAR(1),
    ABS                                          CHAR(1),
    AirbagPasseggero                             CHAR(1),
    CodiceMarcaVeicolo                           CHAR(3),
    CodiceAllestimento                           CHAR(7),
    AnnoMesePresentazione                        CHAR(6),
    AnnoMeseImmatricolazione                     CHAR(6),
    ProprietarioContraente                       CHAR(1),
    ProprietarioCodiceFiscale                    CHAR(16),
    ProprietarioCodiceCatastale                  CHAR(4),
    ProprietarioProfessione                      SMALLINT,
    ProprietarioAnnoMese                         VARCHAR(6),
    ProprietarioSesso                            CHAR(1),
    ConducenteContraente                         CHAR(1),
    ConducenteAnnoMese                           VARCHAR(6),
    ConducenteSesso                              CHAR(1),
    ConducenteAnnoMesePatente                    VARCHAR(6),
    TipoTariffa                                  CHAR(1),
    ClasseMerito                                 SMALLINT,
    AnnoMeseTariffa                              VARCHAR(6),
    FormaTariffa                                 CHAR(1),
    RcaPejus                                     CHAR(1),
    Franchigia                                   CURRENCY,
    ScontoBonus                                  CURRENCY,
    BonusFamiglia                                CHAR(1),
    CombinazioniMassimali                        SMALLINT,
    ProvinciaTariffa                             CHAR(2),
    ClasseTariffaCip                             CHAR(3),
    FlagFlessibilita                             CHAR(1),
    PercentualeFlessibilita                      CURRENCY,
    PremioRcaNetto                               VARCHAR(15),
    
    GarcomPremioRcaPar                           VARCHAR(13),
    GarcomPremioRco                              VARCHAR(13),
    TariffaARD                                   CHAR(5),
    IncendioCodiceGaranzia                       CHAR(3),
    IncendioCapitale                             CURRENCY,
    IncendioFranchigia                           CURRENCY,
    IncendioPercentualeFranchigia                CURRENCY,
    IncendioPercentualeScoperto                  CURRENCY,
    IncendioPremio                               CURRENCY,
    FurtoCodiceGaranzia                          CHAR(3),
    FurtoCapitale                                CURRENCY,
    FurtoFranchigia                              CURRENCY,
    FurtoPercentualeFranchigia                   CURRENCY,
    FurtoPercentualeScoperto                     CURRENCY,
    FurtoPremio                                  CURRENCY,
    EventiAtmosfericiCodiceGaranzia              CHAR(3),
    EventiAtmosfericiCapitale                    CURRENCY,
    EventiAtmosfericiFranchigia                  CURRENCY,
    EventiAtmosfericiPercentualeFranchigia       CURRENCY,
    EventiAtmosfericiPercentualeScoperto         CURRENCY,
    EventiAtmosfericiPremio                      CURRENCY,
    EventiSocioPoliticiCodiceGaranzia            CHAR(3),
    EventiSocioPoliticiCapitale                  CURRENCY,
    EventiSocioPoliticiFranchigia                CURRENCY,
    EventiSocioPoliticiPercentualeFranchigia     CURRENCY,
    EventiSocioPoliticiPercentualeScoperto       CURRENCY,
    EventiSocioPoliticiPremio                    CURRENCY,
    FonoAudiovisiviPresenza                      CHAR(1),
    FonoAudiovisiviCapitale                      CURRENCY
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

DROP TABLE Polizze2;

CREATE TABLE Polizze2
(
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    FonoAudiovisiviFranchigia                    CURRENCY,
    FonoAudiovisiviPremio                        CURRENCY,
    FonoAudiovisiviAnnoAcquisto                  CHAR(4),
    InfortuniCombinazione                        SMALLINT,
    InfortuniPercentualeFranchigiaIP             CURRENCY,
    InfortuniPremio                              CURRENCY,
    RitiroPatenteCodiceGaranzia                  CHAR(3),
    RitiroPatenteGiorni                          CHAR(3),
    RitiroPatenteFranchigiaGiorni                CHAR(3),
    RitiroPatenteDiaria                          CURRENCY,
    RitiroPatentePremio                          CURRENCY,
    GaranzieAccessorieCombinazione               SMALLINT,
    GaranzieAccessoriePremioTutela               CURRENCY,
    GaranzieAccessoriePremioAssistenza           CURRENCY,
    GaranzieAccessoriePremio                     CURRENCY,
    KaskoCodiceGaranzia                          CHAR(3),
    KaskoCapitale                                CURRENCY,
    KaskoFranchigia                              CURRENCY,
    KaskoPercentualeFranchigia                   CURRENCY,
    KaskoPercentualeScoperto                     CURRENCY,
    KaskoPremio                                  CURRENCY,
    KaskoCodiceTariffa                           CHAR(5),
    KaskoCodiceAccessori                         CHAR(1),
    FermoTecnicoCodiceGaranzia                   CHAR(3),
    FermoTecnicoDiaria                           CURRENCY,
    FermoTecnicoGiorni                           CHAR(3),
    FermoTecnicoFranchigiaGiorni                 CHAR(3),
    FermoTecnicoPremio                           CURRENCY,
    CaricoScaricoMassimali                       CHAR(3),
    CaricoScaricoFranchigia                      CURRENCY,
    CaricoScaricoPremio                          CURRENCY,
    GruppoSinistrosita                           CHAR(1),
    MarcaVeicolo                                 VARCHAR(14),
    ProdottoRiferimento                          CHAR(5),
    NumemoVariazione                             CHAR(3),
    DataVariazione                               DATE,
    FlagRegolazionePremio                        CHAR(1),
    EsercizioCompetenza                          CHAR(4),
    TipoIndice                                   CHAR(1),
    NumeroIndice                                 VARCHAR(7),
    TacitoRinnovo                                CHAR(1),
    Rescindibilita                               CHAR(1),
    ProvinciaRischio                             CHAR(3),
    FlagNote                                     CHAR(1),
    FlagCumulativa                               CHAR(1),
    FormaProvvigionale                           CHAR(1),
    CodiceTariffaVita                            CHAR(4),
    TotaleVersamentiAnnui                        CURRENCY,
    ControlloElettronicoVelocita                 CHAR(1),
    ControlloElettronicoStabilita                CHAR(1),
    CCNatanti                                    CHAR(5),
    ScalaBonusMaius                              CHAR(1),
    TipoBlocco                                   CHAR(1),
    DanniIndirettiCodiceGaranzia                 CHAR(2),
    DanniIndirettiValoreAssicurato               VARCHAR(9),
    DanniIndirettiSommaAssicurato                VARCHAR(7),
    DanniIndirettiPremio                         VARCHAR(7),
    AssistenzaPsicologicaCombinazione            CHAR(2),
    AssistenzaPsicologicaPremio                  VARCHAR(7),
    AssistenzaDoveSeiPremio                      VARCHAR(7),
    TariffaVita                                  VARCHAR(12),
    VcvtProdotto                                 VARCHAR(12),
    Protezione                                   CHAR(1),
    PayXuse                                      CHAR(1),
    Riclassifica                                 CHAR(5),
    OctoContratto                                CHAR(1),
    OctoFormula                                  CHAR(1),
    TrasportiSpeciali                            CHAR(1),
    TrasportiMoto                                CHAR(1),
    Sospensione                                  CHAR(1),
    KmPartenza                                   VARCHAR(7),
    FlagTipoVincolo                              CHAR(1),
    VcvtDataVersione                             VARCHAR(8),
    VcvtPacchetto                                VARCHAR(10),
    VcvtDataPacchetto                            VARCHAR(8),
    VcvtAdeguamentoAutomatico                    CHAR(1),
    VcvtSettoreArd                               VARCHAR(12),
    VcvtValoreAssicurato                         VARCHAR(11),
    VcvtValoreAssicuratoAccessori                VARCHAR(11),
    VIncendioFormaVendita                        VARCHAR(12),
    VIncendioMinimoIndennizzabile                VARCHAR(11),
    VIncendioMassimale                           VARCHAR(11),
    VIncendioForzaturaLimiti                     CHAR(1),
    VFurtoFormaVendita                           VARCHAR(12),
    VFurtoMinimoIndennizzabile                   VARCHAR(11),
    VFurtoMassimale                              VARCHAR(11),
    VFurtoForzaturaLimiti                        CHAR(1),
    VKaskoFormaVendita                           VARCHAR(12),
    VKaskoMinimoIndennizzabile                   VARCHAR(11),
    VKaskoMassimale                              VARCHAR(11),
    VKaskoForzaturaLimiti                        CHAR(1),
    VSocioPoliticiFormaVendita                   VARCHAR(12),
    VSocioPoliticiMinimoIndennizzabile           VARCHAR(11),
    VSocioPoliticiMassimale                      VARCHAR(11),
    VSocioPoliticiForzaturaLimiti                CHAR(1),
    VAtmosfericiFormaVendita                     VARCHAR(12),
    VAtmosfericiMinimoIndennizzabile             VARCHAR(11),
    VAtmosfericiMassimale                        VARCHAR(11),
    VAtmosfericiForzaturaLimiti                  CHAR(1),
    VcristalliFormaVendita                       VARCHAR(12),
    VcristalliScoperto                           VARCHAR(7),
    VCristalliMinimoIndennizzabile               VARCHAR(11),
    VcristalliFranchigia                         VARCHAR(11),
    VcristalliMassimale                          VARCHAR(11),
    VCristalliForzaturaLimiti                    CHAR(1),
    VcristalliPremio                             VARCHAR(11),
    VAssistenzaPsicologicaFormaVendita           VARCHAR(12),
    VAssistenzaPsicologicaPremio                 VARCHAR(11),
    VAssistenzaFormaVendita                      VARCHAR(12),
    VAssistenzaMassimale                         VARCHAR(11),
    VAssistenzaForzaturaLimiti                   CHAR(1),
    VTutelaFormaVendita                          VARCHAR(12),
    VTutelaMassimale                             VARCHAR(11),
    VTutelaForzaturaLimiti                       CHAR(1),
    VGaranzieAccessorieFormaVendita              VARCHAR(12),
    VGaranzieAccessorieMassimale                 VARCHAR(11),
    VGaranzieAccessorieForzaturaLimiti           CHAR(1),
    VRitiroPatenteFormaVendita                   VARCHAR(12),
    VRitiroPatenteForzaturaLimiti                CHAR(1)
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

DROP TABLE Polizze3;

CREATE TABLE Polizze3
(
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    VInfortuniFormaVendita                       VARCHAR(12),
    VInfortuniMassimaleMorte                     VARCHAR(11),
    VInfortuniMassimaleIP                        VARCHAR(11),
    VInfortuniMassimaleSpeseSanitarie            VARCHAR(11),
    VInfortuniMassimaleTortoRagione              VARCHAR(11),
    VRcaTipoRivalsa1                             CHAR(1),
    VRcaTipoRivalsa2                             CHAR(1),
    VRcaTipoRivalsa3                             CHAR(1),
    VRcaTipoRivalsa4                             CHAR(1),
    VRcaTipoRivalsa5                             CHAR(1),
    VRcaAutoPrestoBene                           CHAR(1),
    VRcaKmDichiarati                             VARCHAR(7),
    VeicoliUsoSpeciale                           CHAR(3),
    VeicoliDanniCoseTerziTrasportati             CHAR(1),
    VeicoliVelocita                              CHAR(3),
    ResidenzaRegione                             CHAR(3),
    ResidenzaCap                                 CHAR(5),
    VAtmosfericiAutoPrestoBene                   CHAR(1),
    VSocioPoliticiAutoPrestoBene                 CHAR(1),
    VFurtoAutoPrestoBene                         CHAR(1),
    VIncendioAutoPrestoBene                      CHAR(1),
    VIncendioClausolaVip                         CHAR(1),
    VAssistenzaClausolaVip                       CHAR(1),
    VinfMassRicovero                             VARCHAR(11),
    VkasApb                                      CHAR(1),
    VkasVip                                      CHAR(1),
    VoctAutoIntelligen                           CHAR(1),
    VvipFormaGar                                 CHAR(3),
    VvipFormaVendita                             VARCHAR(12),
    VvipMassimale                                VARCHAR(11),
    VvipApb                                      CHAR(1),
    VvipPremio                                   VARCHAR(11),
    VcssFormaGar                                 CHAR(3),
    VcssFormaVendita                             VARCHAR(12),
    VcssMassimale                                VARCHAR(11),
    VcssPremio                                   VARCHAR(11),
    VoroFormaGar                                 CHAR(3),
    VoroFormaVendita                             VARCHAR(12),
    VoroMassimale                                VARCHAR(11),
    VoroPremio                                   VARCHAR(11),
    VresFormaGar                                 CHAR(3),
    VresFormaVendita                             VARCHAR(12),
    VresMassimale                                VARCHAR(11),
    VresPremio                                   VARCHAR(11),
    VpepFormaGar                                 CHAR(3),
    VpepFormaVendita                             VARCHAR(12),
    VpepMassimale                                VARCHAR(11),
    VpepPremio                                   VARCHAR(11),
    VrcpFormaGar                                 CHAR(3),
    VrcpFormaVendita                             VARCHAR(12),
    VrcpMassimale                                VARCHAR(11),
    VrcpPremio                                   VARCHAR(11),
    VinpFormaGar                                 CHAR(3),
    VinpFormaVendita                             VARCHAR(12),
    VinpMassimale                                VARCHAR(11),
    VinpPremio                                   VARCHAR(11),
    VcarFormaGar                                 CHAR(3),
    VcarFormaVendita                             VARCHAR(12),
    VcarMassimale                                VARCHAR(11),
    VcarPremio                                   VARCHAR(11),
    VrtiFormaGar                                 CHAR(3),
    VrtiFormaVendita                             VARCHAR(12),
    VrtiMassimale                                VARCHAR(11),
    VrtiPremio                                   VARCHAR(11),
    VdapFormaGar                                 CHAR(3),
    VdapFormaVendita                             VARCHAR(12),
    VdapFlAccSsi                                 CHAR(1),
    VdapPremio                                   VARCHAR(11),
    VcvmFormaGar                                 CHAR(3),
    VcvmFormaVendita                             VARCHAR(12),
    VcvmFlAccSsi                                 CHAR(1),
    VcvmValAccNsi                                VARCHAR(11),
    VcvmValAppRte                                VARCHAR(11),
    VcvmValBagOgg                                VARCHAR(11),
    VcvmPremio                                   VARCHAR(11),
    NumeroVeicolo                                VARCHAR(7),
    FlexAgenzia                                  VARCHAR(7),
    ScontoCampagna                               VARCHAR(7),
    ScontoConvenzione                            VARCHAR(7),
    DescVincolataria                             VARCHAR(25),
    CodfisAmministratore                         VARCHAR(16),
    CompProvenienza                              CHAR(3),
    SptVguaFormaGar                              CHAR(3),
    SptVguaFormaVendita                          VARCHAR(12),
    SptVguaMassimale                             VARCHAR(11),
    SptVguaPremio                                VARCHAR(11),
    SptVmerFormaGar                              CHAR(3),
    SptVmerFormaVendita                          VARCHAR(12),
    SptVmerMassimale                             VARCHAR(11),
    SptVmerPremio                                VARCHAR(11),
    SptVgrcFormaGar                              CHAR(3),
    SptVgrcFormaVendita                          VARCHAR(12),
    SptVgrcMassimale                             VARCHAR(11),
    SptVgrcPremio                                VARCHAR(11),
    SptVdomFormaGar                              CHAR(3),
    SptVdomFormaVendita                          VARCHAR(12),
    SptVdomMassimale                             VARCHAR(11),
    SptVdomPremio                                VARCHAR(11),
    SptVkasPremioBloc                            VARCHAR(9),
    SptVkasTipoGar                               CHAR(1),
    SptVinfMassGesso                             VARCHAR(11),
    SptVespPremioBloc                            VARCHAR(9),
    SptVatmPremioBloc                            VARCHAR(9),
    SptVIncendioPremioBloc                       VARCHAR(9),
    SptVfurPremioBloc                            VARCHAR(9),
    SptVfurFlAppIndeb                            CHAR(1),
    SptVcvtValBloc                               VARCHAR(9),
    SptVcvtFasciaValBloc                         CHAR(3),
    SptVeicRuoteMotr                             CHAR(1),
    SptVeicTipoMoto                              CHAR(4),
    SptVeicNumAssi                               CHAR(3),
    SptVrcaFar                                   CHAR(2),
    SptVrcaCoeffWelcomeUpto                      VARCHAR(7),
    SptVrcaCoeffWelcUptoGeco                     VARCHAR(7),
    SptVrcaAnnoProtezione                        CHAR(4),
    SptVclmFar                                   CHAR(2),
    SptVclmAnniCu1                               CHAR(3),
    SptVclmAnnoProtezione                        CHAR(4),
    SptValtSegmento                              VARCHAR(12),
    SptValtAnniPtf                               CHAR(3)
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

DROP TABLE Polizze4;

CREATE TABLE Polizze4
(
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    ValtNazione                                  CHAR(03),
    VassEstensioneRim                            CHAR(01),
    VassFascia                                   VARCHAR(10),
    VatrFlPolGratuita                            CHAR(01),
    VatrDichContr                                CHAR(01),
    VatrFlAqua                                   CHAR(01),
    VoctDataEdizInfopriv                         CHAR(08),
    VoctCodInfopriv                              CHAR(10),
    VoctTitoloModulo                             CHAR(01),
    VoctProprDispos                              CHAR(01),
    VoctContattContr                             CHAR(01),
    VoctConsCommm                                CHAR(01),
    VoctConsProfil                               CHAR(01),
    FeaOmniacrm                                  VARCHAR(15),
    Fea                                          CHAR(01),
    FeaMail                                      CHAR(01),
    VeicStorico                                  CHAR(01),
    ExRete1                                      CHAR(01),
    NumArchivio                                  CHAR(11),
    PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

DROP TABLE PolizzeSostituite;
CREATE TABLE PolizzeSostituite
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    VecchioCodiceRamo                            SMALLINT,
    VecchioNumeroPolizza                         INTEGER
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

DROP TABLE PolizzeClausole;
CREATE TABLE PolizzeClausole
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    Clausola                                     SMALLINT
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza, Clausola)
);

DROP TABLE PolizzeRipartizionePremio;
CREATE TABLE PolizzeRipartizionePremio
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    CodiceCategoriaRischio                       SMALLINT,
    CodiceRamoMinisteriale                       CHAR(3),
    PremioNettoCategoriaRischio                  CURRENCY
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza, CodiceCategoriaRischio)
);

DROP TABLE PolizzeRipartizioneCoass;
CREATE TABLE PolizzeRipartizioneCoass
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    CompagniaDelegante                           SMALLINT,
    AgenziaDelegante                             CHAR(5),
    PercentualeQuota                             CURRENCY
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza, CompagniaDelegante)
);

DROP TABLE PolizzeRipartizioneCAG;
CREATE TABLE PolizzeRipartizioneCAG
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER,
    SptVcagCodice                                CHAR(5),
    SptVcagSconto                                VARCHAR(7),
    SptVcagImporto                               VARCHAR(11),
    SptVcagCodPtf                                CHAR(3)
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza, SptVcagCodice)
);

DROP TABLE PolizzeCancellate;
CREATE TABLE PolizzeCancellate
(                     
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           INTEGER,
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    Ramo                                         SMALLINT,
    Polizza                                      INTEGER
    , PRIMARY KEY(CodicePuntoVendita, Ramo, Polizza)
);

