DROP TABLE Sinistri;

CREATE TABLE Sinistri
(
    ProgressivoFile                              INTEGER,
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    EsercizioSinistro                            SMALLINT,
    AgenziaSinistro                              SMALLINT,
    RamoSinistro                                 CHAR(4),
    NumeroSinistro                               INTEGER,
    Ispettorato                                  CHAR(5),
    AgenziaPolizza                               SMALLINT,
    RamoPolizza                                  CHAR(3),
    NumeroPolizza                                INTEGER,
    NumeroVeicolo                                INTEGER,
    CodiceSubagenzia                             CHAR(3),
    CodiceProduttore                             CHAR(7),
    DataAvvenimentoSinistro                      DATE,
    DataDenuncia                                 DATE,
    DataProtocolloCarico                         DATE,
    StatoAvvenimentoSinistro                     CHAR(3),
    ProvinciaAvvenimentoSinistro                 CHAR(3),
    CasisticaCID                                 CHAR(3),
    TipoCid                                      CHAR(3),
    TipoChiusura                                 CHAR(3),
    TipoSinistro                                 CHAR(2),
    FlagCosePersone                              CHAR(1),
    CodiceTipoRamo                               CHAR(1),
    NostraQuota                                  VARCHAR(8),
    DataPreventivo                               DATE,
    PrimoPreventivo                              CURRENCY,
    ImportoQuotaPagatoDel                        CURRENCY,
    ImportoQuotaPagatoAl                         CURRENCY,
    ImportoQuotaRecuperatoDel                    CURRENCY,
    ImportoQuotaRecuperatoAl                     CURRENCY,
    IndicatoreFranchigiaPortafoglio              CHAR(1),
    CodiceConvenzione                            CHAR(5),
    CodiceProdotto                               CHAR(5),
    NominativoAssicurato                         VARCHAR(30),
    CognomeAssicurato                            VARCHAR(20),
    NomeAssicurato                               VARCHAR(10),
    TargaAssicurato                              VARCHAR(10),
    NominativoControparte                        VARCHAR(30),
    CognomeControparte                           VARCHAR(20),
    NomeControparte                              VARCHAR(10),
    CodiceFiscaleControparte                     CHAR(16),
    CompagniaControparte                         CHAR(5),
    TargaControparte                             VARCHAR(10),
    Compagnia                                    SMALLINT,
    AgenziaPolizzaArrivo                         CHAR(5),
    CodiceLiquidatore                            CHAR(4),
    TipoDelega                                   CHAR(1),
    CodiceFiscaleAssicurato                      CHAR(16),
    DataUltimoPagamento                          DATE,
    DataRicevimentoDenuncia                      DATE,
    CodiceCompagniaControparte                   CHAR(5),
    FlagAperturaAIDASERTEL                       CHAR(1),
    NumeroPosizioniProtocollate                  CHAR(3),
    TipologiaDenuncia                            CHAR(1),
    PresentatoreDenuncia                         CHAR(1),
    AutoreDenuncia                               CHAR(1),
    NumeroCartellaSertel                         CHAR(9),
    CodicePeritoIncaricato                       CHAR(5),
    ProvinciaCarrozzeriaIncaricata               CHAR(2),
    CodiceAniaCarrozzeriaIncaricata              CHAR(9),
    DataInterventoLegale                         DATE,
    LivelloInformatizzazioneCarrozzeria          CHAR(2),
    ContatoreSinistri                            SMALLINT,
    IndicatoreCardGestionaria                    SMALLINT,
    IndicatoreCardDebitrice                      SMALLINT,
    IndicatoreNoCard                             SMALLINT,
    QuotaPagatoNoCardAl                          CURRENCY,
    QuotaPagatoNoCardDel                         CURRENCY,
    QuotaPagatoCardAttivoAl                      CURRENCY,
    QuotaPagatoCardAttivoDel                     CURRENCY,
    CodiceAgenziaMadre                           CHAR(5),
    DataAperturaSinistro                         DATE,
    FlagLegale                                   CHAR(1),
    TipoDenuncia                                 CHAR(1),
    IndicatoreSinistroCanalizzato                CHAR(1),
    CodiceAniacarrozzeriaPagata                  CHAR(7),
    CodiceAniacarrozzeriaCanalizzata             CHAR(9),
    PreventivoStatisticoQuota                    CURRENCY,
    SettoreTariffazione                          CHAR(1),
    TipoRamo                                     CHAR(5),
    Lesioni                                      CHAR(3),
    Morti                                        CHAR(3),
    Baremes1ControparteVeicoloA                  CHAR(2),
    Baremes1ControparteVeicoloB                  CHAR(2),
    Baremes2NostraparteVeicoloA                  CHAR(2),
    Baremes2NostraparteVeicoloB                  CHAR(2),
    QuotaImportoNettoDaRecuperareFranchigie      CURRENCY,
    QuotaImportoNettoDaRecuperareRivalse         CURRENCY,
    QuotaImportoNettoDaRecuperarePerAltro        CURRENCY,
    QuotaImportoNettoRecuperatoFranchigieAl      CURRENCY,
    QuotaImportoNettoRecuperatoFranchigieDel     CURRENCY,
    QuotaImportoNettoRecuperatoRivalseAl         CURRENCY,
    QuotaImportoNettoRecuperatoRivalseDel        CURRENCY,
    QuotaImportoNettoRecuperatoPerAltroAl        CURRENCY,
    QuotaImportoNettoRecuperatoPerAltroDel       CURRENCY,
    QuotaSpeseAl                                 CURRENCY,
    QuotaSpeseDel                                CURRENCY,
    ImportoRiserva                               CURRENCY,
    ForzaturaRegolaritaContrattuale              CHAR(1),
    RegolaritaAmministrativa                     CHAR(1),
    ForfaitDebitorePagatoAl                      CURRENCY,
    ForfaitDebitorePagatoDel                     CURRENCY,
    ForfaitGestionarioPagatoAl                   CURRENCY,
    ForfaitGestionarioPagatoDel                  CURRENCY,
    ForfaitGestionarioRiserva                    CURRENCY,
    ForfaitDebitoreRiserva                       CURRENCY,
    RamoGestione                                 CHAR(3),
    AgenziaTBAIINCA                              CHAR(0),
    CompagniaNew                                 SMALLINT,
    StatoBilancistico                            VARCHAR(20),
    DataAggiornamentoStatoBilancistico           DATE,
    AnnoCompetenzaStatoBilancistico              SMALLINT,
    StatoTecnico                                 VARCHAR(20),
    DataAggiornamentoStatoTecnico                DATE,
    AnnoCompetenzaStatoTecnico                   SMALLINT,
    StatoAmministrativo                          VARCHAR(20),
    DataAggiornamentoStatoAmministrativo         DATE,
    AnnoCompetenzaStatoAmministrativo            SMALLINT,
    StatoRecupero                                VARCHAR(20),
    DataAggiornamentoStatoRecupero               DATE,
    AnnoCompetenzaStatoRecupero                  SMALLINT,
    StatoForfait                                 VARCHAR(20),
    DataAggiornamentoStatoForfait                DATE,
    AnnoCompetenzaStatoForfait                   SMALLINT,
    CodicePeritoIncaricato1                      CHAR(10),
    DataElaborazioneSinistri                     DATE,
    ProgCompagnia                                CHAR(3),
    CompagniaCid                                 CHAR(3)
);



SELECT 
EsercizioSinistro,
AgenziaSinistro,
RamoSinistro,
NumeroSinistro,
TipoCid,
TipoChiusura,
PrimoPreventivo,
ImportoQuotaPagatoDel,
ImportoQuotaPagatoAl,
ImportoQuotaRecuperatoDel,
ImportoQuotaRecuperatoAl,
DataUltimoPagamento,
NumeroPosizioniProtocollate,
IndicatoreCardGestionaria,
IndicatoreCardDebitrice,
IndicatoreNoCard,
QuotaImportoNettoRecuperatoFranchigieAl,
QuotaImportoNettoRecuperatoFranchigieDel,
QuotaImportoNettoRecuperatoRivalseAl,
QuotaImportoNettoRecuperatoRivalseDel,
QuotaImportoNettoRecuperatoPerAltroAl,
QuotaImportoNettoRecuperatoPerAltroDel,
QuotaSpeseAl,
QuotaSpeseDel,
ImportoRiserva
FROM SINISTRI;




CREATE TABLE Incarichi
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    TipoRecord                                   CHAR(1),
    DataCompetenzaElaborazione                   DATE,
    AgenziaPolizzaArrivo                         CHAR(5),
    AgenziaPolizza                               CHAR(5),
    EsercizioSinistro                            CHAR(4),
    AgenziaSinistro                              CHAR(4),
    NumeroSinistro                               VARCHAR(7),
    NumeroPosizione                              CHAR(3),
    CodiceFiscaleDanneggiato                     CHAR(16),
    CognomeDanneggiato                           VARCHAR(40),
    NomeDanneggiato                              VARCHAR(40),
    CodicePeritoIncaricato                       CHAR(7),
    CodiceProfessione                            CHAR(3),
    DataIncarico                                 DATE,
    TipoIncarico                                 CHAR(2),
    DataRestituzioneIncarico                     DATE,
    TipoIncaricoRestituito                       CHAR(2),
    CodiceAgenziaMadre                           CHAR(5),
    CompagniaNew                                 CHAR(1),
    CodicePeritoSAP                              CHAR(10),
    TipoIncaricoCC                               VARCHAR(30),
    TipoSpecializzazioneFiduciario               VARCHAR(50),
    TipoFiduciario                               VARCHAR(50),
    StatoIncarico                                VARCHAR(50),
    StatoIncaricoCarrozzeria                     VARCHAR(50),
    EsitoPerizia                                 VARCHAR(30)
);

CREATE TABLE Pagamenti
(
    DataElaborazione                             DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    TipoRecord                                   CHAR(1),
    DataCompetenzaElaborazione                   DATE,
    AgenziaPolizzaArrivo                         CHAR(5),
    AgenziaPolizza                               CHAR(5),
    EsercizioSinistro                            CHAR(4),
    AgenziaSinistro                              CHAR(4),
    NumeroSinistro                               VARCHAR(7),
    NumeroPosizione                              CHAR(3),
    CodiceFiscaleDanneggiato                     CHAR(16),
    CognomeDanneggiato                           VARCHAR(40),
    NomeDanneggiato                              VARCHAR(40),
    TipoPagamento                                CHAR(2),
    FormaPagamento                               CHAR(2),
    DataPagamento                                DATE,
    NumeroAssegno                                VARCHAR(15),
    QuotaImportoPagato                           CURRENCY,
    CodiceAgenziaMadre                           CHAR(5)
);

CREATE TABLE Periti
(
    DataCompetenzaElaborazione                   DATE,
    CodicePuntoVendita                           CHAR(5),
    Progressivo                                  CHAR(2),
    TipoElaborazione                             CHAR(2),
    CodicePerito                                 CHAR(5),
    TipoPerito                                   CHAR(1),
    Cognome                                      VARCHAR(45),
    Nome                                         VARCHAR(15),
    CodiceFiscale                                CHAR(16),
    Telefono                                     VARCHAR(15),
    Cellulare                                    VARCHAR(15),
    Email                                        VARCHAR(50),
    CodicePeritoSAP                              CHAR(10)
);

