Namespace P01201
    Public Class P01201DE
        Inherits P00000DE

        Public DecodeRischioProfessionale As New Dizionario(Of Integer, String)
        Public DecodeAttivitaProfessionale As New Dizionario(Of Integer, String)
        Public DecodePersonaSceltaForma As New Dizionario(Of Integer, String)
        Public DecodePersonaITForma As New Dizionario(Of Integer, String)
        Public DecodePersonaRicoveroForma As New Dizionario(Of Integer, String)
        Public DecodePersonaImmobilizzazioneForma As New Dizionario(Of Integer, String)
        Public DecodeFamigliaSceltaForma As New Dizionario(Of Integer, String)
        Public DecodeVeicoloSceltaForma As New Dizionario(Of Integer, String)
        Public DecodeTipologiaVeicolo As New Dizionario(Of Integer, String)
        Public DecodeMalattiaITSceltaForma As New Dizionario(Of Integer, String)
        Public DecodeMalattiaRicoveroSceltaForma As New Dizionario(Of Integer, String)
        Public DecodeAssistenzaPacchetto As New Dizionario(Of Integer, String)
        Public DecodeTipoAttivita As New Dizionario(Of Integer, String)
        Public DecodePersonaRenditaVitaliziaMassimale As New Dizionario(Of Decimal, String)
        Public DecodePersonaFranchigiaRelativaFranchigia As New Dizionario(Of Decimal, String)
        Public DecodeAttivitaToRischioProfessionale As New Dizionario(Of Integer, Integer)
        Public DecodeVeicoloRicoveroForma As New Dizionario(Of Integer, String)

        Sub New()
            With DecodeSezione
                .Add(TipoSezione.Persona, "Persona")
                .Add(TipoSezione.Famiglia, "Famiglia")
                .Add(TipoSezione.Veicolo, "Veicolo")
                .Add(TipoSezione.Malattia, "Malattia")
                .Add(TipoSezione.Assistenza, "Assistenza")
            End With

            With DecodePartita
                .Add(TipoPartita.Persona, "Persona")
                .Add(TipoPartita.Famiglia, "Famiglia")
                .Add(TipoPartita.Veicolo, "Veicolo")
                .Add(TipoPartita.Malattia, "Malattia")
                .Add(TipoPartita.Assistenza, "Assistenza")
            End With

            With DecodeGaranzia
                .Add(TipoGaranzia.PersonaBase, "Garanzia base")
                .Add(TipoGaranzia.PersonaMorte, "Morte")
                .Add(TipoGaranzia.PersonaIP, "Invalidita Permanente")
                .Add(TipoGaranzia.PersonaIT, "Inabilita Temporanea")
                .Add(TipoGaranzia.PersonaRicovero, "Indennita per ricovero")
                .Add(TipoGaranzia.PersonaImmobilizzazione, "Indennita per immobilizzazione")
                .Add(TipoGaranzia.PersonaSpeseMediche, "Rimborso Spese Mediche")
                .Add(TipoGaranzia.PersonaRenditaVitalizia, "Rendita Vitalizia")
                .Add(TipoGaranzia.PersonaFranchigiaRelativa, "Invalidità Permanente con franchigia relativa")
                .Add(TipoGaranzia.PersonaFranchigia5, "Invalidità Permanente con franchigia 5%")
                .Add(TipoGaranzia.PersonaFranchigia3, "Invalidita Permanente con franchigia 3%")
                .Add(TipoGaranzia.PersonaFranchigiaDifferenziata, "Invalidità Permanente con franchigie differenziate")
                .Add(TipoGaranzia.PersonaIndennizzoVariabile, "Invalidità Permanente con indennizzo variabile")
                .Add(TipoGaranzia.PersonaSpecifica, "Invalidita Permanente con supervalutazione Specifica")
                .Add(TipoGaranzia.PersonaMaggiorazione, "Invalidità Permanente con maggiorazione dell’indennizzo")
                .Add(TipoGaranzia.PersonaTabellaINAIL, "Invalidita Permanente con tabella INAIL")
                .Add(TipoGaranzia.PersonaTabellaUGFPLUS, "Invalidità Permanente con tabella UGF PLUS")
                .Add(TipoGaranzia.PersonaRischiDomestivi, "Estensione rischi domestici")
                .Add(TipoGaranzia.PersonaSportsAltoRischioMorte, "Sports Alto Rischio morte")
                .Add(TipoGaranzia.PersonaSportsAltoRischioIP, "Sports Alto Rischio invalidità permanente")
                .Add(TipoGaranzia.PersonaSportsAltoRischioRicovero, "Sports Alto Rischio per ricovero")
                .Add(TipoGaranzia.PersonaSportsAltoRischioSpeseMediche, "Sports Alto Rischio spese mediche")
                .Add(TipoGaranzia.PersonaSportsMotoristiciMorte, "Sports Motoristici morte")
                .Add(TipoGaranzia.PersonaSportsMotoristiciIP, "Sports Motoristici invalidità permanente")
                .Add(TipoGaranzia.PersonaSportsAereiMorte, "Sports Aerei morte")
                .Add(TipoGaranzia.PersonaSportsAereiIP, "Sports Aerei invalidità permanente")
                .Add(TipoGaranzia.PersonaEsclusioneGuidaMotoveicoli, "Esclusione guida motoveicoli")
                .Add(TipoGaranzia.PersonaEsclusioneSports, "Esclusione sports")
                .Add(TipoGaranzia.FamigliaBase, "Garanzia base")
                .Add(TipoGaranzia.FamigliaMorte, "Morte")
                .Add(TipoGaranzia.FamigliaIP, "Invalidita Permanente")
                .Add(TipoGaranzia.FamigliaRicoveroConvalescenza, "Indennita per ricovero e Convalescenza")
                .Add(TipoGaranzia.FamigliaImmobilizzazione, "Indennita per immobilizzazione")
                .Add(TipoGaranzia.FamigliaSpeseMediche, "Rimborso Spese Mediche")
                .Add(TipoGaranzia.FamigliaTabellaINAIL, "Invalidita Permanente Tabella INAIL")
                .Add(TipoGaranzia.FamigliaFranchigiaDifferenziata, "Invalidità Permanente con franchigie differenziate")
                .Add(TipoGaranzia.FamigliaRischiDomestivi, "Estensione rischi domestici")
                .Add(TipoGaranzia.VeicoloBase, "Garanzia base")
                .Add(TipoGaranzia.VeicoloMorte, "Morte")
                .Add(TipoGaranzia.VeicoloIP, "Invalidita Permanente")
                .Add(TipoGaranzia.VeicoloRicoveroConvalescenza, "Indennita per ricovero e Convalescenza")
                .Add(TipoGaranzia.VeicoloImmobilizzazione, "Indennita per immobilizzazione")
                .Add(TipoGaranzia.VeicoloSpeseMediche, "Rimborso Spese Mediche")
                .Add(TipoGaranzia.VeicoloTabellaINAIL, "Invalidita Permanente Tabella INAIL")
                .Add(TipoGaranzia.VeicoloFranchigiaDifferenziata, "Invalidità Permanente con franchigie differenziate")
                .Add(TipoGaranzia.VeicoloFranchigia5, "Invalidità Permanente con franchigia 5%")
                .Add(TipoGaranzia.VeicoloFranchigiaAssoluta, "Invalidità Permanente da infortunio con franchigia assoluta")
                .Add(TipoGaranzia.MalattiaBase, "Garanzia base")
                .Add(TipoGaranzia.MalattiaInvaliditaPermanente, "Invalidità Permanente da malattia")
                .Add(TipoGaranzia.MalattiaInabilitaTemporanea, "Inabilità Temporanea da malattia")
                .Add(TipoGaranzia.MalattiaRicovero, "Indennità per Ricovero da malattia")
                .Add(TipoGaranzia.MalattiaImmobilizzazione, "Indennità per Immobilizzazione da malattia")
                .Add(TipoGaranzia.AssistenzaBase, "Assistenza")
            End With

            With DecodeFrazionamenti
                .Add(FrazionamentiEnum.temporaneo, "temporaneo")
                .Add(FrazionamentiEnum.annuale, "annuale")
                .Add(FrazionamentiEnum.semestrale, "semestrale")
                .Add(FrazionamentiEnum.quadrimestrale, "quadrimestrale")
                .Add(FrazionamentiEnum.trimestrale, "trimestrale")
            End With

            With DecodeRischioProfessionale
                .Add(RischioProfessionaleEnum.ClasseA, "Classe A")
                .Add(RischioProfessionaleEnum.ClasseB, "Classe B")
                .Add(RischioProfessionaleEnum.ClasseC, "Classe C")
                .Add(RischioProfessionaleEnum.ClasseD, "Classe D")
                .Add(RischioProfessionaleEnum.ClasseRD, "Classe RD")
            End With

            With DecodeAttivitaProfessionale
                .Add(AttivitaProfessionaleEnum.Dipendente, "Dipendente")
                .Add(AttivitaProfessionaleEnum.LiberoProfessionista, "Libero Professionista")
                .Add(AttivitaProfessionaleEnum.NoAttivitaProfessionale, "No attività professionale")
            End With

            With DecodePersonaSceltaForma
                .Add(PersonaSceltaFormaEnum.TempoLiberoLavoroAll, "Tempo libero e Lavoro - rischio professionale ed extraprofessionale")
                .Add(PersonaSceltaFormaEnum.TempoLiberoLavoroPrf, "Tempo libero e Lavoro - rischio professionale")
                .Add(PersonaSceltaFormaEnum.TempoLiberoLavoroExt, "Tempo libero e Lavoro - rischio extraprofessionale")
                .Add(PersonaSceltaFormaEnum.TempoLiberoLavoroTop, "Tempo libero e Lavoro - Top Target")
                .Add(PersonaSceltaFormaEnum.FullTime, "Full time")
                .Add(PersonaSceltaFormaEnum.FullTimeTop, "Full time - Top Target")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile01, "Full time Formula facile - combinazione 1")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile02, "Full time Formula facile - combinazione 2")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile03, "Full time Formula facile - combinazione 3")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile04, "Full time Formula facile - combinazione 4")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile05, "Full time Formula facile - combinazione 5")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile06, "Full time Formula facile - combinazione 6")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile07, "Full time Formula facile - combinazione 7")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile08, "Full time Formula facile - combinazione 8")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile09, "Full time Formula facile - combinazione 9")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile10, "Full time Formula facile - combinazione 10")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile11, "Full time Formula facile - combinazione 11")
                .Add(PersonaSceltaFormaEnum.FullTimeFormulaFacile12, "Full time Formula facile - combinazione 12")
                .Add(PersonaSceltaFormaEnum.Circolazione01, "Circolazione - combinazione 1")
                .Add(PersonaSceltaFormaEnum.Circolazione02, "Circolazione - combinazione 2")
                .Add(PersonaSceltaFormaEnum.Circolazione03, "Circolazione - combinazione 3")
                .Add(PersonaSceltaFormaEnum.Circolazione04, "Circolazione - combinazione 4")
                .Add(PersonaSceltaFormaEnum.Circolazione05, "Circolazione - combinazione 5")
                .Add(PersonaSceltaFormaEnum.Circolazione06, "Circolazione - combinazione 6")
                .Add(PersonaSceltaFormaEnum.Circolazione07, "Circolazione - combinazione 7")
                .Add(PersonaSceltaFormaEnum.Circolazione08, "Circolazione - combinazione 8")
                .Add(PersonaSceltaFormaEnum.Circolazione09, "Circolazione - combinazione 9")
                .Add(PersonaSceltaFormaEnum.Circolazione10, "Circolazione - combinazione 10")
                .Add(PersonaSceltaFormaEnum.Circolazione11, "Circolazione - combinazione 11")
                .Add(PersonaSceltaFormaEnum.Circolazione12, "Circolazione - combinazione 12")
            End With

            With DecodePersonaITForma
                .Add(PersonaITFormaEnum.PersonaITParziale, "Parziale")
                .Add(PersonaITFormaEnum.PersonaITIntegrale, "Integrale")
                .Add(PersonaITFormaEnum.PersonaITRicovero, "limitata per ricovero e convalescenza (cp 225)")
            End With

            With DecodePersonaRicoveroForma
                .Add(PersonaRicoveroFormaEnum.PersonaRicoveroSoloRicovero, "Solo ricovero")
                .Add(PersonaRicoveroFormaEnum.PersonaRicoveroConvalescenza, "Ricovero e convalescenza")
                .Add(PersonaRicoveroFormaEnum.PersonaRicoveroConvalescenzaProlungata, "Ricovero e convalescenza prolungata (cp 228)")
            End With

            With DecodePersonaImmobilizzazioneForma
                .Add(PersonaImmobilizzazioneFormaEnum.PersonaImmobilizzazioneNormale, "Breve")
                .Add(PersonaImmobilizzazioneFormaEnum.PersonaImmobilizzazioneProlungata, "Prolungata (cp 229)")
            End With

            With DecodeFamigliaSceltaForma
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile11, "Full time Formula facile - combinazione 1")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile12, "Full time Formula facile - combinazione 2")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile13, "Full time Formula facile - combinazione 3")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile14, "Full time Formula facile - combinazione 4")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile15, "Full time Formula facile - combinazione 5")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile16, "Full time Formula facile - combinazione 6")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile17, "Full time Formula facile - combinazione 7")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile18, "Full time Formula facile - combinazione 8")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile19, "Full time Formula facile - combinazione 9")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile20, "Full time Formula facile - combinazione 10")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile21, "Full time Formula facile - combinazione 11")
                .Add(FamigliaSceltaFormaEnum.FullTimeFormulaFacile22, "Full time Formula facile - combinazione 12")
                .Add(FamigliaSceltaFormaEnum.Circolazione01, "Circolazione - combinazione 1")
                .Add(FamigliaSceltaFormaEnum.Circolazione02, "Circolazione - combinazione 2")
                .Add(FamigliaSceltaFormaEnum.Circolazione03, "Circolazione - combinazione 3")
                .Add(FamigliaSceltaFormaEnum.Circolazione04, "Circolazione - combinazione 4")
                .Add(FamigliaSceltaFormaEnum.Circolazione05, "Circolazione - combinazione 5")
                .Add(FamigliaSceltaFormaEnum.Circolazione06, "Circolazione - combinazione 6")
                .Add(FamigliaSceltaFormaEnum.Circolazione07, "Circolazione - combinazione 7")
                .Add(FamigliaSceltaFormaEnum.Circolazione08, "Circolazione - combinazione 8")
                .Add(FamigliaSceltaFormaEnum.Circolazione09, "Circolazione - combinazione 9")
                .Add(FamigliaSceltaFormaEnum.Circolazione10, "Circolazione - combinazione 10")
                .Add(FamigliaSceltaFormaEnum.Circolazione11, "Circolazione - combinazione 11")
                .Add(FamigliaSceltaFormaEnum.Circolazione12, "Circolazione - combinazione 12")
            End With

            With DecodeVeicoloSceltaForma
                .Add(VeicoloSceltaFormaEnum.CapitaliLiberi, "Capitali liberi")
                .Add(VeicoloSceltaFormaEnum.Circolazione01, "Circolazione - combinazione 1")
                .Add(VeicoloSceltaFormaEnum.Circolazione02, "Circolazione - combinazione 2")
                .Add(VeicoloSceltaFormaEnum.Circolazione03, "Circolazione - combinazione 3")
                .Add(VeicoloSceltaFormaEnum.Circolazione04, "Circolazione - combinazione 4")
                .Add(VeicoloSceltaFormaEnum.Circolazione05, "Circolazione - combinazione 5")
                .Add(VeicoloSceltaFormaEnum.Circolazione06, "Circolazione - combinazione 6")
                .Add(VeicoloSceltaFormaEnum.Circolazione07, "Circolazione - combinazione 7")
                .Add(VeicoloSceltaFormaEnum.Circolazione08, "Circolazione - combinazione 8")
                .Add(VeicoloSceltaFormaEnum.Circolazione09, "Circolazione - combinazione 9")
                .Add(VeicoloSceltaFormaEnum.Circolazione10, "Circolazione - combinazione 10")
                .Add(VeicoloSceltaFormaEnum.Circolazione11, "Circolazione - combinazione 11")
                .Add(VeicoloSceltaFormaEnum.Circolazione12, "Circolazione - combinazione 12")
            End With

            With DecodeTipologiaVeicolo
                .Add(TipologiaVeicoloEnum.Autovetture, "Autovetture")
                .Add(TipologiaVeicoloEnum.AutoMotocarri, "Autocarri/Motocarri")
                .Add(TipologiaVeicoloEnum.Motocicli, "Motocicli")
                .Add(TipologiaVeicoloEnum.Ciclomotori, "Ciclomotori")
            End With

            With DecodeVeicoloRicoveroForma
                .Add(VeicoloRicoveroFormaEnum.VeicoloRicoveroSoloRicovero, "Solo ricovero")
                .Add(VeicoloRicoveroFormaEnum.VeicoloRicoveroConvalescenza, "Ricovero e convalescenza")
            End With

            With DecodeMalattiaITSceltaForma
                .Add(MalattiaITSceltaFormaEnum.RicoveroConvalescenza, "Ricovero e convalescenza")
                .Add(MalattiaITSceltaFormaEnum.Integrale, "Integrale")
            End With

            With DecodeMalattiaRicoveroSceltaForma
                .Add(MalattiaRicoveroSceltaFormaEnum.SoloRicovero, "Solo ricovero")
                .Add(MalattiaRicoveroSceltaFormaEnum.RicoveroConvalescenza, "Ricovero e convalescenza")
            End With

            With DecodeAssistenzaPacchetto
                .Add(AssistenzaPacchettoEnum.PacchettoCompleto, "Pacchetto completo")
                .Add(AssistenzaPacchettoEnum.PacchettoTop, "Pacchetto completo Top")
                .Add(AssistenzaPacchettoEnum.PacchettoComfort, "Pacchetto Comfort")
                .Add(AssistenzaPacchettoEnum.PacchettoClassico, "Pacchetto Classico")
            End With

            With DecodeTipoAttivita
                .Add(TipoAttivitaEnum.Attivita0, "Attitività non selezionata")
                .Add(TipoAttivitaEnum.Attivita1, "Addestratori di animali")
                .Add(TipoAttivitaEnum.Attivita2, "Addetto a funivie, seggiovie, ovovie, cabinovie con manutenzione e riparazione")
                .Add(TipoAttivitaEnum.Attivita3, "Addetto a funivie, seggiovie, ovovie, cabinovie senza manutenzione")
                .Add(TipoAttivitaEnum.Attivita4, "Addetto a servizi vari anche su pista, con lavoro manuale nell’aviazione civile")
                .Add(TipoAttivitaEnum.Attivita5, "Addetto ai giardini zoologici")
                .Add(TipoAttivitaEnum.Attivita6, "Addetto alla disinfezione, disinfestazione e derattizzazione")
                .Add(TipoAttivitaEnum.Attivita7, "Addetto alla lavorazione di bigiotteria")
                .Add(TipoAttivitaEnum.Attivita8, "Addetto alla lavorazione, manipolazione, trasporto ed uso professionale di esplosivi e contaminanti")
                .Add(TipoAttivitaEnum.Attivita9, "Addetto alla pulizia, riparazione e manutenzione di cisterne e serbatoi in genere")
                .Add(TipoAttivitaEnum.Attivita10, "Addetto all’abbattimento di piante")
                .Add(TipoAttivitaEnum.Attivita11, "Addetto alle pulizie pavimenti")
                .Add(TipoAttivitaEnum.Attivita12, "Addetto alle pulizie vetri e insegne")
                .Add(TipoAttivitaEnum.Attivita13, "Addetto allo spurgo pozzi neri e manutenzione reti fognarie")
                .Add(TipoAttivitaEnum.Attivita14, "Addetto autolavaggio")
                .Add(TipoAttivitaEnum.Attivita15, "Addetto autorimesse che non lavora manualmente")
                .Add(TipoAttivitaEnum.Attivita16, "Addetto autorimesse con lavori di riparazione, manutenzione, lavaggio")
                .Add(TipoAttivitaEnum.Attivita17, "Addetto cave che dirige e sorveglia")
                .Add(TipoAttivitaEnum.Attivita18, "Addetto cave con uso di esplosivi")
                .Add(TipoAttivitaEnum.Attivita19, "Addetto cave senza uso di esplosivi")
                .Add(TipoAttivitaEnum.Attivita20, "Addetto pompe funebri con trasporto e sepoltura")
                .Add(TipoAttivitaEnum.Attivita21, "Addetto pompe funebri senza trasporto")
                .Add(TipoAttivitaEnum.Attivita22, "Addobbatore con impalcatura")
                .Add(TipoAttivitaEnum.Attivita23, "Aeronautica (in servizio permanente effettivo) assicurabile solo a terra")
                .Add(TipoAttivitaEnum.Attivita24, "Aeronautica (in servizio permanente effettivo) corpi speciali assicurabile solo a terra")
                .Add(TipoAttivitaEnum.Attivita25, "Agente di assicurazione")
                .Add(TipoAttivitaEnum.Attivita26, "Agente di borsa")
                .Add(TipoAttivitaEnum.Attivita27, "Agente di cambio")
                .Add(TipoAttivitaEnum.Attivita28, "Agente di commercio che non provvede alla consegna di prodotti")
                .Add(TipoAttivitaEnum.Attivita29, "Agente di commercio che provvede anche alla consegna di prodotti")
                .Add(TipoAttivitaEnum.Attivita30, "Agente di custodia")
                .Add(TipoAttivitaEnum.Attivita31, "Agente di Pubblica Sicurezza")
                .Add(TipoAttivitaEnum.Attivita32, "Agente di Pubblica Sicurezza corpi speciali")
                .Add(TipoAttivitaEnum.Attivita33, "Agente di viaggio")
                .Add(TipoAttivitaEnum.Attivita34, "Agente immobiliare")
                .Add(TipoAttivitaEnum.Attivita35, "Agente marittimo")
                .Add(TipoAttivitaEnum.Attivita36, "Agricoltore con uso di trattore")
                .Add(TipoAttivitaEnum.Attivita37, "Agricoltore senza uso di trattore")
                .Add(TipoAttivitaEnum.Attivita38, "Agronomo")
                .Add(TipoAttivitaEnum.Attivita39, "Albergatore con lavoro manuale")
                .Add(TipoAttivitaEnum.Attivita40, "Albergatore senza lavoro manuale")
                .Add(TipoAttivitaEnum.Attivita41, "Allenatore sportivo")
                .Add(TipoAttivitaEnum.Attivita42, "Allevatore di animali comuni diversi da bovini, equini, suini")
                .Add(TipoAttivitaEnum.Attivita43, "Allevatore di bovini, equini, suini")
                .Add(TipoAttivitaEnum.Attivita44, "Ambasciatore in paesi Unione Europea")
                .Add(TipoAttivitaEnum.Attivita45, "Ambasciatore resto del Mondo")
                .Add(TipoAttivitaEnum.Attivita46, "Amministratore")
                .Add(TipoAttivitaEnum.Attivita47, "Analista fi nanziario")
                .Add(TipoAttivitaEnum.Attivita48, "Animatore di villaggi turistici")
                .Add(TipoAttivitaEnum.Attivita49, "Annunciatrice")
                .Add(TipoAttivitaEnum.Attivita50, "Antennista con accesso ai tetti")
                .Add(TipoAttivitaEnum.Attivita51, "Antennista senza accesso ai tetti")
                .Add(TipoAttivitaEnum.Attivita52, "Antiquario con restauro")
                .Add(TipoAttivitaEnum.Attivita53, "Antiquario con sola attivita di vendita")
                .Add(TipoAttivitaEnum.Attivita54, "Antropologo")
                .Add(TipoAttivitaEnum.Attivita55, "Apicoltore")
                .Add(TipoAttivitaEnum.Attivita56, "Archeologo")
                .Add(TipoAttivitaEnum.Attivita57, "Architetto con accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita58, "Architetto senza accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita59, "Argentatore")
                .Add(TipoAttivitaEnum.Attivita60, "Armaiolo addetto alla fabbricazione")
                .Add(TipoAttivitaEnum.Attivita61, "Armaiolo addetto alla vendita")
                .Add(TipoAttivitaEnum.Attivita62, "Artiere")
                .Add(TipoAttivitaEnum.Attivita63, "Artista di strada")
                .Add(TipoAttivitaEnum.Attivita64, "Ascensorista")
                .Add(TipoAttivitaEnum.Attivita65, "Asfaltatore")
                .Add(TipoAttivitaEnum.Attivita66, "Assistente geriatrico")
                .Add(TipoAttivitaEnum.Attivita67, "Assistente sociale")
                .Add(TipoAttivitaEnum.Attivita68, "Atleta/sportivo professionista")
                .Add(TipoAttivitaEnum.Attivita69, "Attacchino")
                .Add(TipoAttivitaEnum.Attivita70, "Attore")
                .Add(TipoAttivitaEnum.Attivita71, "Ausiliario socio sanitario")
                .Add(TipoAttivitaEnum.Attivita72, "Autotrasportatore con carico e scarico")
                .Add(TipoAttivitaEnum.Attivita73, "Autotrasportatore senza carico e scarico")
                .Add(TipoAttivitaEnum.Attivita74, "Avvocato")
                .Add(TipoAttivitaEnum.Attivita75, "Baby sitters")
                .Add(TipoAttivitaEnum.Attivita76, "Badante")
                .Add(TipoAttivitaEnum.Attivita77, "Bagnino")
                .Add(TipoAttivitaEnum.Attivita78, "Ballerina/o non professionista")
                .Add(TipoAttivitaEnum.Attivita79, "Ballerina/o professionista")
                .Add(TipoAttivitaEnum.Attivita80, "Bambino in eta prescolare")
                .Add(TipoAttivitaEnum.Attivita81, "Barbiere")
                .Add(TipoAttivitaEnum.Attivita82, "Barcaiolo addetto al trasporto di cose, compreso carico e scarico")
                .Add(TipoAttivitaEnum.Attivita83, "Barcaiolo addetto al trasporto di persone")
                .Add(TipoAttivitaEnum.Attivita84, "Barista")
                .Add(TipoAttivitaEnum.Attivita85, "Benzinaio addetto ai distributori")
                .Add(TipoAttivitaEnum.Attivita86, "Benzinaio addetto raffi nerie")
                .Add(TipoAttivitaEnum.Attivita87, "Bibbliotecario")
                .Add(TipoAttivitaEnum.Attivita88, "Bidello")
                .Add(TipoAttivitaEnum.Attivita89, "Bigliettaio/Controllore di cinema e teatri")
                .Add(TipoAttivitaEnum.Attivita90, "Bigliettaio/Controllore su mezzi di trasporto")
                .Add(TipoAttivitaEnum.Attivita91, "Biologo")
                .Add(TipoAttivitaEnum.Attivita92, "Botanico")
                .Add(TipoAttivitaEnum.Attivita93, "Broker di assicurazione")
                .Add(TipoAttivitaEnum.Attivita94, "Brunitore")
                .Add(TipoAttivitaEnum.Attivita95, "Call center addetto")
                .Add(TipoAttivitaEnum.Attivita96, "Callista")
                .Add(TipoAttivitaEnum.Attivita97, "Calzaturiere")
                .Add(TipoAttivitaEnum.Attivita98, "Calzolaio")
                .Add(TipoAttivitaEnum.Attivita99, "Cameraman anche all esterno")
                .Add(TipoAttivitaEnum.Attivita100, "Cameraman in studio")
                .Add(TipoAttivitaEnum.Attivita101, "Cameriere")
                .Add(TipoAttivitaEnum.Attivita102, "Cancelliere")
                .Add(TipoAttivitaEnum.Attivita103, "Cantante non professionista")
                .Add(TipoAttivitaEnum.Attivita104, "Cantante professionista")
                .Add(TipoAttivitaEnum.Attivita105, "Cantiniere")
                .Add(TipoAttivitaEnum.Attivita106, "Cantoniere")
                .Add(TipoAttivitaEnum.Attivita107, "Capostazione")
                .Add(TipoAttivitaEnum.Attivita108, "Carabiniere")
                .Add(TipoAttivitaEnum.Attivita109, "Carabiniere corpi speciali")
                .Add(TipoAttivitaEnum.Attivita110, "Cardatore")
                .Add(TipoAttivitaEnum.Attivita111, "Carpentiere")
                .Add(TipoAttivitaEnum.Attivita112, "Carrozziere")
                .Add(TipoAttivitaEnum.Attivita113, "Cartaio")
                .Add(TipoAttivitaEnum.Attivita114, "Cartolaio")
                .Add(TipoAttivitaEnum.Attivita115, "Casalinga")
                .Add(TipoAttivitaEnum.Attivita116, "Casaro")
                .Add(TipoAttivitaEnum.Attivita117, "Cassiere")
                .Add(TipoAttivitaEnum.Attivita118, "Centralinista")
                .Add(TipoAttivitaEnum.Attivita119, "Ceramista addetto alla modellatura e cottura")
                .Add(TipoAttivitaEnum.Attivita120, "Ceramista addetto alla sola decorazione")
                .Add(TipoAttivitaEnum.Attivita121, "Certifi catore di bilancio")
                .Add(TipoAttivitaEnum.Attivita122, "Cesellatore")
                .Add(TipoAttivitaEnum.Attivita123, "Cestaio")
                .Add(TipoAttivitaEnum.Attivita124, "Chimico/Analista chimico in laboratorio di analisi compreso il trattamento di materie esplodenti")
                .Add(TipoAttivitaEnum.Attivita125, "Chimico/Analista Chimico in laboratorio di analisi escluso il trattamento di materie esplodenti")
                .Add(TipoAttivitaEnum.Attivita126, "Cineoperatore")
                .Add(TipoAttivitaEnum.Attivita127, "Cocchiere")
                .Add(TipoAttivitaEnum.Attivita128, "Collaudatore di veicoli/velivoli in genere")
                .Add(TipoAttivitaEnum.Attivita129, "Commercialista")
                .Add(TipoAttivitaEnum.Attivita130, "Commesso addetto al trasporto e consegna")
                .Add(TipoAttivitaEnum.Attivita131, "Commesso addetto alla vendita di generi alimentari")
                .Add(TipoAttivitaEnum.Attivita132, "Commesso addetto alla vendita di generi non alimentari")
                .Add(TipoAttivitaEnum.Attivita133, "Commesso viaggiatore")
                .Add(TipoAttivitaEnum.Attivita134, "Concessionario di veicoli")
                .Add(TipoAttivitaEnum.Attivita135, "Conciatore con uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita136, "Conciatore senza uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita137, "Coniatore")
                .Add(TipoAttivitaEnum.Attivita138, "Console in paesi Unione Europea")
                .Add(TipoAttivitaEnum.Attivita139, "Console resto del mondo")
                .Add(TipoAttivitaEnum.Attivita140, "Consulente del lavoro")
                .Add(TipoAttivitaEnum.Attivita141, "Coreografo")
                .Add(TipoAttivitaEnum.Attivita142, "Corista")
                .Add(TipoAttivitaEnum.Attivita143, "Corniciaio con uso di macchine")
                .Add(TipoAttivitaEnum.Attivita144, "Corniciaio senza uso di macchine")
                .Add(TipoAttivitaEnum.Attivita145, "Costumista")
                .Add(TipoAttivitaEnum.Attivita146, "Critico d arte")
                .Add(TipoAttivitaEnum.Attivita147, "Cromatore")
                .Add(TipoAttivitaEnum.Attivita148, "Croupier")
                .Add(TipoAttivitaEnum.Attivita149, "Cuoco")
                .Add(TipoAttivitaEnum.Attivita150, "Custode")
                .Add(TipoAttivitaEnum.Attivita151, "Custode di zoo")
                .Add(TipoAttivitaEnum.Attivita152, "Decoratore all esterno di fabbricati con uso di ponteggi")
                .Add(TipoAttivitaEnum.Attivita153, "Decoratore all interno di fabbricati")
                .Add(TipoAttivitaEnum.Attivita154, "Decoratore in laboratorio")
                .Add(TipoAttivitaEnum.Attivita155, "Demolitore")
                .Add(TipoAttivitaEnum.Attivita156, "Dentista medico")
                .Add(TipoAttivitaEnum.Attivita157, "Diplomatico in paesi Unione Europea")
                .Add(TipoAttivitaEnum.Attivita158, "Diplomatico resto del mondo")
                .Add(TipoAttivitaEnum.Attivita159, "Direttore d orchestra")
                .Add(TipoAttivitaEnum.Attivita160, "Dirigente che accede a laboratori, sale macchine, magazzini, depositi")
                .Add(TipoAttivitaEnum.Attivita161, "Dirigente che partecipa al lavoro manuale e/o con uso di macchine operatrici e/o con accesso a ponteggi e impalcature")
                .Add(TipoAttivitaEnum.Attivita162, "Dirigente con sola attivita amministrativa e direttiva")
                .Add(TipoAttivitaEnum.Attivita163, "Disegnatore occupato anche all esterno")
                .Add(TipoAttivitaEnum.Attivita164, "Disegnatore occupato esclusivamente in uffi cio")
                .Add(TipoAttivitaEnum.Attivita165, "Disinfestatore")
                .Add(TipoAttivitaEnum.Attivita166, "Disk jockey")
                .Add(TipoAttivitaEnum.Attivita167, "Domestica (Colf)")
                .Add(TipoAttivitaEnum.Attivita168, "Doratore")
                .Add(TipoAttivitaEnum.Attivita169, "Droghiere")
                .Add(TipoAttivitaEnum.Attivita170, "Ebanista con uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita171, "Ebanista senza uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita172, "Elettrauto")
                .Add(TipoAttivitaEnum.Attivita173, "Elettricista a contatto con correnti a bassa tensione fi no a 420 volt")
                .Add(TipoAttivitaEnum.Attivita174, "Elettricista a contatto con correnti oltre 420 volt")
                .Add(TipoAttivitaEnum.Attivita175, "Elettrotecnico")
                .Add(TipoAttivitaEnum.Attivita176, "Enologo")
                .Add(TipoAttivitaEnum.Attivita177, "Enotecnico")
                .Add(TipoAttivitaEnum.Attivita178, "Erborista")
                .Add(TipoAttivitaEnum.Attivita179, "Esattore in servizio esterno")
                .Add(TipoAttivitaEnum.Attivita180, "Esattore solo in uffi cio")
                .Add(TipoAttivitaEnum.Attivita181, "Escavatorista")
                .Add(TipoAttivitaEnum.Attivita182, "Estetista")
                .Add(TipoAttivitaEnum.Attivita183, "Fabbro a terra o all interno di fabbricati")
                .Add(TipoAttivitaEnum.Attivita184, "Fabbro in edifi cio in costruzione o su impalcature")
                .Add(TipoAttivitaEnum.Attivita185, "Facchino addetto al carico e scarico di merci")
                .Add(TipoAttivitaEnum.Attivita186, "Facchino di piazza e portabagagli nelle stazioni")
                .Add(TipoAttivitaEnum.Attivita187, "Falegname")
                .Add(TipoAttivitaEnum.Attivita188, "Fantino")
                .Add(TipoAttivitaEnum.Attivita189, "farmacista anche con preparazione di ossigeno")
                .Add(TipoAttivitaEnum.Attivita190, "Farmacista con laboratorio di analisi per la preparazione di medicinali")
                .Add(TipoAttivitaEnum.Attivita191, "Farmacista con sola vendita di medicinali")
                .Add(TipoAttivitaEnum.Attivita192, "Fattorino anche all esterno di uffi ci")
                .Add(TipoAttivitaEnum.Attivita193, "Fattorino solo all interno di uffi ci")
                .Add(TipoAttivitaEnum.Attivita194, "Ferroviere addetto alla biglietteria o altra attivita senza lavoro manuale")
                .Add(TipoAttivitaEnum.Attivita195, "Ferroviere addetto alla manutenzione")
                .Add(TipoAttivitaEnum.Attivita196, "Ferroviere addetto allo smistamento merci")
                .Add(TipoAttivitaEnum.Attivita197, "Ferroviere macchinista")
                .Add(TipoAttivitaEnum.Attivita198, "Fiorista")
                .Add(TipoAttivitaEnum.Attivita199, "Fisioterapista")
                .Add(TipoAttivitaEnum.Attivita200, "Floricoltore")
                .Add(TipoAttivitaEnum.Attivita201, "Fotografo anche all esterno")
                .Add(TipoAttivitaEnum.Attivita202, "Fotografo solo in studio")
                .Add(TipoAttivitaEnum.Attivita203, "Fotomodella/o")
                .Add(TipoAttivitaEnum.Attivita204, "Fotoreporter inviato di guerra")
                .Add(TipoAttivitaEnum.Attivita205, "Fotoreporter non inviato di guerra")
                .Add(TipoAttivitaEnum.Attivita206, "Fresatore")
                .Add(TipoAttivitaEnum.Attivita207, "Fruttivendolo")
                .Add(TipoAttivitaEnum.Attivita208, "Fuochista addetto a caldaie e macchine in genere")
                .Add(TipoAttivitaEnum.Attivita209, "Fuochista addetto ad impianti di riscaldamento")
                .Add(TipoAttivitaEnum.Attivita210, "Gelataio addetto alla sola vendita")
                .Add(TipoAttivitaEnum.Attivita211, "Gelataio con uso di macchine")
                .Add(TipoAttivitaEnum.Attivita212, "Geologo")
                .Add(TipoAttivitaEnum.Attivita213, "Geometra con accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita214, "Geometra senza accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita215, "Gestore cinema, teatro")
                .Add(TipoAttivitaEnum.Attivita216, "Giardiniere con potatura di alberi ad alto fusto")
                .Add(TipoAttivitaEnum.Attivita217, "Giardiniere senza potatura di alberi ad alto fusto")
                .Add(TipoAttivitaEnum.Attivita218, "Gioielliere addetto alla vendita")
                .Add(TipoAttivitaEnum.Attivita219, "Giornalaio")
                .Add(TipoAttivitaEnum.Attivita220, "Giornalista/cronista inviato all estero/speciale di guerra")
                .Add(TipoAttivitaEnum.Attivita221, "Giornalista/cronista non inviato all estero")
                .Add(TipoAttivitaEnum.Attivita222, "Giornalista/cronista occupato solo in ufficio")
                .Add(TipoAttivitaEnum.Attivita223, "Giostraio")
                .Add(TipoAttivitaEnum.Attivita224, "Gommista")
                .Add(TipoAttivitaEnum.Attivita225, "Governante")
                .Add(TipoAttivitaEnum.Attivita226, "Grafi co")
                .Add(TipoAttivitaEnum.Attivita227, "Gruista con manovra a distanza")
                .Add(TipoAttivitaEnum.Attivita228, "Gruista su gru")
                .Add(TipoAttivitaEnum.Attivita229, "Guantaio in lana o pelle (fabbricante)")
                .Add(TipoAttivitaEnum.Attivita230, "Guardia campestre")
                .Add(TipoAttivitaEnum.Attivita231, "Guardia del corpo")
                .Add(TipoAttivitaEnum.Attivita232, "Guardia di fi nanza")
                .Add(TipoAttivitaEnum.Attivita233, "Guardia di fi nanza corpi speciali")
                .Add(TipoAttivitaEnum.Attivita234, "Guardia forestale")
                .Add(TipoAttivitaEnum.Attivita235, "Guardia giurata con trasporto di valori")
                .Add(TipoAttivitaEnum.Attivita236, "Guardia giurata senza trasporto di valori")
                .Add(TipoAttivitaEnum.Attivita237, "Guardia notturna")
                .Add(TipoAttivitaEnum.Attivita238, "Guida alpina")
                .Add(TipoAttivitaEnum.Attivita239, "Guida turistica")
                .Add(TipoAttivitaEnum.Attivita240, "Hostess di terra")
                .Add(TipoAttivitaEnum.Attivita241, "Idraulico occupato anche su tetti, impalcature e in pozzi")
                .Add(TipoAttivitaEnum.Attivita242, "Idraulico occupato solo a terra")
                .Add(TipoAttivitaEnum.Attivita243, "Imbianchino con accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita244, "Imbianchino senza accesso a cantieri, ponteggi, impalcature")
                .Add(TipoAttivitaEnum.Attivita245, "Impagliatore")
                .Add(TipoAttivitaEnum.Attivita246, "Impiegato con partecipazione a lavoro di leggera manualita e/o che accedono a laboratori, sale macchine, magazzini, depositi")
                .Add(TipoAttivitaEnum.Attivita247, "Impiegato con sola attivita amministrativa")
                .Add(TipoAttivitaEnum.Attivita248, "Imprenditore con partecipazione a lavoro di leggera manualita e/o che accedono a laboratori, sale macchine, magazzini, depositi")
                .Add(TipoAttivitaEnum.Attivita249, "Imprenditore con partecipazione al lavoro di pesante manualita con uso di macchine operatrici")
                .Add(TipoAttivitaEnum.Attivita250, "Imprenditore con sola attivita amministrativa e direttiva che puo accedere a laboratori, sale macchine, magazzini, depositi")
                .Add(TipoAttivitaEnum.Attivita251, "Incisore di metalli")
                .Add(TipoAttivitaEnum.Attivita252, "Incisore di ogni altro materiale")
                .Add(TipoAttivitaEnum.Attivita253, "Indossatore/trice")
                .Add(TipoAttivitaEnum.Attivita254, "Infermiere")
                .Add(TipoAttivitaEnum.Attivita255, "Ingegnere che accede a cantieri")
                .Add(TipoAttivitaEnum.Attivita256, "Ingegnere che non accede a cantieri")
                .Add(TipoAttivitaEnum.Attivita257, "Insegnante di ballo")
                .Add(TipoAttivitaEnum.Attivita258, "Insegnante di educazione fi sica")
                .Add(TipoAttivitaEnum.Attivita259, "Insegnante di materie professionali con prove di laboratorio")
                .Add(TipoAttivitaEnum.Attivita260, "Insegnante di materie professionali senza prove di laboratorio")
                .Add(TipoAttivitaEnum.Attivita261, "Intarsiatore")
                .Add(TipoAttivitaEnum.Attivita262, "Interprete")
                .Add(TipoAttivitaEnum.Attivita263, "Investigatore/Detective privato")
                .Add(TipoAttivitaEnum.Attivita264, "Istruttore di scuola guida")
                .Add(TipoAttivitaEnum.Attivita265, "Istruttore sportivo")
                .Add(TipoAttivitaEnum.Attivita266, "Lattaio")
                .Add(TipoAttivitaEnum.Attivita267, "Lattoniere anche su impalcature e tetti")
                .Add(TipoAttivitaEnum.Attivita268, "Lattoniere solo a terra")
                .Add(TipoAttivitaEnum.Attivita269, "Lavandiere")
                .Add(TipoAttivitaEnum.Attivita270, "Lavoratore forestale")
                .Add(TipoAttivitaEnum.Attivita271, "Levigatore di pavimenti")
                .Add(TipoAttivitaEnum.Attivita272, "Libraio")
                .Add(TipoAttivitaEnum.Attivita273, "Linotipista")
                .Add(TipoAttivitaEnum.Attivita274, "Litografo")
                .Add(TipoAttivitaEnum.Attivita275, "Logopedista")
                .Add(TipoAttivitaEnum.Attivita276, "Logoterapista")
                .Add(TipoAttivitaEnum.Attivita277, "Macellaio con macellazione")
                .Add(TipoAttivitaEnum.Attivita278, "Macellaio senza macellazione")
                .Add(TipoAttivitaEnum.Attivita279, "Magazziniere con lavori manuali pesanti")
                .Add(TipoAttivitaEnum.Attivita280, "Magazziniere/Addetto Vendita con lavori manuali leggeri")
                .Add(TipoAttivitaEnum.Attivita281, "Magistrato")
                .Add(TipoAttivitaEnum.Attivita282, "Magliaia con uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita283, "Magliaia senza uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita284, "Manicure")
                .Add(TipoAttivitaEnum.Attivita285, "Maniscalco")
                .Add(TipoAttivitaEnum.Attivita286, "Marina militare")
                .Add(TipoAttivitaEnum.Attivita287, "Marina militare corpi speciali")
                .Add(TipoAttivitaEnum.Attivita288, "Marinaio")
                .Add(TipoAttivitaEnum.Attivita289, "Marmista che lavora in cave con uso di mine")
                .Add(TipoAttivitaEnum.Attivita290, "Marmista con uso di macchine o su ponti e impalcature")
                .Add(TipoAttivitaEnum.Attivita291, "Marmista occupato in laboratorio senza uso di macchine o levigatori solo a terra")
                .Add(TipoAttivitaEnum.Attivita292, "Massaggiatore")
                .Add(TipoAttivitaEnum.Attivita293, "Meccanico")
                .Add(TipoAttivitaEnum.Attivita294, "Meccanico di biciclette e motocicli")
                .Add(TipoAttivitaEnum.Attivita295, "Medico")
                .Add(TipoAttivitaEnum.Attivita296, "Merciaia")
                .Add(TipoAttivitaEnum.Attivita297, "Metereologo")
                .Add(TipoAttivitaEnum.Attivita298, "Militare (in servizio permanente effettivo)")
                .Add(TipoAttivitaEnum.Attivita299, "Militare (in servizio permanente effettivo) corpi speciali")
                .Add(TipoAttivitaEnum.Attivita300, "Minatore")
                .Add(TipoAttivitaEnum.Attivita301, "Ministro del culto")
                .Add(TipoAttivitaEnum.Attivita302, "Mobiliere addetto alla fabbricazione")
                .Add(TipoAttivitaEnum.Attivita303, "Mobiliere addetto alla vendita")
                .Add(TipoAttivitaEnum.Attivita304, "Modella/o")
                .Add(TipoAttivitaEnum.Attivita305, "Modellista in carta/cartone")
                .Add(TipoAttivitaEnum.Attivita306, "Modellista in ferro e legno")
                .Add(TipoAttivitaEnum.Attivita307, "Modista")
                .Add(TipoAttivitaEnum.Attivita308, "Motorista")
                .Add(TipoAttivitaEnum.Attivita309, "Mugnaio")
                .Add(TipoAttivitaEnum.Attivita310, "Muratore")
                .Add(TipoAttivitaEnum.Attivita311, "Musicista")
                .Add(TipoAttivitaEnum.Attivita312, "Negoziante abbigliamento, confezioni, tessuti")
                .Add(TipoAttivitaEnum.Attivita313, "Negoziante casalinghi")
                .Add(TipoAttivitaEnum.Attivita314, "Negoziante che attende alla vendita di biciclette")
                .Add(TipoAttivitaEnum.Attivita315, "Negoziante dischi, musica, strumenti musicali, audiovisivi")
                .Add(TipoAttivitaEnum.Attivita316, "Negoziante ferramenta, colori, vernici")
                .Add(TipoAttivitaEnum.Attivita317, "Negoziante giocattoli, articoli sportivi")
                .Add(TipoAttivitaEnum.Attivita318, "Negoziante profumerie")
                .Add(TipoAttivitaEnum.Attivita319, "Negoziante supermarket, minimarket, bazar")
                .Add(TipoAttivitaEnum.Attivita320, "Netturbino")
                .Add(TipoAttivitaEnum.Attivita321, "Nichelatore")
                .Add(TipoAttivitaEnum.Attivita322, "Notaio")
                .Add(TipoAttivitaEnum.Attivita323, "Odontoiatra")
                .Add(TipoAttivitaEnum.Attivita324, "Odontotecnico")
                .Add(TipoAttivitaEnum.Attivita325, "Operaio")
                .Add(TipoAttivitaEnum.Attivita326, "Operatore turistico")
                .Add(TipoAttivitaEnum.Attivita327, "Orafo")
                .Add(TipoAttivitaEnum.Attivita328, "Orefi ce")
                .Add(TipoAttivitaEnum.Attivita329, "Orologiaio")
                .Add(TipoAttivitaEnum.Attivita330, "Ortopedico con uso di macchine")
                .Add(TipoAttivitaEnum.Attivita331, "Ortopedico senza uso di macchine")
                .Add(TipoAttivitaEnum.Attivita332, "Oste")
                .Add(TipoAttivitaEnum.Attivita333, "Ostetrica")
                .Add(TipoAttivitaEnum.Attivita334, "Ottico addetto alla riparazione")
                .Add(TipoAttivitaEnum.Attivita335, "Ottico addetto alla vendita")
                .Add(TipoAttivitaEnum.Attivita336, "Palombaro")
                .Add(TipoAttivitaEnum.Attivita337, "Panettiere addetto alla preparazione del pane")
                .Add(TipoAttivitaEnum.Attivita338, "Panettiere addetto alla vendita")
                .Add(TipoAttivitaEnum.Attivita339, "Parcheggiatore")
                .Add(TipoAttivitaEnum.Attivita340, "Parroco")
                .Add(TipoAttivitaEnum.Attivita341, "Parrucchiere")
                .Add(TipoAttivitaEnum.Attivita342, "Pastaio con uso di macchine")
                .Add(TipoAttivitaEnum.Attivita343, "Pastaio senza uso di macchine")
                .Add(TipoAttivitaEnum.Attivita344, "Pasticcere con uso di macchine")
                .Add(TipoAttivitaEnum.Attivita345, "Pasticcere senza uso di macchine")
                .Add(TipoAttivitaEnum.Attivita346, "Pastore")
                .Add(TipoAttivitaEnum.Attivita347, "Pavimentatore")
                .Add(TipoAttivitaEnum.Attivita348, "Pedicure")
                .Add(TipoAttivitaEnum.Attivita349, "Pellettiere")
                .Add(TipoAttivitaEnum.Attivita350, "Pellicciaio")
                .Add(TipoAttivitaEnum.Attivita351, "Pensionato")
                .Add(TipoAttivitaEnum.Attivita352, "Perito")
                .Add(TipoAttivitaEnum.Attivita353, "Persona senza occupazione professionale")
                .Add(TipoAttivitaEnum.Attivita354, "Personale che lavora in galleria")
                .Add(TipoAttivitaEnum.Attivita355, "Personale di bordo di mezzi aerei")
                .Add(TipoAttivitaEnum.Attivita356, "Personale di circhi equestri ed artisti acrobati")
                .Add(TipoAttivitaEnum.Attivita357, "Pescatore su laghi e fi umi")
                .Add(TipoAttivitaEnum.Attivita358, "Pescatore su mari")
                .Add(TipoAttivitaEnum.Attivita359, "Pescivendolo")
                .Add(TipoAttivitaEnum.Attivita360, "Phone center addetto")
                .Add(TipoAttivitaEnum.Attivita361, "Piastrellista")
                .Add(TipoAttivitaEnum.Attivita362, "Piazzista")
                .Add(TipoAttivitaEnum.Attivita363, "Pilota aerei")
                .Add(TipoAttivitaEnum.Attivita364, "Pirotecnico")
                .Add(TipoAttivitaEnum.Attivita365, "Pittore anche su impalcature e ponti")
                .Add(TipoAttivitaEnum.Attivita366, "Pittore solo a terra")
                .Add(TipoAttivitaEnum.Attivita367, "Pizzaiolo")
                .Add(TipoAttivitaEnum.Attivita368, "Podologo")
                .Add(TipoAttivitaEnum.Attivita369, "Politico titolare di carica istituzionale pubblica nazionale")
                .Add(TipoAttivitaEnum.Attivita370, "Politico/Amministratore pubblico titolare di carica istituzionale territoriale")
                .Add(TipoAttivitaEnum.Attivita371, "Pony express")
                .Add(TipoAttivitaEnum.Attivita372, "Portavalori")
                .Add(TipoAttivitaEnum.Attivita373, "Portiere di stabili")
                .Add(TipoAttivitaEnum.Attivita374, "Posatore di parquet")
                .Add(TipoAttivitaEnum.Attivita375, "Postino")
                .Add(TipoAttivitaEnum.Attivita376, "Potatore di alberi di piante alto fusto")
                .Add(TipoAttivitaEnum.Attivita377, "Potatore di alberi di piante basso fusto")
                .Add(TipoAttivitaEnum.Attivita378, "Pranoterapista")
                .Add(TipoAttivitaEnum.Attivita379, "Presentatore")
                .Add(TipoAttivitaEnum.Attivita380, "Preside")
                .Add(TipoAttivitaEnum.Attivita381, "Procacciatore d affari")
                .Add(TipoAttivitaEnum.Attivita382, "Procuratore legale")
                .Add(TipoAttivitaEnum.Attivita383, "Professore universitario")
                .Add(TipoAttivitaEnum.Attivita384, "Programmatore")
                .Add(TipoAttivitaEnum.Attivita385, "Promoter")
                .Add(TipoAttivitaEnum.Attivita386, "Promotore Finanziario")
                .Add(TipoAttivitaEnum.Attivita387, "Provveditore agli studi")
                .Add(TipoAttivitaEnum.Attivita388, "Psicanalista")
                .Add(TipoAttivitaEnum.Attivita389, "Psichiatra")
                .Add(TipoAttivitaEnum.Attivita390, "Psicologo")
                .Add(TipoAttivitaEnum.Attivita391, "Pubblicista")
                .Add(TipoAttivitaEnum.Attivita392, "Pubblicitario")
                .Add(TipoAttivitaEnum.Attivita393, "Quadro/Funzionario che accede a laboratori, sale macchine, magazzini, depositi")
                .Add(TipoAttivitaEnum.Attivita394, "Quadro/Funzionario che partecipa al lavoro manuale e/o con uso di macchine operatrici e/o con accesso a ponteggi e impalcature")
                .Add(TipoAttivitaEnum.Attivita395, "Quadro/Funzionario con sola attivita amministrativa e direttiva")
                .Add(TipoAttivitaEnum.Attivita396, "Questore")
                .Add(TipoAttivitaEnum.Attivita397, "Radiologo")
                .Add(TipoAttivitaEnum.Attivita398, "Radiotecnico con installazione di antenne")
                .Add(TipoAttivitaEnum.Attivita399, "Radiotecnico senza installazione di antenne")
                .Add(TipoAttivitaEnum.Attivita400, "Rappresentante che non provvede alla consegna di prodotti")
                .Add(TipoAttivitaEnum.Attivita401, "Rappresentante che provvede anche alla consegna di prodotti")
                .Add(TipoAttivitaEnum.Attivita402, "Regista")
                .Add(TipoAttivitaEnum.Attivita403, "Restauratore solo a terra")
                .Add(TipoAttivitaEnum.Attivita404, "Restauratore su ponti e impalcature")
                .Add(TipoAttivitaEnum.Attivita405, "Revisore dei conti")
                .Add(TipoAttivitaEnum.Attivita406, "Ricamatrice")
                .Add(TipoAttivitaEnum.Attivita407, "Ricercatore Scientifi co")
                .Add(TipoAttivitaEnum.Attivita408, "Rigattiere")
                .Add(TipoAttivitaEnum.Attivita409, "Rilegatore con uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita410, "Rilegatore senza uso di macchine a motore")
                .Add(TipoAttivitaEnum.Attivita411, "Riparatore di elettrodomestici")
                .Add(TipoAttivitaEnum.Attivita412, "Riparatore di macchine per uffi cio, computer")
                .Add(TipoAttivitaEnum.Attivita413, "Ristoratore")
                .Add(TipoAttivitaEnum.Attivita414, "Rosticciere")
                .Add(TipoAttivitaEnum.Attivita415, "Sacerdote")
                .Add(TipoAttivitaEnum.Attivita416, "Sagrestano")
                .Add(TipoAttivitaEnum.Attivita417, "Saldatore")
                .Add(TipoAttivitaEnum.Attivita418, "Salumiere")
                .Add(TipoAttivitaEnum.Attivita419, "Sarto")
                .Add(TipoAttivitaEnum.Attivita420, "Scalpellino anche su ponti e impalcature")
                .Add(TipoAttivitaEnum.Attivita421, "Scalpellino solo a terra")
                .Add(TipoAttivitaEnum.Attivita422, "Sceneggiatore")
                .Add(TipoAttivitaEnum.Attivita423, "Scrittore")
                .Add(TipoAttivitaEnum.Attivita424, "Scultore anche su impalcature e ponti")
                .Add(TipoAttivitaEnum.Attivita425, "Scultore solo a terra")
                .Add(TipoAttivitaEnum.Attivita426, "Segretario nella pubblica amministrazione")
                .Add(TipoAttivitaEnum.Attivita427, "Sindaco")
                .Add(TipoAttivitaEnum.Attivita428, "Skipper")
                .Add(TipoAttivitaEnum.Attivita429, "Smaltatore")
                .Add(TipoAttivitaEnum.Attivita430, "Sommozzatore")
                .Add(TipoAttivitaEnum.Attivita431, "Spedizioniere che accede agli ambienti di lavoro senza partecipazione manuale")
                .Add(TipoAttivitaEnum.Attivita432, "Spedizioniere che effettua anche carico e scarico")
                .Add(TipoAttivitaEnum.Attivita433, "Speleologo")
                .Add(TipoAttivitaEnum.Attivita434, "Stagnino anche su impalcature")
                .Add(TipoAttivitaEnum.Attivita435, "Stagnino solo a terra")
                .Add(TipoAttivitaEnum.Attivita436, "Stalliere")
                .Add(TipoAttivitaEnum.Attivita437, "Stilista")
                .Add(TipoAttivitaEnum.Attivita438, "Stiratrice")
                .Add(TipoAttivitaEnum.Attivita439, "Stradino")
                .Add(TipoAttivitaEnum.Attivita440, "Studente")
                .Add(TipoAttivitaEnum.Attivita441, "Stuntman")
                .Add(TipoAttivitaEnum.Attivita442, "Suora")
                .Add(TipoAttivitaEnum.Attivita443, "Tabaccaio")
                .Add(TipoAttivitaEnum.Attivita444, "Tagliapietre con accesso a cave e/o che lavorano su ponti e impalcature")
                .Add(TipoAttivitaEnum.Attivita445, "Tagliapietre solo a terra")
                .Add(TipoAttivitaEnum.Attivita446, "Tappezziere con posa in opera; con uso di impalcature")
                .Add(TipoAttivitaEnum.Attivita447, "Tappezziere in laboratorio; senza uso di impalcature")
                .Add(TipoAttivitaEnum.Attivita448, "Tassista")
                .Add(TipoAttivitaEnum.Attivita449, "Tecnico di Laboratorio")
                .Add(TipoAttivitaEnum.Attivita450, "Tintore")
                .Add(TipoAttivitaEnum.Attivita451, "Tipografo")
                .Add(TipoAttivitaEnum.Attivita452, "Tirocinante presso le A.S.L.")
                .Add(TipoAttivitaEnum.Attivita453, "Toelettatura per animali")
                .Add(TipoAttivitaEnum.Attivita454, "Tornitore")
                .Add(TipoAttivitaEnum.Attivita455, "Traduttore")
                .Add(TipoAttivitaEnum.Attivita456, "Tranviere")
                .Add(TipoAttivitaEnum.Attivita457, "Truccatore")
                .Add(TipoAttivitaEnum.Attivita458, "Uffi ciale giudiziario")
                .Add(TipoAttivitaEnum.Attivita459, "Usciere")
                .Add(TipoAttivitaEnum.Attivita460, "Valigiaio")
                .Add(TipoAttivitaEnum.Attivita461, "Venditore ambulante")
                .Add(TipoAttivitaEnum.Attivita462, "Verniciatore all esterno di navi")
                .Add(TipoAttivitaEnum.Attivita463, "Verniciatore solo a terra e all interno di fabbricati")
                .Add(TipoAttivitaEnum.Attivita464, "Verniciatore su ponti e impalcature")
                .Add(TipoAttivitaEnum.Attivita465, "Veterinario")
                .Add(TipoAttivitaEnum.Attivita466, "Vetraio anche su impalcature e ponti")
                .Add(TipoAttivitaEnum.Attivita467, "Vetraio solo a terra")
                .Add(TipoAttivitaEnum.Attivita468, "Vetrinista")
                .Add(TipoAttivitaEnum.Attivita469, "Vigilantes con trasporto di valori")
                .Add(TipoAttivitaEnum.Attivita470, "Vigilantes senza trasporto di valori")
                .Add(TipoAttivitaEnum.Attivita471, "Vigile del fuoco")
                .Add(TipoAttivitaEnum.Attivita472, "Vigile del fuoco corpi speciali")
                .Add(TipoAttivitaEnum.Attivita473, "Vigile urbano motociclisti")
                .Add(TipoAttivitaEnum.Attivita474, "Vigile urbano non motociclisti")
                .Add(TipoAttivitaEnum.Attivita475, "Vulcanizzatore")
                .Add(TipoAttivitaEnum.Attivita476, "Xilografo")
                .Add(TipoAttivitaEnum.Attivita477, "Zincografo")
                .Add(TipoAttivitaEnum.Attivita478, "Zoologo")
                .Add(TipoAttivitaEnum.Attivita999, "Attitività non trovata")
            End With
            With DecodePersonaRenditaVitaliziaMassimale
                .Add(15000D, "€ 15.000")
                .Add(30000D, "€ 30.000")
            End With
            With DecodePersonaFranchigiaRelativaFranchigia
                .Add(10D, "Franchigia 10%")
                .Add(30D, "Franchigia 30%")
            End With
            With DecodeAttivitaToRischioProfessionale
                .Add(TipoAttivitaEnum.Attivita0, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita1, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita2, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita3, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita4, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita5, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita6, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita7, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita8, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita9, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita10, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita11, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita12, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita13, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita14, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita15, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita16, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita17, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita18, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita19, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita20, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita21, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita22, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita23, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita24, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita25, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita26, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita27, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita28, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita29, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita30, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita31, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita32, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita33, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita34, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita35, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita36, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita37, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita38, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita39, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita40, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita41, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita42, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita43, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita44, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita45, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita46, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita47, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita48, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita49, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita50, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita51, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita52, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita53, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita54, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita55, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita56, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita57, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita58, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita59, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita60, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita61, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita62, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita63, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita64, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita65, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita66, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita67, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita68, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita69, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita70, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita71, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita72, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita73, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita74, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita75, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita76, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita77, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita78, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita79, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita80, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita81, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita82, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita83, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita84, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita85, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita86, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita87, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita88, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita89, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita90, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita91, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita92, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita93, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita94, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita95, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita96, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita97, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita98, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita99, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita100, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita101, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita102, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita103, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita104, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita105, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita106, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita107, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita108, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita109, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita110, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita111, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita112, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita113, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita114, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita115, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita116, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita117, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita118, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita119, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita120, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita121, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita122, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita123, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita124, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita125, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita126, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita127, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita128, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita129, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita130, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita131, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita132, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita133, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita134, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita135, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita136, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita137, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita138, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita139, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita140, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita141, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita142, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita143, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita144, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita145, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita146, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita147, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita148, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita149, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita150, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita151, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita152, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita153, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita154, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita155, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita156, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita157, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita158, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita159, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita160, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita161, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita162, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita163, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita164, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita165, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita166, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita167, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita168, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita169, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita170, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita171, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita172, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita173, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita174, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita175, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita176, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita177, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita178, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita179, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita180, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita181, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita182, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita183, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita184, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita185, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita186, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita187, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita188, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita189, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita190, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita191, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita192, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita193, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita194, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita195, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita196, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita197, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita198, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita199, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita200, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita201, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita202, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita203, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita204, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita205, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita206, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita207, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita208, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita209, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita210, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita211, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita212, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita213, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita214, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita215, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita216, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita217, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita218, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita219, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita220, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita221, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita222, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita223, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita224, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita225, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita226, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita227, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita228, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita229, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita230, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita231, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita232, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita233, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita234, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita235, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita236, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita237, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita238, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita239, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita240, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita241, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita242, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita243, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita244, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita245, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita246, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita247, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita248, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita249, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita250, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita251, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita252, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita253, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita254, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita255, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita256, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita257, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita258, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita259, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita260, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita261, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita262, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita263, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita264, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita265, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita266, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita267, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita268, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita269, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita270, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita271, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita272, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita273, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita274, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita275, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita276, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita277, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita278, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita279, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita280, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita281, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita282, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita283, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita284, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita285, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita286, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita287, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita288, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita289, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita290, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita291, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita292, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita293, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita294, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita295, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita296, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita297, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita298, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita299, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita300, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita301, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita302, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita303, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita304, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita305, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita306, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita307, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita308, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita309, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita310, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita311, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita312, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita313, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita314, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita315, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita316, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita317, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita318, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita319, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita320, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita321, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita322, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita323, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita324, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita325, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita326, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita327, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita328, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita329, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita330, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita331, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita332, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita333, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita334, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita335, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita336, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita337, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita338, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita339, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita340, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita341, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita342, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita343, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita344, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita345, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita346, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita347, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita348, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita349, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita350, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita351, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita352, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita353, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita354, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita355, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita356, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita357, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita358, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita359, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita360, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita361, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita362, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita363, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita364, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita365, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita366, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita367, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita368, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita369, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita370, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita371, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita372, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita373, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita374, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita375, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita376, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita377, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita378, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita379, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita380, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita381, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita382, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita383, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita384, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita385, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita386, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita387, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita388, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita389, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita390, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita391, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita392, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita393, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita394, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita395, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita396, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita397, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita398, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita399, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita400, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita401, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita402, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita403, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita404, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita405, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita406, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita407, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita408, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita409, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita410, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita411, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita412, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita413, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita414, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita415, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita416, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita417, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita418, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita419, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita420, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita421, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita422, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita423, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita424, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita425, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita426, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita427, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita428, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita429, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita430, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita431, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita432, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita433, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita434, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita435, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita436, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita437, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita438, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita439, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita440, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita441, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita442, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita443, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita444, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita445, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita446, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita447, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita448, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita449, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita450, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita451, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita452, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita453, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita454, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita455, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita456, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita457, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita458, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita459, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita460, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita461, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita462, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita463, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita464, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita465, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita466, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita467, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita468, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita469, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita470, RischioProfessionaleEnum.ClasseD)
                .Add(TipoAttivitaEnum.Attivita471, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita472, RischioProfessionaleEnum.ClasseRD)
                .Add(TipoAttivitaEnum.Attivita473, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita474, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita475, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita476, RischioProfessionaleEnum.ClasseA)
                .Add(TipoAttivitaEnum.Attivita477, RischioProfessionaleEnum.ClasseC)
                .Add(TipoAttivitaEnum.Attivita478, RischioProfessionaleEnum.ClasseB)
                .Add(TipoAttivitaEnum.Attivita999, RischioProfessionaleEnum.ClasseRD)
            End With
        End Sub
    End Class
End Namespace
