Namespace P04226
    Public Class P04226DE
        Inherits P00000DE

        Public DecodeClasseFabbricato As New Dictionary(Of Integer, String)
        Public DecodeFabbricatoDestinazione As New Dictionary(Of Integer, String)
        Public DecodeZonaTerritorialeFurto As New Dictionary(Of Integer, String)
        Public DecodeZonaTerritorialeEventiAtmosferici As New Dictionary(Of Integer, String)
        Public DecodeClasseRischioAttivitaFurto As New Dictionary(Of Integer, String)
        Public DecodeIncendioScelta As New Dictionary(Of Integer, String)
        Public DecodeIncendioEventiAtmosfericiScelta As New Dictionary(Of Integer, String)
        Public DecodeIncendioDanniElettriciScelta As New Dictionary(Of Integer, String)
        Public DecodeIncendioDanniIndirettiScelta As New Dictionary(Of Integer, String)
        Public DecodeClasseMerceologica As New Dictionary(Of Integer, String)
        Public DecodeFurtoFissiScelta As New Dictionary(Of Integer, String)
        Public DecodeFurtoValoriScelta As New Dictionary(Of Integer, String)
        Public DecodeFurtoRapinaScelta As New Dictionary(Of Integer, String)
        Public DecodeIncendioConduttureMassimale As New Dictionary(Of Decimal, String)
        Public DecodeIncendioDemolizioneMassimale As New Dictionary(Of Decimal, String)
        Public DecodeIncendioFranchigiaFranchigia As New Dictionary(Of Decimal, String)
        Public DecodeResponsabilitaCivileRctMassimale As New Dictionary(Of Decimal, String)
        Public DecodeResponsabilitaCivileRcoMassimale As New Dictionary(Of Decimal, String)
        Public DecodeRCSoloProprietaMassimale As New Dictionary(Of Decimal, String)
        Public DecodeRCFranchigiaFranchigia As New Dictionary(Of Decimal, String)
        Public DecodeTutelaLegaleBaseMassimale As New Dictionary(Of Decimal, String)
        Public DecodeProvinciaToZonaTerritorialeFurto As New Dictionary(Of Integer, Integer)
        Public DecodeProvinciaToEventiAtmosferici As New Dictionary(Of Integer, Integer)
        Public DecodeFormaDiAssicurazione As New Dictionary(Of Integer, String)

        Public DecodeAttivita As New Dictionary(Of Integer, String)
        Public DecodeAttivitaToClasseRischioAttivitaIncendio As New Dictionary(Of Integer, Integer)
        Public DecodeAttivitaToClasseRischioAttivitaFurto As New Dictionary(Of Integer, Integer)
        Public DecodeAttivitaToClasseRischioAttivitaRc As New Dictionary(Of Integer, Integer)
        Public DecodeAttivitaToClasseRischioAttivitaTerremoto As New Dictionary(Of Integer, Integer)

        Public DecodeTipologiaFabbricato As New Dizionario(Of Integer, String)
        Public DecodeCaratteristicaCostruttiva As New Dizionario(Of Integer, String)
        Public DecodeTerremotoBaseLimite As New Dizionario(Of Decimal, String)
        Public DecodeTerremotoDemolizioneMassimale As New Dizionario(Of Decimal, String)

        Sub New()
            With DecodeFormaDiAssicurazione
                .Add(FormaDiAssicurazione.ValoreInteroNuovo, "Valore intero e a nuovo")
                .Add(FormaDiAssicurazione.ValoreInteroStatoUso, "Valore intero e allo stato d'uso")
            End With

            With DecodeFrazionamenti
                .Add(FrazionamentiEnum.Annuale, "Annuale")
                .Add(FrazionamentiEnum.Semestrale, "Semestrale")
                .Add(FrazionamentiEnum.Quadrimestrale, "Quadrimestrale")
                .Add(FrazionamentiEnum.Trimestrale, "Trimestrale")
                .Add(FrazionamentiEnum.Temporaneo, "Temporaneo")
                .Add(FrazionamentiEnum.UnicoAnticipato, "Unico Anticipato")
            End With

            With DecodeSezione
                .Add(TipoSezione.Incendio, "Incendio")
                .Add(TipoSezione.Furto, "Furto")
                .Add(TipoSezione.Terremoto, "Terremoto")
                .Add(TipoSezione.ResponsabilitaCivile, "Responsabilità Civile")
                .Add(TipoSezione.TutelaLegale, "Tutela Legale")
                .Add(TipoSezione.Assistenza, "Assistenza")
            End With

            With DecodePartita
                .Add(TipoPartita.Incendio, "Incendio")
                .Add(TipoPartita.Furto, "Furto")
                .Add(TipoPartita.Terremoto, "Terremoto")
                .Add(TipoPartita.ResponsabilitaCivile, "Responsabilità Civile")
                .Add(TipoPartita.TutelaLegale, "Tutela Legale")
                .Add(TipoPartita.Assistenza, "Assistenza")
            End With

            With DecodeGaranzia
                .Add(TipoGaranzia.IncendioBase, "Garanzia base")
                .Add(TipoGaranzia.IncendioFabbricato, "Fabbricato")
                .Add(TipoGaranzia.IncendioContenuto, "Contenuto")
                .Add(TipoGaranzia.IncendioLocazione, "Locali in locazione")
                .Add(TipoGaranzia.IncendioCondutture, "Spese di ricerca rottura e riparazione di condutture di acqua")
                .Add(TipoGaranzia.IncendioDemolizione, "Spese di demolizione, sgombero, trasporto, rimozione e ricollocamento")
                .Add(TipoGaranzia.IncendioEventiAtmosferici, "Eventi Atmosferici")
                .Add(TipoGaranzia.IncendioDanniElettrici, "Danni Elettrici")
                .Add(TipoGaranzia.IncendioDanniIndirettiA, "Danni Indiretti basic")
                .Add(TipoGaranzia.IncendioDanniIndirettiB, "Danni Indiretti maggiori costi")
                .Add(TipoGaranzia.IncendioRicorsoTerzi, "Ricorso terzi")
                .Add(TipoGaranzia.IncendioAumentoMerci, "Aumento periodico merci assicurate")
                .Add(TipoGaranzia.IncendioCoseTrasportate, "Merci ed Attrezzature trasportate")
                .Add(TipoGaranzia.IncendioRefrigerati1, "Danni a merci in refrigerazione")
                .Add(TipoGaranzia.IncendioRefrigerati2, "Danni a merci in refrigerazione (con impianto di allarme)")
                .Add(TipoGaranzia.IncendioLastre, "Lastre")
                .Add(TipoGaranzia.IncendioPannelliSolari, "Pannelli fotovoltaici e solari termici")
                .Add(TipoGaranzia.IncendioRicetteMediche, "Ricette mediche")
                .Add(TipoGaranzia.IncendioSpeseAccessorie, "Spese accessorie")
                .Add(TipoGaranzia.IncendioGrandineFragili, "Grandine su fragili")
                .Add(TipoGaranzia.IncendioAttiVandaliciDolosi, "Atti vandalici e dolosi")
                .Add(TipoGaranzia.IncendioFabbricatiAperti1, "Fabbricati aperti e enti all’aperto (esclusi veicoli)")
                .Add(TipoGaranzia.IncendioFabbricatiAperti2, "Fabbricati aperti e enti all’aperto (compresi veicoli costituenti merci)")
                .Add(TipoGaranzia.IncendioPreziosi, "Valori, Preziosi e Oggetti d’arte")
                .Add(TipoGaranzia.IncendioSistemiProtezione, "Danni Elettrici - Sistemi di protezione")
                .Add(TipoGaranzia.IncendioCommercioAmbulante, "Commercio Ambulante")
                .Add(TipoGaranzia.IncendioFranchigia, "Franchigia assoluta")
                .Add(TipoGaranzia.FurtoBase, "Garanzia base")
                .Add(TipoGaranzia.FurtoContenuto, "Furto contenuto")
                .Add(TipoGaranzia.FurtoFissi, "Furto di fissi e infissi")
                .Add(TipoGaranzia.FurtoValori, "Furto Valori")
                .Add(TipoGaranzia.FurtoRapina, "Rapina nei locali")
                .Add(TipoGaranzia.FurtoVetrinette, "Furto Vetrinette esterne")
                .Add(TipoGaranzia.FurtoPortavalori, "Furto Portavalori")
                .Add(TipoGaranzia.FurtoAumentoMerci, "Aumento periodico Merci assicurate")
                .Add(TipoGaranzia.FurtoMerciTrasportate, "Furto di Merci trasportate")
                .Add(TipoGaranzia.FurtoMerciAperto, "Furto di Merci all’aperto")
                .Add(TipoGaranzia.FurtoDistributoriEsterni, "Distributori esterni di Merci inerenti l’attività esercitata")
                .Add(TipoGaranzia.FurtoDistributoriCarburante, "Distributori di carburante (Furto Valori)")
                .Add(TipoGaranzia.FurtoRicetteMediche, "Ricette mediche")
                .Add(TipoGaranzia.FurtoDipendenti, "Infedeltà dei dipendenti")
                .Add(TipoGaranzia.FurtoSpeseAccessorie, "Spese accessorie")
                .Add(TipoGaranzia.FurtoSpeseMiglioramento, "Rimborso spese per miglioramento dei sistemi di prevenzione e/o protezione")
                .Add(TipoGaranzia.FurtoSlotMachine, "Slot machine, gettoniere, cambiamonete e relativi contenuti")
                .Add(TipoGaranzia.FurtoReintegroAutomatico, "Reintegro automatico")
                .Add(TipoGaranzia.FurtoCommercioAmbulante, "Commercio ambulante")
                .Add(TipoGaranzia.FurtoDepositoRiserva, "Deposito di riserva")
                .Add(TipoGaranzia.FurtoDerogaCostruttive, "Deroga alle caratteristiche costruttive")
                .Add(TipoGaranzia.FurtoMezziChiusura, "Mezzi di Chiusura Particolari")
                .Add(TipoGaranzia.FurtoImpiantoAllarme, "Impianto di allarme")
                .Add(TipoGaranzia.FurtoAllarmeDistanza, "Impianto d’allarme antifurto con registratore e trasmissione a distanza di eventi")
                .Add(TipoGaranzia.FurtoAllarmeDoppio, "Impianto d’allarme antifurto con doppio livello di protezione")
                .Add(TipoGaranzia.FurtoVideoSorveglianza, "Impianto d’allarme antifurto con video-sorveglianza")
                .Add(TipoGaranzia.FurtoScopertoMerciA, "Abrogazione dello Scoperto per Merci di classe A1 e A2")
                .Add(TipoGaranzia.FurtoScopertoMerciB, "Inserimento dello Scoperto per Merci di classe B1-B2-C1-C2-D1-D2")
                .Add(TipoGaranzia.FurtoPiuEsercizi, "Pluralità Esercizi assicurati")
                .Add(TipoGaranzia.ResponsabilitaCivileBase, "Garanzia base")
                .Add(TipoGaranzia.ResponsabilitaCivileRct, "Responsabilità Civile verso Terzi")
                .Add(TipoGaranzia.ResponsabilitaCivileRco, "RC verso prestatori di lavoro - R.C.O./R.C.I.")
                .Add(TipoGaranzia.RCLavoratoriProgetto, "Lavoratori a progetto (Legge Biagi)")
                .Add(TipoGaranzia.RCRicorsoTerzi, "Ricorso terzi da incendio")
                .Add(TipoGaranzia.RCDanniCoseClienti, "Danni a cose portate dai clienti")
                .Add(TipoGaranzia.RCDanniVeicoliTerzi, "Autoveicoli e motoveicoli di terzi")
                .Add(TipoGaranzia.RCDanniFurto, "Danni da furto")
                .Add(TipoGaranzia.RCDanniCoseLavorate, "Danni a cose oggetto di lavorazione")
                .Add(TipoGaranzia.RCDanniCoseMovimentate, "Danni alle cose movimentate")
                .Add(TipoGaranzia.RCMalattieProfessionali, "Malattie professionali")
                .Add(TipoGaranzia.RCInquinamento, "Inquinamento dell'aria, dell'acqua e del suolo")
                .Add(TipoGaranzia.RCFornitura, "RC della fornitura")
                .Add(TipoGaranzia.RCDistributori1, "RC dei distributori di carburante 1")
                .Add(TipoGaranzia.RCDistributori2, "RC dei distributori di carburante 2")
                .Add(TipoGaranzia.RCCatering, "Servizi di catering")
                .Add(TipoGaranzia.RCInstallazioni, "Installazioni presso terzi e Postuma 1 anno")
                .Add(TipoGaranzia.RCLavanderie, "Stirerie, Lavanderie")
                .Add(TipoGaranzia.RCParrucchieri, "Istituti di bellezza, Parrucchieri, Estetisti")
                .Add(TipoGaranzia.RCSoloProprieta, "Limitazione alla sola proprietà del fabbricato")
                .Add(TipoGaranzia.RCAmbulante, "Commercio ambulante")
                .Add(TipoGaranzia.RCFranchigia, "Franchigia assoluta")
                .Add(TipoGaranzia.RCCarrelli, "Utilizzo carrelli elevatori e macchine operatrici")
                .Add(TipoGaranzia.TutelaLegaleBase, "Garanzia base")
                .Add(TipoGaranzia.TutelaLegaleDlgs07193, "D.Lgs 193/07 Controlli in sicurezza alimentare")
                .Add(TipoGaranzia.TutelaLegaleDlgs01231, "D.Lgs 231/01 Responsabilità amministrativa")
                .Add(TipoGaranzia.TutelaLegaleDlgs97472, "D.Lgs 472/97 Riforma fiscale e tributaria")
                .Add(TipoGaranzia.AssistenzaBase, "Garanzia base")
                .Add(TipoGaranzia.TerremotoBase, "Garanzia base")
                .Add(TipoGaranzia.TerremotoFabbricato, "Fabbricato")
                .Add(TipoGaranzia.TerremotoContenuto, "Contenuto")
                .Add(TipoGaranzia.TerremotoDemolizione, "Spese di demolizione, sgombero, trasporto, rimozione e ricollocamento")
                .Add(TipoGaranzia.TerremotoAumentoMerci, "Aumento periodico merci assicurate (n° mesi)")
                .Add(TipoGaranzia.TerremotoRicetteMediche, "Ricette mediche")
            End With

            With DecodeClasseFabbricato
                .Add(ClasseFabbricatoEnum.Classe1, "Classe 1")
                .Add(ClasseFabbricatoEnum.Classe2, "Classe 2")
            End With

            With DecodeFabbricatoDestinazione
                .Add(FabbricatoDestinazioneEnum.VenditaDettaglio, "Vendita Dettaglio")
                .Add(FabbricatoDestinazioneEnum.VenditaIngrosso, "Vendita Ingrosso")
                .Add(FabbricatoDestinazioneEnum.VenditaIngrossoDettaglio, "Vendita Ingrosso e Dettaglio")
                .Add(FabbricatoDestinazioneEnum.Uffici, "Uffici")
            End With

            With DecodeZonaTerritorialeFurto
                .Add(ZonaTerritorialeFurtoEnum.Zona12, "12")
                .Add(ZonaTerritorialeFurtoEnum.Zona21, "21")
                .Add(ZonaTerritorialeFurtoEnum.Zona22, "22")
                .Add(ZonaTerritorialeFurtoEnum.Zona31, "31")
                .Add(ZonaTerritorialeFurtoEnum.Zona32, "32")
                .Add(ZonaTerritorialeFurtoEnum.Zona41, "41")
            End With

            With DecodeZonaTerritorialeEventiAtmosferici
                .Add(ZonaTerritorialeEventiAtmosfericiEnum.ZonaA, "Zona A")
                .Add(ZonaTerritorialeEventiAtmosfericiEnum.ZonaB, "Zona B")
                .Add(ZonaTerritorialeEventiAtmosfericiEnum.ZonaC, "Zona C")
            End With

            With DecodeClasseRischioAttivitaFurto
                .Add(ClasseRischioAttivitaFurtoEnum.ND, "ND")
                .Add(ClasseRischioAttivitaFurtoEnum.RD, "RD")
                .Add(ClasseRischioAttivitaFurtoEnum.A0, "A0")
                .Add(ClasseRischioAttivitaFurtoEnum.A2, "A2")
                .Add(ClasseRischioAttivitaFurtoEnum.B1, "B1")
                .Add(ClasseRischioAttivitaFurtoEnum.B2, "B2")
                .Add(ClasseRischioAttivitaFurtoEnum.C1, "C1")
                .Add(ClasseRischioAttivitaFurtoEnum.C2, "C2")
                .Add(ClasseRischioAttivitaFurtoEnum.D1, "D1")
                .Add(ClasseRischioAttivitaFurtoEnum.D2, "D2")
            End With

            With DecodeIncendioScelta
                .Add(IncendioSceltaEnum.RischiNominati, "Rischi Nominati")
                .Add(IncendioSceltaEnum.AllRisks, "All Risks")
            End With

            With DecodeIncendioEventiAtmosfericiScelta
                .Add(IncendioEventiAtmosfericiSceltaEnum.SceltaBasic, "Scelta Basic")
                .Add(IncendioEventiAtmosfericiSceltaEnum.SceltaMedium, "Scelta Medium")
                .Add(IncendioEventiAtmosfericiSceltaEnum.SceltaLarge, "Scelta Large")
            End With

            With DecodeIncendioDanniElettriciScelta
                .Add(IncendioDanniElettriciSceltaEnum.SceltaBasic, "Scelta Basic - Fenomeni elettrici")
                .Add(IncendioDanniElettriciSceltaEnum.SceltaMedium, "Scelta Medium - Guasti")
            End With

            With DecodeIncendioDanniIndirettiScelta
                .Add(IncendioDanniIndirettiSceltaEnum.SceltaBasicDiaria, "Danni Indiretti a diaria")
                .Add(IncendioDanniIndirettiSceltaEnum.SceltaBasicPercentuale, "Danni Indiretti a percentuale")
            End With

            With DecodeClasseMerceologica
                .Add(ClasseRischioAttivitaFurtoEnum.A2, "Classe Merceologica A2")
                .Add(ClasseRischioAttivitaFurtoEnum.B1, "Classe Merceologica B1")
                .Add(ClasseRischioAttivitaFurtoEnum.B2, "Classe Merceologica B2")
                .Add(ClasseRischioAttivitaFurtoEnum.C1, "Classe Merceologica C1")
                .Add(ClasseRischioAttivitaFurtoEnum.C2, "Classe Merceologica C2")
                .Add(ClasseRischioAttivitaFurtoEnum.D1, "Classe Merceologica D1")
            End With

            With DecodeFurtoFissiScelta
                .Add(FurtoFissiSceltaEnum.SceltaA, "Scelta A")
                .Add(FurtoFissiSceltaEnum.SceltaB, "Scelta B")
            End With

            With DecodeFurtoValoriScelta
                .Add(FurtoValoriSceltaEnum.SceltaA, "Scelta A - Valori sotto chiave")
                .Add(FurtoValoriSceltaEnum.SceltaB, "Scelta B - Valori in cassaforte")
            End With

            With DecodeFurtoRapinaScelta
                .Add(FurtoRapinaSceltaEnum.SceltaA, "Scelta A")
                .Add(FurtoRapinaSceltaEnum.SceltaB, "Scelta B")
            End With

            With DecodeIncendioConduttureMassimale
                .Add(2000D, "Massimale € 2.000,00")
                .Add(5000D, "Massimale € 5.000,00")
                .Add(10000D, "Massimale € 10.000,00")
                .Add(20000D, "Massimale € 20.000,00 - RD")
                .Add(50000D, "Massimale € 50.000,00 - RD")
            End With
            With DecodeIncendioDemolizioneMassimale
                .Add(10000D, "Massimale € 10.000,00")
                .Add(30000D, "Massimale € 30.000,00")
                .Add(50000D, "Massimale € 50.000,00")
                .Add(100000D, "Massimale € 100.000,00")
                .Add(200000D, "Massimale € 200.000,00")
                .Add(300000D, "Massimale € 300.000,00 - RD")
                .Add(500000D, "Massimale € 500.000,00 - RD")
            End With
            With DecodeIncendioFranchigiaFranchigia
                .Add(1500D, "Franchigia € 1.500,00")
                .Add(2500D, "Franchigia € 2.500,00")
                .Add(20000D, "Franchigia € 20.000,00")
            End With
            With DecodeTipologiaFabbricato
                .Add(TipologiaFabbricatoEnum.TipologiaA, "A – Fabbricato")
                .Add(TipologiaFabbricatoEnum.TipologiaB, "B – Altri Fabbricati")
            End With

            With DecodeCaratteristicaCostruttiva
                .Add(CaratteristicaCostruttivaEnum.Antisismica, "Antisismica")
                .Add(CaratteristicaCostruttivaEnum.Tradizionale, "Tradizionale")
                .Add(CaratteristicaCostruttivaEnum.Muratura, "Muratura")
            End With
            With DecodeTerremotoBaseLimite
                .Add(30, "Limite 30%")
                .Add(50, "Limite 50%")
            End With
            With DecodeTerremotoDemolizioneMassimale
                .Add(10000D, "Massimale € 10.000,00")
                .Add(30000D, "Massimale € 30.000,00")
                .Add(50000D, "Massimale € 50.000,00")
                .Add(100000D, "Massimale € 100.000,00")
                .Add(200000D, "Massimale € 200.000,00")
            End With


            With DecodeResponsabilitaCivileRctMassimale
                .Add(250000D, "Massimale € 250.000,00")
                .Add(500000D, "Massimale € 500.000,00")
                .Add(1000000D, "Massimale € 1.000.000,00")
                .Add(1500000D, "Massimale € 1.500.000,00")
                .Add(3000000D, "Massimale € 3.000.000,00")
                .Add(4000000D, "Massimale € 4.000.000,00")
                .Add(5000000D, "Massimale € 5.000.000,00")
            End With
            With DecodeResponsabilitaCivileRcoMassimale
                .Add(250000D, "Massimale € 250.000,00")
                .Add(500000D, "Massimale € 500.000,00")
                .Add(1000000D, "Massimale € 1.000.000,00")
                .Add(1500000D, "Massimale € 1.500.000,00")
                .Add(3000000D, "Massimale € 3.000.000,00")
                .Add(4000000D, "Massimale € 4.000.000,00")
                .Add(5000000D, "Massimale € 5.000.000,00")
            End With
            With DecodeRCSoloProprietaMassimale
                .Add(500000D, "Massimale € 500.000,00")
                .Add(1000000D, "Massimale € 1.000.000,00")
                .Add(1500000D, "Massimale € 1.500.000,00")
            End With
            With DecodeRCFranchigiaFranchigia
                .Add(1500D, "Franchigia assoluta € 1.500,00")
                .Add(2500D, "Franchigia assoluta € 2.500,00")
                .Add(20000D, "Franchigia assoluta € 20.000,00")
            End With
            With DecodeTutelaLegaleBaseMassimale
                .Add(10000D, "Massimale € 10.000,00")
                .Add(20000D, "Massimale € 20.000,00")
                .Add(30000D, "Massimale € 30.000,00")
            End With

            With DecodeProvinciaToZonaTerritorialeFurto
                .Add(ProvinciaEnum.SiglaXX, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaAG, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaAL, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaAN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaAO, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaAP, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaAQ, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaAR, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaAT, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaAV, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaBA, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaBG, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaBI, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaBL, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaBN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaBO, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaBR, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaBS, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaBT, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaBZ, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaCA, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaCB, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaCE, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaCH, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaCI, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaCL, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaCN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaCO, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaCR, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaCS, ZonaTerritorialeFurtoEnum.Zona22)
                .Add(ProvinciaEnum.SiglaCT, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaCZ, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaEN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaFC, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaFE, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaFG, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaFI, ZonaTerritorialeFurtoEnum.Zona22)
                .Add(ProvinciaEnum.SiglaFM, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaFR, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaGE, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaGO, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaGR, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaIM, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaIS, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaKR, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaLC, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaLE, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaLI, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaLO, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaLT, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaLU, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaMB, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaMC, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaME, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaMI, ZonaTerritorialeFurtoEnum.Zona21)
                .Add(ProvinciaEnum.SiglaMN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaMO, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaMS, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaMT, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaNA, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaNO, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaNU, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaOG, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaOR, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaOT, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaPA, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaPC, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaPD, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaPE, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPG, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPI, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPN, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaPO, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaPR, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaPT, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPU, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPV, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaPZ, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaRA, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaRC, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaRE, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaRG, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaRI, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaRM, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaRN, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaRO, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaRSM, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaSA, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaSI, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaSO, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaSP, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaSR, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaSS, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaSV, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaTA, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaTE, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaTN, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaTO, ZonaTerritorialeFurtoEnum.Zona12)
                .Add(ProvinciaEnum.SiglaTP, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaTR, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaTS, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaTV, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaUD, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaVA, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaVB, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaVC, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaVE, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaVI, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaVR, ZonaTerritorialeFurtoEnum.Zona31)
                .Add(ProvinciaEnum.SiglaVS, ZonaTerritorialeFurtoEnum.Zona32)
                .Add(ProvinciaEnum.SiglaVT, ZonaTerritorialeFurtoEnum.Zona41)
                .Add(ProvinciaEnum.SiglaVV, ZonaTerritorialeFurtoEnum.Zona21)
            End With
            With DecodeProvinciaToEventiAtmosferici
                .Add(ProvinciaEnum.SiglaXX, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaAG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaAL, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaAN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaAO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaAP, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaAQ, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaAR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaAT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaAV, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaBA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaBG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaBI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaBL, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaBN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaBO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaBR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaBS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaBT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaBZ, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaCB, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCH, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaCL, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaCN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaCO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaCR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaCS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaCZ, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaEN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaFC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaFE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaFG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaFI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaFM, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaFR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaGE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaGO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaGR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaIM, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaIS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaKR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaLC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaLE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaLI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaLO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaLT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaLU, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaMB, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaMC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaME, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaMI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaMN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaMO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaMS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaMT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaNA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaNO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaNU, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaOG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaOR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaOT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaPA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaPC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaPD, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaPE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaPG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaPI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaPN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaPO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaPR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaPT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaPU, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaPV, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaPZ, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaRA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRG, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaRI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRM, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaRO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaRSM, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaSA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaSI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaSO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaSP, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaSR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaSS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaSV, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaTA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaTE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaTN, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaTO, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaTP, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaTR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaTS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaTV, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaUD, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaVA, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVB, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVC, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVE, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVI, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVR, ZonaTerritorialeEventiAtmosfericiEnum.ZonaA)
                .Add(ProvinciaEnum.SiglaVS, ZonaTerritorialeEventiAtmosfericiEnum.ZonaC)
                .Add(ProvinciaEnum.SiglaVT, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
                .Add(ProvinciaEnum.SiglaVV, ZonaTerritorialeEventiAtmosfericiEnum.ZonaB)
            End With

            With DecodeAttivita
                .Add(0, "Attitività non selezionata")
                .Add(100, "Altra attività alimentare - RD")
                .Add(111, "Acque gassose e minerali, bibite analcoliche,succhi di frutta")
                .Add(114, "Enoteche/Bott iglierie/Liquori in genere e bevande alcoliche")
                .Add(126, "Panetterie, paste alimentari, anche con forno o pastifi cio")
                .Add(135, "Pasticcerie, gelaterie, cremerie, caramelle")
                .Add(141, "Confetture, conserve")
                .Add(144, "Salumerie, pizzicherie")
                .Add(146, "Surgelati")
                .Add(149, "Drogherie, caff è e coloniali in genere")
                .Add(161, "Formaggi in genere, latterie")
                .Add(163, "Oli e grassi alimentari")
                .Add(166, "Macellerie, carni in genere, pollerie")
                .Add(171, "Cereali, granaglie, sementi in genere, mangimi")
                .Add(179, "Alimentari in genere anche surgelati")
                .Add(181, "Ristoranti, tavole calde, tratt orie, friggitorie, gastronomie, rosticcerie, pizzerie, anche con bar")
                .Add(182, "Bar, birrerie, degustazione/consumazione vini, esclusi: tabacchi, slot machine con vincite in denaro, ricevitorie")
                .Add(183, "Bar, birrerie, degustazione/consumazione vini, compresi tabacchi, slot machine con vincite in denaro, ricevitorie")
                .Add(184, "Circoli ricreativi/culturali/dopolavoro, compresi: impianti sportivi, bar; esclusi: sale da ballo, tabacchi, slot machine con vincite in denaro, ricevitorie")
                .Add(185, "Circoli ricreativi/culturali/dopolavoro, compresi: impianti sportivi, bar, tabacchi, slot machine con vincite in denaro, ricevitorie; escluse sale da ballo")
                .Add(190, "Frutta e verdura")
                .Add(191, "Pescherie")
                .Add(200, "Altra attività elettromeccanica - RD")
                .Add(222, "Attrezzature ed articoli tecnici per imprese commerciali ed industriali")
                .Add(226, "Ferramenta, coltellerie, minuterie metalliche, utensileria e rubinetteria")
                .Add(232, "Articoli e materiali elettrici, utensileria elettrica ed idraulica")
                .Add(235, "Lampadari e lampade da tavolo")
                .Add(237, "Personal computers, telefonia, articoli e componenti elettronici, giochi elettronici (esclusa assistenza software)")
                .Add(241, "Macchine e attrezzature per ufficio")
                .Add(242, "Articoli fotografici, compreso sviluppo e stampa, ottici e di precisione")
                .Add(251, "Autoveicoli, autoconcessionari")
                .Add(253, "Accessori e ricambi per auto, cicli, motocicli")
                .Add(254, "Biciclette, moto, ciclomotori")
                .Add(256, "Macchine e meccanismi agricoli, edili, stradali ed industriali")
                .Add(257, "Barche, natanti in genere, articoli nautici")
                .Add(258, "Roulottes e camper (vendita ed esposizione)")
                .Add(261, "Elettrodomestici anche audiovisivi ed apparecchi domestici compresi i relativi accessori")
                .Add(263, "Mobili in metallo")
                .Add(271, "Oggetti di metallo (esclusi preziosi)")
                .Add(273, "Oggetti di metallo (esclusi stagno, ottone, bronzo, piombo, rame, acciai e preziosi)")
                .Add(274, "Serramenti metallici (esclusa installazione)")
                .Add(275, "Timbri, targhe, medaglie, coppe (esclusi argento e preziosi)")
                .Add(284, "Oreficierie, gioiellerie ed argenterie")
                .Add(287, "Orologiai anche con riparazione")
                .Add(288, "Bigiotteria (esclusi argento e preziosi)")
                .Add(300, "Altra attività legno - RD")
                .Add(312, "Legno da costruzione, opera, lavoro")
                .Add(321, "Serramenti in genere (esclusa installazione)")
                .Add(331, "Oggetti di legno non artistici, cornici non in argento e simili")
                .Add(332, "Articoli casalinghi compresi piccoli elettrodomestici e relativi accessori (esclusi audiovisivi)")
                .Add(333, "Imballaggi anche combustibili (escluse materie plastiche espanse e/o alveolari)")
                .Add(341, "Mobili in genere, divani, poltrone escluso antiquariato")
                .Add(343, "Onoranze funebri")
                .Add(361, "Giocattoli (esclusi quelli elettronici e pirici)")
                .Add(362, "Strumenti musicali ed accessori")
                .Add(363, "Penne stilografiche a sfera, a feltro (esclusi argento e preziosi)")
                .Add(364, "Articoli di caccia e pesca")
                .Add(365, "Fumatori (articoli per) (esclusi preziosi)")
                .Add(391, "Antiquari, quadri e oggetti d’arte (esclusi preziosi)")
                .Add(392, "Gallerie d’arte")
                .Add(400, "Altra attività carta, plastica, gomma, pelle - RD")
                .Add(418, "Cancelleria, cartoleria, cartolibreria, comprese legatorie e forniture per ufficio")
                .Add(422, "Copisterie, fotocopie e copie eliografiche")
                .Add(427, "Edicole e librerie")
                .Add(434, "Pelletterie, accessori per l’abbigliamento anche in pelle, articoli da viaggio, ombrelli")
                .Add(435, "Calzature (esclusi articoli da viaggio)")
                .Add(438, "Calzolai, attività affini alla riparazione di calzature in genere, duplicazione chiavi")
                .Add(441, "Oggetti di plastica non espansa o alveolare")
                .Add(444, "Tappezzerie, moquettes")
                .Add(448, "Fiori e piante artificiali")
                .Add(449, "Giardinaggio (articoli da) (solo vendita)")
                .Add(451, "Oggetti di gomma (esclusi gommaspugna, microporosa e pneumatici)")
                .Add(463, "Compact disc ed audio-video cassette")
                .Add(469, "Bazar, empori (esclusi preziosi)")
                .Add(472, "Bricolage")
                .Add(475, "Campeggio e sportivi (rticoli per) (compreso abbigliamento)")
                .Add(476, "Campeggio e sportivi (articoli per) (escluso abbigliamento)")
                .Add(477, "Bomboniere (esclusi argento e preziosi)")
                .Add(500, "Altra attività edilizia - RD")
                .Add(532, "Casalinghi di ceramica, terracotte, gres, porcellane, maioliche e vetro, ceramiche,")
                .Add(541, "Materiali ed attrezzature incombustibili per l’edilizia")
                .Add(542, "Materiali ed attrezzature per l’edilizia (esclusi espansi e/o alveolari/esclusa installazione)")
                .Add(553, "Vetri, cristalli, specchi")
                .Add(600, "Altra attività tessile - RD")
                .Add(651, "Tessuti e stoffe per l’arredamento, biancheria per la casa,Tessuti, stoffe per abbigliamento")
                .Add(663, "Lavanderie, tintorie, stirerie, di indumenti usati")
                .Add(668, "Coperte, copriletti, trapunte, cuscini, materassi e reti")
                .Add(669, "Lavanderie automatiche")
                .Add(674, "Articoli medicali, ortopedici, igienico sanitari (escluso medicinali)")
                .Add(679, "Tappeti, arazzi")
                .Add(681, "Abbigliamento in genere (escluse pellicce)")
                .Add(682, "Calze, guanti, cravatte, foderami, mercerie (escluso abbigliamento), passamanerie")
                .Add(684, "Cappelli, berretti")
                .Add(685, "Sartorie su misura, modisterie e riparazioni di vestiario")
                .Add(687, "Tendaggi, tende da sole, tende alla veneziana")
                .Add(688, "Pelliccerie")
                .Add(689, "Abbigliamento da lavoro")
                .Add(691, "Articoli religiosi (esclusi argento e preziosi)")
                .Add(692, "Articoli religiosi (esclusi preziosi)")
                .Add(693, "Articoli per l’infanzia in genere")
                .Add(695, "Cesteria")
                .Add(700, "Altra attività chimica - RD")
                .Add(711, "Combustibili ad uso domestico (esclusi gas in bombole)")
                .Add(721, "Olii lubrificanti, minerali e non")
                .Add(726, "Detersivi, sapone, saponette ed altri prodotti per l’igiene e la pulizia dei locali")
                .Add(737, "Colorifici, vernici, smalti, colori, coloranti, terre coloranti, colle e paste adesive")
                .Add(743, "Concimi, fertilizzanti, diserbanti, disinfestanti")
                .Add(751, "Profumerie, cosmetici, prodotti di bellezza e per l’igiene della persona")
                .Add(752, "Barbiere/Parrucchiere")
                .Add(753, "Erboristerie")
                .Add(754, "Farmacie (esclusi stupefacenti)")
                .Add(755, "Istituti di bellezza (esclusi solarium)")
                .Add(756, "Estetisti, visagisti, massaggiatori, podologi (esclusi solarium, elettrostimolazioni, cure dimagranti)")
                .Add(757, "Tatuaggi e pearcing")
                .Add(800, "Altra attività chimica - RD")
                .Add(881, "Tabaccherie")
                .Add(891, "Armi e munizioni")
                .Add(900, "Altra attività varie - RD")
                .Add(913, "Supermercati alimentari, minimarket, compresi generi per la pulizia della casa e della persona")
                .Add(921, "Autorimesse e/o silos")
                .Add(936, "Filatelia e numismatica (escluse monete d’oro)")
                .Add(938, "Internet points, phone centers")
                .Add(941, "Distributori di carburante (escluso servizi di autolavaggio e di officina)")
                .Add(942, "Distributori di carburante compresi servizi di autolavaggio e di officina - stazioni di servizio")
                .Add(966, "Sale giochi elettronici (esclusi giochi d’azzardo elettronici come slot machines, videopoker e simili costituenti attività preponderante/principale )")
                .Add(968, "Sexy shop")
                .Add(955, "Palestre")
                .Add(971, "Agenzie di scommesse sportive e ricevitorie")
                .Add(972, "Circoli ricreativi, culturali o dopolavoristici anche con impianti sportivi (senza bar e sala da ballo)")
                .Add(991, "Fiori naturali freschi (escluso serre e vivai)")
                .Add(994, "Toelettatuta per cani")
                .Add(995, "Animali vivi e relativi mangimi ed accessori")
            End With


            With DecodeAttivitaToClasseRischioAttivitaIncendio
                .Add(0, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(100, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(111, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(114, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(126, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(135, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(141, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(144, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(146, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(149, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(161, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(163, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(166, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(171, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(179, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(181, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(182, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(183, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(184, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(185, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(190, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(191, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(200, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(222, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(226, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(232, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(235, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(237, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(241, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(242, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(251, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(253, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(254, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(256, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(257, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(258, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(261, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(263, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(271, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(273, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(274, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(275, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(284, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(287, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(288, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(300, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(312, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(321, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(331, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(332, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(333, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(341, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(343, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(361, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(362, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(363, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(364, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(365, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(391, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(392, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(400, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(418, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(422, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(427, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(434, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(435, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(438, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(441, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(444, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(448, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(449, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(451, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(463, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(469, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(472, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(475, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(476, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(477, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(500, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(532, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(541, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(542, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(553, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(600, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(651, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(663, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(668, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(669, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(674, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(679, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(681, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(682, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(684, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(685, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(687, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(688, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(689, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(691, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(692, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(693, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(695, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(700, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(711, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(721, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(726, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(737, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(743, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(751, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(752, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(753, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(754, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(755, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(756, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(757, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(800, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(881, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(891, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(900, ClasseRischioAttivitaIncendioEnum.ClasseND)
                .Add(913, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(921, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(936, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(938, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(941, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(942, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(966, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(968, ClasseRischioAttivitaIncendioEnum.Classe2)
                .Add(955, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(971, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(972, ClasseRischioAttivitaIncendioEnum.Classe3)
                .Add(991, ClasseRischioAttivitaIncendioEnum.Classe1)
                .Add(994, ClasseRischioAttivitaIncendioEnum.Classe4)
                .Add(995, ClasseRischioAttivitaIncendioEnum.Classe1)
            End With

            With DecodeAttivitaToClasseRischioAttivitaFurto
                .Add(0, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(100, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(111, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(114, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(126, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(135, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(141, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(144, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(146, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(149, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(161, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(163, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(166, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(171, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(179, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(181, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(182, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(183, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(184, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(185, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(190, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(191, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(200, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(222, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(226, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(232, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(235, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(237, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(241, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(242, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(251, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(253, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(254, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(256, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(257, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(258, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(261, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(263, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(271, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(273, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(274, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(275, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(284, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(287, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(288, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(300, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(312, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(321, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(331, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(332, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(333, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(341, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(343, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(361, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(362, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(363, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(364, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(365, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(391, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(392, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(400, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(418, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(422, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(427, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(434, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(435, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(438, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(441, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(444, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(448, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(449, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(451, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(463, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(469, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(472, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(475, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(476, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(477, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(500, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(532, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(541, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(542, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(553, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(600, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(651, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(663, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(668, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(669, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(674, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(679, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(681, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(682, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(684, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(685, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(687, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(688, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(689, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(691, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(692, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(693, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(695, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(700, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(711, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(721, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(726, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(737, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(743, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(751, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(752, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(753, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(754, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(755, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(756, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(757, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(800, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(881, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(891, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(900, ClasseRischioAttivitaFurtoEnum.ND)
                .Add(913, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(921, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(936, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(938, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(941, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(942, ClasseRischioAttivitaFurtoEnum.A2)
                .Add(966, ClasseRischioAttivitaFurtoEnum.B1)
                .Add(968, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(955, ClasseRischioAttivitaFurtoEnum.C2)
                .Add(971, ClasseRischioAttivitaFurtoEnum.B2)
                .Add(972, ClasseRischioAttivitaFurtoEnum.C1)
                .Add(991, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(994, ClasseRischioAttivitaFurtoEnum.D1)
                .Add(995, ClasseRischioAttivitaFurtoEnum.D1)
            End With

            With DecodeAttivitaToClasseRischioAttivitaRc
                .Add(0, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(100, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(111, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(114, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(126, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(135, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(141, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(144, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(146, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(149, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(161, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(163, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(166, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(171, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(179, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(181, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(182, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(183, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(184, ClasseRischioAttivitaRcEnum.ClasseRD)
                .Add(185, ClasseRischioAttivitaRcEnum.ClasseRD)
                .Add(190, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(191, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(200, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(222, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(226, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(232, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(235, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(237, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(241, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(242, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(251, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(253, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(254, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(256, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(257, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(258, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(261, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(263, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(271, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(273, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(274, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(275, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(284, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(287, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(288, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(300, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(312, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(321, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(331, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(332, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(333, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(341, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(343, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(361, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(362, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(363, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(364, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(365, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(391, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(392, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(400, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(418, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(422, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(427, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(434, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(435, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(438, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(441, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(444, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(448, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(449, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(451, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(463, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(469, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(472, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(475, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(476, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(477, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(500, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(532, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(541, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(542, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(553, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(600, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(651, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(663, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(668, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(669, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(674, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(679, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(681, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(682, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(684, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(685, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(687, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(688, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(689, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(691, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(692, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(693, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(695, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(700, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(711, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(721, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(726, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(737, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(743, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(751, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(752, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(753, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(754, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(755, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(756, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(757, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(800, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(881, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(891, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(900, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(913, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(921, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(936, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(938, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(941, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(942, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(966, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(968, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(955, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(971, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(972, ClasseRischioAttivitaRcEnum.ClasseND)
                .Add(991, ClasseRischioAttivitaRcEnum.Classe2)
                .Add(994, ClasseRischioAttivitaRcEnum.Classe1)
                .Add(995, ClasseRischioAttivitaRcEnum.Classe1)
            End With

            With DecodeAttivitaToClasseRischioAttivitaTerremoto
                .Add(0, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(100, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(111, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(114, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(126, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(135, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(141, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(144, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(146, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(149, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(161, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(163, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(166, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(171, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(179, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(181, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(182, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(183, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(184, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(185, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(190, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(191, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(200, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(222, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(226, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(232, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(235, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(237, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(241, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(242, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(251, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(253, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(254, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(256, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(257, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(258, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(261, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(263, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(271, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(273, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(274, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(275, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(284, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(287, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(288, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(300, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(312, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(321, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(331, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(332, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(333, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(341, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(343, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(361, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(362, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(363, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(364, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(365, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(391, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(392, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(400, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(418, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(422, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(427, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(434, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(435, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(438, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(441, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(444, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(448, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(449, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(451, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(463, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(469, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(472, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(475, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(476, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(477, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(500, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(532, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(541, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(542, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(553, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(600, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(651, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(663, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(668, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(669, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(674, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(679, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(681, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(682, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(684, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(685, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(687, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(688, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(689, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(691, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(692, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(693, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(695, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(700, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(711, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(721, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(726, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(737, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(743, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(751, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(752, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(753, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(754, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(755, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(756, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(757, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(800, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(881, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(891, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(900, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(913, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(921, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(936, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(938, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(941, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(942, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(966, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(968, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(955, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(971, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(972, ClasseRischioAttivitaTerremotoEnum.Classe3)
                .Add(991, ClasseRischioAttivitaTerremotoEnum.Classe1)
                .Add(994, ClasseRischioAttivitaTerremotoEnum.Classe2)
                .Add(995, ClasseRischioAttivitaTerremotoEnum.Classe1)
            End With

        End Sub
    End Class
End Namespace
