'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace VisureOMW
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VisureSoap", [Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class Visure
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private VisuraPraOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ElencoVisureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportVisureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraLottoAvvisiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Visure.My.MySettings.Default.Visure_VisureOMW_Sinistri
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event VisuraPraCompleted As VisuraPraCompletedEventHandler
        
        '''<remarks/>
        Public Event ElencoVisureCompleted As ElencoVisureCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportVisureCompleted As ReportVisureCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraLottoAvvisiCompleted As RegistraLottoAvvisiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/VisuraPra", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VisuraPra(ByVal AgenziaMadre As String, ByVal Utente As String, ByVal Targa As String, ByVal CodiceSerieTarga As Integer, ByVal Token As String) As Visura
            Dim results() As Object = Me.Invoke("VisuraPra", New Object() {AgenziaMadre, Utente, Targa, CodiceSerieTarga, Token})
            Return CType(results(0),Visura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VisuraPraAsync(ByVal AgenziaMadre As String, ByVal Utente As String, ByVal Targa As String, ByVal CodiceSerieTarga As Integer, ByVal Token As String)
            Me.VisuraPraAsync(AgenziaMadre, Utente, Targa, CodiceSerieTarga, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VisuraPraAsync(ByVal AgenziaMadre As String, ByVal Utente As String, ByVal Targa As String, ByVal CodiceSerieTarga As Integer, ByVal Token As String, ByVal userState As Object)
            If (Me.VisuraPraOperationCompleted Is Nothing) Then
                Me.VisuraPraOperationCompleted = AddressOf Me.OnVisuraPraOperationCompleted
            End If
            Me.InvokeAsync("VisuraPra", New Object() {AgenziaMadre, Utente, Targa, CodiceSerieTarga, Token}, Me.VisuraPraOperationCompleted, userState)
        End Sub
        
        Private Sub OnVisuraPraOperationCompleted(ByVal arg As Object)
            If (Not (Me.VisuraPraCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VisuraPraCompleted(Me, New VisuraPraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/ElencoVisure", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ElencoVisure(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ElencoVisure", New Object() {Inizio, Fine, Token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ElencoVisureAsync(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String)
            Me.ElencoVisureAsync(Inizio, Fine, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ElencoVisureAsync(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String, ByVal userState As Object)
            If (Me.ElencoVisureOperationCompleted Is Nothing) Then
                Me.ElencoVisureOperationCompleted = AddressOf Me.OnElencoVisureOperationCompleted
            End If
            Me.InvokeAsync("ElencoVisure", New Object() {Inizio, Fine, Token}, Me.ElencoVisureOperationCompleted, userState)
        End Sub
        
        Private Sub OnElencoVisureOperationCompleted(ByVal arg As Object)
            If (Not (Me.ElencoVisureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ElencoVisureCompleted(Me, New ElencoVisureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/ReportVisure", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportVisure(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ReportVisure", New Object() {Inizio, Fine, Token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportVisureAsync(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String)
            Me.ReportVisureAsync(Inizio, Fine, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportVisureAsync(ByVal Inizio As Date, ByVal Fine As Date, ByVal Token As String, ByVal userState As Object)
            If (Me.ReportVisureOperationCompleted Is Nothing) Then
                Me.ReportVisureOperationCompleted = AddressOf Me.OnReportVisureOperationCompleted
            End If
            Me.InvokeAsync("ReportVisure", New Object() {Inizio, Fine, Token}, Me.ReportVisureOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportVisureOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportVisureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportVisureCompleted(Me, New ReportVisureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utools.auaonline.it/RegistraLottoAvvisi", RequestNamespace:="http://utools.auaonline.it/", ResponseNamespace:="http://utools.auaonline.it/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistraLottoAvvisi(ByVal Ambiente As String, ByVal CodiceAgenzia As String, ByVal Localita As String, ByVal MeseAvvisi As Integer, ByVal AnnoAvvisi As Integer, ByVal NomeLotto As String, ByVal IdCampagna As String, ByVal Destinatari As Integer, ByVal Titoli As Integer, ByVal Comunicazioni As Integer, ByVal Token As String) As String
            Dim results() As Object = Me.Invoke("RegistraLottoAvvisi", New Object() {Ambiente, CodiceAgenzia, Localita, MeseAvvisi, AnnoAvvisi, NomeLotto, IdCampagna, Destinatari, Titoli, Comunicazioni, Token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraLottoAvvisiAsync(ByVal Ambiente As String, ByVal CodiceAgenzia As String, ByVal Localita As String, ByVal MeseAvvisi As Integer, ByVal AnnoAvvisi As Integer, ByVal NomeLotto As String, ByVal IdCampagna As String, ByVal Destinatari As Integer, ByVal Titoli As Integer, ByVal Comunicazioni As Integer, ByVal Token As String)
            Me.RegistraLottoAvvisiAsync(Ambiente, CodiceAgenzia, Localita, MeseAvvisi, AnnoAvvisi, NomeLotto, IdCampagna, Destinatari, Titoli, Comunicazioni, Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraLottoAvvisiAsync(ByVal Ambiente As String, ByVal CodiceAgenzia As String, ByVal Localita As String, ByVal MeseAvvisi As Integer, ByVal AnnoAvvisi As Integer, ByVal NomeLotto As String, ByVal IdCampagna As String, ByVal Destinatari As Integer, ByVal Titoli As Integer, ByVal Comunicazioni As Integer, ByVal Token As String, ByVal userState As Object)
            If (Me.RegistraLottoAvvisiOperationCompleted Is Nothing) Then
                Me.RegistraLottoAvvisiOperationCompleted = AddressOf Me.OnRegistraLottoAvvisiOperationCompleted
            End If
            Me.InvokeAsync("RegistraLottoAvvisi", New Object() {Ambiente, CodiceAgenzia, Localita, MeseAvvisi, AnnoAvvisi, NomeLotto, IdCampagna, Destinatari, Titoli, Comunicazioni, Token}, Me.RegistraLottoAvvisiOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraLottoAvvisiOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistraLottoAvvisiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraLottoAvvisiCompleted(Me, New RegistraLottoAvvisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://utools.auaonline.it/")>  _
    Partial Public Class Visura
        
        Private codiceEsitoField As Object
        
        Private erroreField As String
        
        Private visuraRichiestaField() As Byte
        
        '''<remarks/>
        Public Property CodiceEsito() As Object
            Get
                Return Me.codiceEsitoField
            End Get
            Set
                Me.codiceEsitoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errore() As String
            Get
                Return Me.erroreField
            End Get
            Set
                Me.erroreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property VisuraRichiesta() As Byte()
            Get
                Return Me.visuraRichiestaField
            End Get
            Set
                Me.visuraRichiestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub VisuraPraCompletedEventHandler(ByVal sender As Object, ByVal e As VisuraPraCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VisuraPraCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Visura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Visura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ElencoVisureCompletedEventHandler(ByVal sender As Object, ByVal e As ElencoVisureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ElencoVisureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportVisureCompletedEventHandler(ByVal sender As Object, ByVal e As ReportVisureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportVisureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub RegistraLottoAvvisiCompletedEventHandler(ByVal sender As Object, ByVal e As RegistraLottoAvvisiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraLottoAvvisiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
