'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace ServiziUniarea
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="accessoCasaSoap", [Namespace]:="casa.org")>  _
    Partial Public Class accessoCasa
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private checkSmsWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private checkVisureWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private checkMultiploWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private checkPostalizzazioneWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrazioneRicaricaWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraVisuraWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ElencoVisureWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportTotaliWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ElencoRicaricheWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDatiPostalizzazioneWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verificaEsistenzaCodiceFiscaleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private verificaEsistenzaEsistenzaEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDatiUtenteByCodiceFiscaleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDenominazioneGestoreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Utx.My.MySettings.Default.Ut_ServiziUniarea_accessoCasa
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event checkSmsWCompleted As checkSmsWCompletedEventHandler
        
        '''<remarks/>
        Public Event checkVisureWCompleted As checkVisureWCompletedEventHandler
        
        '''<remarks/>
        Public Event checkMultiploWCompleted As checkMultiploWCompletedEventHandler
        
        '''<remarks/>
        Public Event checkPostalizzazioneWCompleted As checkPostalizzazioneWCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrazioneRicaricaWCompleted As RegistrazioneRicaricaWCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraVisuraWCompleted As RegistraVisuraWCompletedEventHandler
        
        '''<remarks/>
        Public Event ElencoVisureWCompleted As ElencoVisureWCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportTotaliWCompleted As ReportTotaliWCompletedEventHandler
        
        '''<remarks/>
        Public Event ElencoRicaricheWCompleted As ElencoRicaricheWCompletedEventHandler
        
        '''<remarks/>
        Public Event getDatiPostalizzazioneWCompleted As getDatiPostalizzazioneWCompletedEventHandler
        
        '''<remarks/>
        Public Event verificaEsistenzaCodiceFiscaleCompleted As verificaEsistenzaCodiceFiscaleCompletedEventHandler
        
        '''<remarks/>
        Public Event verificaEsistenzaEsistenzaEmailCompleted As verificaEsistenzaEsistenzaEmailCompletedEventHandler
        
        '''<remarks/>
        Public Event getDatiUtenteByCodiceFiscaleCompleted As getDatiUtenteByCodiceFiscaleCompletedEventHandler
        
        '''<remarks/>
        Public Event getDenominazioneGestoreCompleted As getDenominazioneGestoreCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/checkSmsW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function checkSmsW(codiceAgenzia As String, codiceCompagnia As String, token As String) As String
            Dim results() As Object = Me.Invoke("checkSmsW", New Object() {codiceAgenzia, codiceCompagnia, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub checkSmsWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String)
            Me.checkSmsWAsync(codiceAgenzia, codiceCompagnia, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub checkSmsWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String, userState As Object)
            If (Me.checkSmsWOperationCompleted Is Nothing) Then
                Me.checkSmsWOperationCompleted = AddressOf Me.OncheckSmsWOperationCompleted
            End If
            Me.InvokeAsync("checkSmsW", New Object() {codiceAgenzia, codiceCompagnia, token}, Me.checkSmsWOperationCompleted, userState)
        End Sub
        
        Private Sub OncheckSmsWOperationCompleted(arg As Object)
            If (Not (Me.checkSmsWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent checkSmsWCompleted(Me, New checkSmsWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/checkVisureW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function checkVisureW(codiceAgenzia As String, codiceCompagnia As String, token As String) As String
            Dim results() As Object = Me.Invoke("checkVisureW", New Object() {codiceAgenzia, codiceCompagnia, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub checkVisureWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String)
            Me.checkVisureWAsync(codiceAgenzia, codiceCompagnia, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub checkVisureWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String, userState As Object)
            If (Me.checkVisureWOperationCompleted Is Nothing) Then
                Me.checkVisureWOperationCompleted = AddressOf Me.OncheckVisureWOperationCompleted
            End If
            Me.InvokeAsync("checkVisureW", New Object() {codiceAgenzia, codiceCompagnia, token}, Me.checkVisureWOperationCompleted, userState)
        End Sub
        
        Private Sub OncheckVisureWOperationCompleted(arg As Object)
            If (Not (Me.checkVisureWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent checkVisureWCompleted(Me, New checkVisureWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/checkMultiploW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function checkMultiploW(codiceAgenzia As String, codiceCompagnia As String, token As String) As String
            Dim results() As Object = Me.Invoke("checkMultiploW", New Object() {codiceAgenzia, codiceCompagnia, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub checkMultiploWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String)
            Me.checkMultiploWAsync(codiceAgenzia, codiceCompagnia, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub checkMultiploWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String, userState As Object)
            If (Me.checkMultiploWOperationCompleted Is Nothing) Then
                Me.checkMultiploWOperationCompleted = AddressOf Me.OncheckMultiploWOperationCompleted
            End If
            Me.InvokeAsync("checkMultiploW", New Object() {codiceAgenzia, codiceCompagnia, token}, Me.checkMultiploWOperationCompleted, userState)
        End Sub
        
        Private Sub OncheckMultiploWOperationCompleted(arg As Object)
            If (Not (Me.checkMultiploWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent checkMultiploWCompleted(Me, New checkMultiploWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/checkPostalizzazioneW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function checkPostalizzazioneW(codiceAgenzia As String, codiceCompagnia As String, token As String) As String
            Dim results() As Object = Me.Invoke("checkPostalizzazioneW", New Object() {codiceAgenzia, codiceCompagnia, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub checkPostalizzazioneWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String)
            Me.checkPostalizzazioneWAsync(codiceAgenzia, codiceCompagnia, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub checkPostalizzazioneWAsync(codiceAgenzia As String, codiceCompagnia As String, token As String, userState As Object)
            If (Me.checkPostalizzazioneWOperationCompleted Is Nothing) Then
                Me.checkPostalizzazioneWOperationCompleted = AddressOf Me.OncheckPostalizzazioneWOperationCompleted
            End If
            Me.InvokeAsync("checkPostalizzazioneW", New Object() {codiceAgenzia, codiceCompagnia, token}, Me.checkPostalizzazioneWOperationCompleted, userState)
        End Sub
        
        Private Sub OncheckPostalizzazioneWOperationCompleted(arg As Object)
            If (Not (Me.checkPostalizzazioneWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent checkPostalizzazioneWCompleted(Me, New checkPostalizzazioneWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/RegistrazioneRicaricaW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrazioneRicaricaW(UtenteSubaccount As String, QuantitaSms As Integer, CostoPacchetto As Double, AcquistoUnicoSistema As Integer, token As String) As String
            Dim results() As Object = Me.Invoke("RegistrazioneRicaricaW", New Object() {UtenteSubaccount, QuantitaSms, CostoPacchetto, AcquistoUnicoSistema, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrazioneRicaricaWAsync(UtenteSubaccount As String, QuantitaSms As Integer, CostoPacchetto As Double, AcquistoUnicoSistema As Integer, token As String)
            Me.RegistrazioneRicaricaWAsync(UtenteSubaccount, QuantitaSms, CostoPacchetto, AcquistoUnicoSistema, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrazioneRicaricaWAsync(UtenteSubaccount As String, QuantitaSms As Integer, CostoPacchetto As Double, AcquistoUnicoSistema As Integer, token As String, userState As Object)
            If (Me.RegistrazioneRicaricaWOperationCompleted Is Nothing) Then
                Me.RegistrazioneRicaricaWOperationCompleted = AddressOf Me.OnRegistrazioneRicaricaWOperationCompleted
            End If
            Me.InvokeAsync("RegistrazioneRicaricaW", New Object() {UtenteSubaccount, QuantitaSms, CostoPacchetto, AcquistoUnicoSistema, token}, Me.RegistrazioneRicaricaWOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrazioneRicaricaWOperationCompleted(arg As Object)
            If (Not (Me.RegistrazioneRicaricaWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrazioneRicaricaWCompleted(Me, New RegistrazioneRicaricaWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/RegistraVisuraW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistraVisuraW(IdApp As String, Compagnia As Integer, Agenzia As Integer, Utente As String, Targa As String, TipoVeicolo As Integer, Esito As Integer, token As String) As String
            Dim results() As Object = Me.Invoke("RegistraVisuraW", New Object() {IdApp, Compagnia, Agenzia, Utente, Targa, TipoVeicolo, Esito, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraVisuraWAsync(IdApp As String, Compagnia As Integer, Agenzia As Integer, Utente As String, Targa As String, TipoVeicolo As Integer, Esito As Integer, token As String)
            Me.RegistraVisuraWAsync(IdApp, Compagnia, Agenzia, Utente, Targa, TipoVeicolo, Esito, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraVisuraWAsync(IdApp As String, Compagnia As Integer, Agenzia As Integer, Utente As String, Targa As String, TipoVeicolo As Integer, Esito As Integer, token As String, userState As Object)
            If (Me.RegistraVisuraWOperationCompleted Is Nothing) Then
                Me.RegistraVisuraWOperationCompleted = AddressOf Me.OnRegistraVisuraWOperationCompleted
            End If
            Me.InvokeAsync("RegistraVisuraW", New Object() {IdApp, Compagnia, Agenzia, Utente, Targa, TipoVeicolo, Esito, token}, Me.RegistraVisuraWOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraVisuraWOperationCompleted(arg As Object)
            If (Not (Me.RegistraVisuraWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraVisuraWCompleted(Me, New RegistraVisuraWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/ElencoVisureW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ElencoVisureW(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ElencoVisureW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ElencoVisureWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String)
            Me.ElencoVisureWAsync(Compagnia, CodiceAgenzia, DataDal, DataAl, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ElencoVisureWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String, userState As Object)
            If (Me.ElencoVisureWOperationCompleted Is Nothing) Then
                Me.ElencoVisureWOperationCompleted = AddressOf Me.OnElencoVisureWOperationCompleted
            End If
            Me.InvokeAsync("ElencoVisureW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token}, Me.ElencoVisureWOperationCompleted, userState)
        End Sub
        
        Private Sub OnElencoVisureWOperationCompleted(arg As Object)
            If (Not (Me.ElencoVisureWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ElencoVisureWCompleted(Me, New ElencoVisureWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/ReportTotaliW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportTotaliW(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ReportTotaliW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportTotaliWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String)
            Me.ReportTotaliWAsync(Compagnia, CodiceAgenzia, DataDal, DataAl, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportTotaliWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String, userState As Object)
            If (Me.ReportTotaliWOperationCompleted Is Nothing) Then
                Me.ReportTotaliWOperationCompleted = AddressOf Me.OnReportTotaliWOperationCompleted
            End If
            Me.InvokeAsync("ReportTotaliW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token}, Me.ReportTotaliWOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportTotaliWOperationCompleted(arg As Object)
            If (Not (Me.ReportTotaliWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportTotaliWCompleted(Me, New ReportTotaliWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/ElencoRicaricheW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ElencoRicaricheW(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ElencoRicaricheW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ElencoRicaricheWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String)
            Me.ElencoRicaricheWAsync(Compagnia, CodiceAgenzia, DataDal, DataAl, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ElencoRicaricheWAsync(Compagnia As Integer, CodiceAgenzia As Integer, DataDal As String, DataAl As String, token As String, userState As Object)
            If (Me.ElencoRicaricheWOperationCompleted Is Nothing) Then
                Me.ElencoRicaricheWOperationCompleted = AddressOf Me.OnElencoRicaricheWOperationCompleted
            End If
            Me.InvokeAsync("ElencoRicaricheW", New Object() {Compagnia, CodiceAgenzia, DataDal, DataAl, token}, Me.ElencoRicaricheWOperationCompleted, userState)
        End Sub
        
        Private Sub OnElencoRicaricheWOperationCompleted(arg As Object)
            If (Not (Me.ElencoRicaricheWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ElencoRicaricheWCompleted(Me, New ElencoRicaricheWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/getDatiPostalizzazioneW", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDatiPostalizzazioneW(codici As String, token As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getDatiPostalizzazioneW", New Object() {codici, token})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDatiPostalizzazioneWAsync(codici As String, token As String)
            Me.getDatiPostalizzazioneWAsync(codici, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDatiPostalizzazioneWAsync(codici As String, token As String, userState As Object)
            If (Me.getDatiPostalizzazioneWOperationCompleted Is Nothing) Then
                Me.getDatiPostalizzazioneWOperationCompleted = AddressOf Me.OngetDatiPostalizzazioneWOperationCompleted
            End If
            Me.InvokeAsync("getDatiPostalizzazioneW", New Object() {codici, token}, Me.getDatiPostalizzazioneWOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDatiPostalizzazioneWOperationCompleted(arg As Object)
            If (Not (Me.getDatiPostalizzazioneWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDatiPostalizzazioneWCompleted(Me, New getDatiPostalizzazioneWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/verificaEsistenzaCodiceFiscale", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verificaEsistenzaCodiceFiscale(token As String, codiceFiscale As String) As String
            Dim results() As Object = Me.Invoke("verificaEsistenzaCodiceFiscale", New Object() {token, codiceFiscale})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verificaEsistenzaCodiceFiscaleAsync(token As String, codiceFiscale As String)
            Me.verificaEsistenzaCodiceFiscaleAsync(token, codiceFiscale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verificaEsistenzaCodiceFiscaleAsync(token As String, codiceFiscale As String, userState As Object)
            If (Me.verificaEsistenzaCodiceFiscaleOperationCompleted Is Nothing) Then
                Me.verificaEsistenzaCodiceFiscaleOperationCompleted = AddressOf Me.OnverificaEsistenzaCodiceFiscaleOperationCompleted
            End If
            Me.InvokeAsync("verificaEsistenzaCodiceFiscale", New Object() {token, codiceFiscale}, Me.verificaEsistenzaCodiceFiscaleOperationCompleted, userState)
        End Sub
        
        Private Sub OnverificaEsistenzaCodiceFiscaleOperationCompleted(arg As Object)
            If (Not (Me.verificaEsistenzaCodiceFiscaleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verificaEsistenzaCodiceFiscaleCompleted(Me, New verificaEsistenzaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/verificaEsistenzaEsistenzaEmail", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function verificaEsistenzaEsistenzaEmail(token As String, email As String) As String
            Dim results() As Object = Me.Invoke("verificaEsistenzaEsistenzaEmail", New Object() {token, email})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub verificaEsistenzaEsistenzaEmailAsync(token As String, email As String)
            Me.verificaEsistenzaEsistenzaEmailAsync(token, email, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub verificaEsistenzaEsistenzaEmailAsync(token As String, email As String, userState As Object)
            If (Me.verificaEsistenzaEsistenzaEmailOperationCompleted Is Nothing) Then
                Me.verificaEsistenzaEsistenzaEmailOperationCompleted = AddressOf Me.OnverificaEsistenzaEsistenzaEmailOperationCompleted
            End If
            Me.InvokeAsync("verificaEsistenzaEsistenzaEmail", New Object() {token, email}, Me.verificaEsistenzaEsistenzaEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnverificaEsistenzaEsistenzaEmailOperationCompleted(arg As Object)
            If (Not (Me.verificaEsistenzaEsistenzaEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent verificaEsistenzaEsistenzaEmailCompleted(Me, New verificaEsistenzaEsistenzaEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/getDatiUtenteByCodiceFiscale", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDatiUtenteByCodiceFiscale(token As String, codiceFiscale As String) As String
            Dim results() As Object = Me.Invoke("getDatiUtenteByCodiceFiscale", New Object() {token, codiceFiscale})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDatiUtenteByCodiceFiscaleAsync(token As String, codiceFiscale As String)
            Me.getDatiUtenteByCodiceFiscaleAsync(token, codiceFiscale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDatiUtenteByCodiceFiscaleAsync(token As String, codiceFiscale As String, userState As Object)
            If (Me.getDatiUtenteByCodiceFiscaleOperationCompleted Is Nothing) Then
                Me.getDatiUtenteByCodiceFiscaleOperationCompleted = AddressOf Me.OngetDatiUtenteByCodiceFiscaleOperationCompleted
            End If
            Me.InvokeAsync("getDatiUtenteByCodiceFiscale", New Object() {token, codiceFiscale}, Me.getDatiUtenteByCodiceFiscaleOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDatiUtenteByCodiceFiscaleOperationCompleted(arg As Object)
            If (Not (Me.getDatiUtenteByCodiceFiscaleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDatiUtenteByCodiceFiscaleCompleted(Me, New getDatiUtenteByCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("casa.org/getDenominazioneGestore", RequestNamespace:="casa.org", ResponseNamespace:="casa.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDenominazioneGestore(codiceAgenzia As String, token As String) As String
            Dim results() As Object = Me.Invoke("getDenominazioneGestore", New Object() {codiceAgenzia, token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDenominazioneGestoreAsync(codiceAgenzia As String, token As String)
            Me.getDenominazioneGestoreAsync(codiceAgenzia, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDenominazioneGestoreAsync(codiceAgenzia As String, token As String, userState As Object)
            If (Me.getDenominazioneGestoreOperationCompleted Is Nothing) Then
                Me.getDenominazioneGestoreOperationCompleted = AddressOf Me.OngetDenominazioneGestoreOperationCompleted
            End If
            Me.InvokeAsync("getDenominazioneGestore", New Object() {codiceAgenzia, token}, Me.getDenominazioneGestoreOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDenominazioneGestoreOperationCompleted(arg As Object)
            If (Not (Me.getDenominazioneGestoreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDenominazioneGestoreCompleted(Me, New getDenominazioneGestoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub checkSmsWCompletedEventHandler(sender As Object, e As checkSmsWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class checkSmsWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub checkVisureWCompletedEventHandler(sender As Object, e As checkVisureWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class checkVisureWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub checkMultiploWCompletedEventHandler(sender As Object, e As checkMultiploWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class checkMultiploWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub checkPostalizzazioneWCompletedEventHandler(sender As Object, e As checkPostalizzazioneWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class checkPostalizzazioneWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub RegistrazioneRicaricaWCompletedEventHandler(sender As Object, e As RegistrazioneRicaricaWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrazioneRicaricaWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub RegistraVisuraWCompletedEventHandler(sender As Object, e As RegistraVisuraWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraVisuraWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub ElencoVisureWCompletedEventHandler(sender As Object, e As ElencoVisureWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ElencoVisureWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub ReportTotaliWCompletedEventHandler(sender As Object, e As ReportTotaliWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportTotaliWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub ElencoRicaricheWCompletedEventHandler(sender As Object, e As ElencoRicaricheWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ElencoRicaricheWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub getDatiPostalizzazioneWCompletedEventHandler(sender As Object, e As getDatiPostalizzazioneWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDatiPostalizzazioneWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub verificaEsistenzaCodiceFiscaleCompletedEventHandler(sender As Object, e As verificaEsistenzaCodiceFiscaleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verificaEsistenzaCodiceFiscaleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub verificaEsistenzaEsistenzaEmailCompletedEventHandler(sender As Object, e As verificaEsistenzaEsistenzaEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class verificaEsistenzaEsistenzaEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub getDatiUtenteByCodiceFiscaleCompletedEventHandler(sender As Object, e As getDatiUtenteByCodiceFiscaleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDatiUtenteByCodiceFiscaleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub getDenominazioneGestoreCompletedEventHandler(sender As Object, e As getDenominazioneGestoreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDenominazioneGestoreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(results() As Object, exception As System.Exception, cancelled As Boolean, userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
