'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace UnipolSendMailWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendMailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailHTMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailWithAttachmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailWithMultiAttachmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailWithMultiAttachmentHTMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailHTMLWithEmbeddedAttachmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BackupArchivi.My.MySettings.Default.BackupArchivi_UnipolSendMailWS_Service1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendMailCompleted As SendMailCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailHTMLCompleted As SendMailHTMLCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailWithAttachmentCompleted As SendMailWithAttachmentCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailWithMultiAttachmentCompleted As SendMailWithMultiAttachmentCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailWithMultiAttachmentHTMLCompleted As SendMailWithMultiAttachmentHTMLCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailHTMLWithEmbeddedAttachmentCompleted As SendMailHTMLWithEmbeddedAttachmentCompletedEventHandler
        
        '''<remarks/>
        Public Event SendMailHTMLWithEmbeddedAttachmentMaxCompleted As SendMailHTMLWithEmbeddedAttachmentMaxCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMail(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String) As String
            Dim results() As Object = Me.Invoke("SendMail", New Object() {contractID, from, [to], cc, bcc, subject, text})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String)
            Me.SendMailAsync(contractID, from, [to], cc, bcc, subject, text, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String, ByVal userState As Object)
            If (Me.SendMailOperationCompleted Is Nothing) Then
                Me.SendMailOperationCompleted = AddressOf Me.OnSendMailOperationCompleted
            End If
            Me.InvokeAsync("SendMail", New Object() {contractID, from, [to], cc, bcc, subject, text}, Me.SendMailOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailCompleted(Me, New SendMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailHTML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailHTML(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String) As String
            Dim results() As Object = Me.Invoke("SendMailHTML", New Object() {contractID, from, [to], cc, bcc, subject, text})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String)
            Me.SendMailHTMLAsync(contractID, from, [to], cc, bcc, subject, text, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String, ByVal userState As Object)
            If (Me.SendMailHTMLOperationCompleted Is Nothing) Then
                Me.SendMailHTMLOperationCompleted = AddressOf Me.OnSendMailHTMLOperationCompleted
            End If
            Me.InvokeAsync("SendMailHTML", New Object() {contractID, from, [to], cc, bcc, subject, text}, Me.SendMailHTMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailHTMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailHTMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailHTMLCompleted(Me, New SendMailHTMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailWithAttachment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailWithAttachment(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent() As Byte, ByVal attachmentName As String) As String
            Dim results() As Object = Me.Invoke("SendMailWithAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailWithAttachmentAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String, ByVal attachmentContent() As Byte, ByVal attachmentName As String)
            Me.SendMailWithAttachmentAsync(contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailWithAttachmentAsync(ByVal contractID As String, ByVal from As String, ByVal [to] As String, ByVal cc As String, ByVal bcc As String, ByVal subject As String, ByVal text As String, ByVal attachmentContent() As Byte, ByVal attachmentName As String, ByVal userState As Object)
            If (Me.SendMailWithAttachmentOperationCompleted Is Nothing) Then
                Me.SendMailWithAttachmentOperationCompleted = AddressOf Me.OnSendMailWithAttachmentOperationCompleted
            End If
            Me.InvokeAsync("SendMailWithAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName}, Me.SendMailWithAttachmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailWithAttachmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailWithAttachmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailWithAttachmentCompleted(Me, New SendMailWithAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailWithMultiAttachment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailWithMultiAttachment( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String) As String
            Dim results() As Object = Me.Invoke("SendMailWithMultiAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailWithMultiAttachmentAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String)
            Me.SendMailWithMultiAttachmentAsync(contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailWithMultiAttachmentAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    ByVal userState As Object)
            If (Me.SendMailWithMultiAttachmentOperationCompleted Is Nothing) Then
                Me.SendMailWithMultiAttachmentOperationCompleted = AddressOf Me.OnSendMailWithMultiAttachmentOperationCompleted
            End If
            Me.InvokeAsync("SendMailWithMultiAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4}, Me.SendMailWithMultiAttachmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailWithMultiAttachmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailWithMultiAttachmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailWithMultiAttachmentCompleted(Me, New SendMailWithMultiAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailWithMultiAttachmentHTML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailWithMultiAttachmentHTML( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String) As String
            Dim results() As Object = Me.Invoke("SendMailWithMultiAttachmentHTML", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailWithMultiAttachmentHTMLAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String)
            Me.SendMailWithMultiAttachmentHTMLAsync(contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailWithMultiAttachmentHTMLAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    ByVal userState As Object)
            If (Me.SendMailWithMultiAttachmentHTMLOperationCompleted Is Nothing) Then
                Me.SendMailWithMultiAttachmentHTMLOperationCompleted = AddressOf Me.OnSendMailWithMultiAttachmentHTMLOperationCompleted
            End If
            Me.InvokeAsync("SendMailWithMultiAttachmentHTML", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4}, Me.SendMailWithMultiAttachmentHTMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailWithMultiAttachmentHTMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailWithMultiAttachmentHTMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailWithMultiAttachmentHTMLCompleted(Me, New SendMailWithMultiAttachmentHTMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailHTMLWithEmbeddedAttachment", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailHTMLWithEmbeddedAttachment( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String) As String
            Dim results() As Object = Me.Invoke("SendMailHTMLWithEmbeddedAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLWithEmbeddedAttachmentAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String)
            Me.SendMailHTMLWithEmbeddedAttachmentAsync(contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLWithEmbeddedAttachmentAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    ByVal userState As Object)
            If (Me.SendMailHTMLWithEmbeddedAttachmentOperationCompleted Is Nothing) Then
                Me.SendMailHTMLWithEmbeddedAttachmentOperationCompleted = AddressOf Me.OnSendMailHTMLWithEmbeddedAttachmentOperationCompleted
            End If
            Me.InvokeAsync("SendMailHTMLWithEmbeddedAttachment", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4}, Me.SendMailHTMLWithEmbeddedAttachmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailHTMLWithEmbeddedAttachmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailHTMLWithEmbeddedAttachmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailHTMLWithEmbeddedAttachmentCompleted(Me, New SendMailHTMLWithEmbeddedAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailHTMLWithEmbeddedAttachmentMax", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendMailHTMLWithEmbeddedAttachmentMax( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent5() As Byte,  _
                    ByVal attachmentName5 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent6() As Byte,  _
                    ByVal attachmentName6 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent7() As Byte,  _
                    ByVal attachmentName7 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent8() As Byte,  _
                    ByVal attachmentName8 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent9() As Byte,  _
                    ByVal attachmentName9 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent10() As Byte,  _
                    ByVal attachmentName10 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent11() As Byte,  _
                    ByVal attachmentName11 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent12() As Byte,  _
                    ByVal attachmentName12 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent13() As Byte,  _
                    ByVal attachmentName13 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent14() As Byte,  _
                    ByVal attachmentName14 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent15() As Byte,  _
                    ByVal attachmentName15 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent16() As Byte,  _
                    ByVal attachmentName16 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent17() As Byte,  _
                    ByVal attachmentName17 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent18() As Byte,  _
                    ByVal attachmentName18 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent19() As Byte,  _
                    ByVal attachmentName19 As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal attachmentContent20() As Byte,  _
                    ByVal attachmentName20 As String) As String
            Dim results() As Object = Me.Invoke("SendMailHTMLWithEmbeddedAttachmentMax", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, attachmentContent5, attachmentName5, attachmentContent6, attachmentName6, attachmentContent7, attachmentName7, attachmentContent8, attachmentName8, attachmentContent9, attachmentName9, attachmentContent10, attachmentName10, attachmentContent11, attachmentName11, attachmentContent12, attachmentName12, attachmentContent13, attachmentName13, attachmentContent14, attachmentName14, attachmentContent15, attachmentName15, attachmentContent16, attachmentName16, attachmentContent17, attachmentName17, attachmentContent18, attachmentName18, attachmentContent19, attachmentName19, attachmentContent20, attachmentName20})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLWithEmbeddedAttachmentMaxAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    ByVal attachmentContent5() As Byte,  _
                    ByVal attachmentName5 As String,  _
                    ByVal attachmentContent6() As Byte,  _
                    ByVal attachmentName6 As String,  _
                    ByVal attachmentContent7() As Byte,  _
                    ByVal attachmentName7 As String,  _
                    ByVal attachmentContent8() As Byte,  _
                    ByVal attachmentName8 As String,  _
                    ByVal attachmentContent9() As Byte,  _
                    ByVal attachmentName9 As String,  _
                    ByVal attachmentContent10() As Byte,  _
                    ByVal attachmentName10 As String,  _
                    ByVal attachmentContent11() As Byte,  _
                    ByVal attachmentName11 As String,  _
                    ByVal attachmentContent12() As Byte,  _
                    ByVal attachmentName12 As String,  _
                    ByVal attachmentContent13() As Byte,  _
                    ByVal attachmentName13 As String,  _
                    ByVal attachmentContent14() As Byte,  _
                    ByVal attachmentName14 As String,  _
                    ByVal attachmentContent15() As Byte,  _
                    ByVal attachmentName15 As String,  _
                    ByVal attachmentContent16() As Byte,  _
                    ByVal attachmentName16 As String,  _
                    ByVal attachmentContent17() As Byte,  _
                    ByVal attachmentName17 As String,  _
                    ByVal attachmentContent18() As Byte,  _
                    ByVal attachmentName18 As String,  _
                    ByVal attachmentContent19() As Byte,  _
                    ByVal attachmentName19 As String,  _
                    ByVal attachmentContent20() As Byte,  _
                    ByVal attachmentName20 As String)
            Me.SendMailHTMLWithEmbeddedAttachmentMaxAsync(contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, attachmentContent5, attachmentName5, attachmentContent6, attachmentName6, attachmentContent7, attachmentName7, attachmentContent8, attachmentName8, attachmentContent9, attachmentName9, attachmentContent10, attachmentName10, attachmentContent11, attachmentName11, attachmentContent12, attachmentName12, attachmentContent13, attachmentName13, attachmentContent14, attachmentName14, attachmentContent15, attachmentName15, attachmentContent16, attachmentName16, attachmentContent17, attachmentName17, attachmentContent18, attachmentName18, attachmentContent19, attachmentName19, attachmentContent20, attachmentName20, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendMailHTMLWithEmbeddedAttachmentMaxAsync( _
                    ByVal contractID As String,  _
                    ByVal from As String,  _
                    ByVal [to] As String,  _
                    ByVal cc As String,  _
                    ByVal bcc As String,  _
                    ByVal subject As String,  _
                    ByVal text As String,  _
                    ByVal attachmentContent() As Byte,  _
                    ByVal attachmentName As String,  _
                    ByVal attachmentContent1() As Byte,  _
                    ByVal attachmentName1 As String,  _
                    ByVal attachmentContent2() As Byte,  _
                    ByVal attachmentName2 As String,  _
                    ByVal attachmentContent3() As Byte,  _
                    ByVal attachmentName3 As String,  _
                    ByVal attachmentContent4() As Byte,  _
                    ByVal attachmentName4 As String,  _
                    ByVal attachmentContent5() As Byte,  _
                    ByVal attachmentName5 As String,  _
                    ByVal attachmentContent6() As Byte,  _
                    ByVal attachmentName6 As String,  _
                    ByVal attachmentContent7() As Byte,  _
                    ByVal attachmentName7 As String,  _
                    ByVal attachmentContent8() As Byte,  _
                    ByVal attachmentName8 As String,  _
                    ByVal attachmentContent9() As Byte,  _
                    ByVal attachmentName9 As String,  _
                    ByVal attachmentContent10() As Byte,  _
                    ByVal attachmentName10 As String,  _
                    ByVal attachmentContent11() As Byte,  _
                    ByVal attachmentName11 As String,  _
                    ByVal attachmentContent12() As Byte,  _
                    ByVal attachmentName12 As String,  _
                    ByVal attachmentContent13() As Byte,  _
                    ByVal attachmentName13 As String,  _
                    ByVal attachmentContent14() As Byte,  _
                    ByVal attachmentName14 As String,  _
                    ByVal attachmentContent15() As Byte,  _
                    ByVal attachmentName15 As String,  _
                    ByVal attachmentContent16() As Byte,  _
                    ByVal attachmentName16 As String,  _
                    ByVal attachmentContent17() As Byte,  _
                    ByVal attachmentName17 As String,  _
                    ByVal attachmentContent18() As Byte,  _
                    ByVal attachmentName18 As String,  _
                    ByVal attachmentContent19() As Byte,  _
                    ByVal attachmentName19 As String,  _
                    ByVal attachmentContent20() As Byte,  _
                    ByVal attachmentName20 As String,  _
                    ByVal userState As Object)
            If (Me.SendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted Is Nothing) Then
                Me.SendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted = AddressOf Me.OnSendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted
            End If
            Me.InvokeAsync("SendMailHTMLWithEmbeddedAttachmentMax", New Object() {contractID, from, [to], cc, bcc, subject, text, attachmentContent, attachmentName, attachmentContent1, attachmentName1, attachmentContent2, attachmentName2, attachmentContent3, attachmentName3, attachmentContent4, attachmentName4, attachmentContent5, attachmentName5, attachmentContent6, attachmentName6, attachmentContent7, attachmentName7, attachmentContent8, attachmentName8, attachmentContent9, attachmentName9, attachmentContent10, attachmentName10, attachmentContent11, attachmentName11, attachmentContent12, attachmentName12, attachmentContent13, attachmentName13, attachmentContent14, attachmentName14, attachmentContent15, attachmentName15, attachmentContent16, attachmentName16, attachmentContent17, attachmentName17, attachmentContent18, attachmentName18, attachmentContent19, attachmentName19, attachmentContent20, attachmentName20}, Me.SendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendMailHTMLWithEmbeddedAttachmentMaxOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendMailHTMLWithEmbeddedAttachmentMaxCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendMailHTMLWithEmbeddedAttachmentMaxCompleted(Me, New SendMailHTMLWithEmbeddedAttachmentMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailHTMLCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailHTMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailHTMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailWithAttachmentCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailWithAttachmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailWithAttachmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailWithMultiAttachmentCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailWithMultiAttachmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailWithMultiAttachmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailWithMultiAttachmentHTMLCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailWithMultiAttachmentHTMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailWithMultiAttachmentHTMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailHTMLWithEmbeddedAttachmentCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailHTMLWithEmbeddedAttachmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailHTMLWithEmbeddedAttachmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SendMailHTMLWithEmbeddedAttachmentMaxCompletedEventHandler(ByVal sender As Object, ByVal e As SendMailHTMLWithEmbeddedAttachmentMaxCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendMailHTMLWithEmbeddedAttachmentMaxCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
