'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace Uniarea
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UniquotaSoap", [Namespace]:="http://sso.uniarea.it/ws/")>  _
    Partial Public Class Uniquota
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private VerificaReteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraQuotazioneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ControllaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UniQuota.My.MySettings.Default.UniQuota_Uniarea_Uniquota
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event VerificaReteCompleted As VerificaReteCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraQuotazioneCompleted As RegistraQuotazioneCompletedEventHandler
        
        '''<remarks/>
        Public Event ControllaCompleted As ControllaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sso.uniarea.it/ws/VerificaRete", RequestNamespace:="http://sso.uniarea.it/ws/", ResponseNamespace:="http://sso.uniarea.it/ws/")>  _
        Public Function VerificaRete() As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("VerificaRete", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerificaReteAsync()
            Me.VerificaReteAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerificaReteAsync(ByVal userState As Object)
            If (Me.VerificaReteOperationCompleted Is Nothing) Then
                Me.VerificaReteOperationCompleted = AddressOf Me.OnVerificaReteOperationCompleted
            End If
            Me.InvokeAsync("VerificaRete", New Object(-1) {}, Me.VerificaReteOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerificaReteOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerificaReteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerificaReteCompleted(Me, New VerificaReteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sso.uniarea.it/ws/RegistraQuotazione", RequestNamespace:="http://sso.uniarea.it/ws/", ResponseNamespace:="http://sso.uniarea.it/ws/")>  _
        Public Function RegistraQuotazione(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String, ByVal prodottodda As String, ByVal data As String, ByVal azione As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Esito
            Dim results() As Object = Me.Invoke("RegistraQuotazione", New Object() {codCompagnia, codAgenzia, uid, prodottodda, data, azione})
            Return CType(results(0),Esito)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistraQuotazioneAsync(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String, ByVal prodottodda As String, ByVal data As String, ByVal azione As String)
            Me.RegistraQuotazioneAsync(codCompagnia, codAgenzia, uid, prodottodda, data, azione, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraQuotazioneAsync(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String, ByVal prodottodda As String, ByVal data As String, ByVal azione As String, ByVal userState As Object)
            If (Me.RegistraQuotazioneOperationCompleted Is Nothing) Then
                Me.RegistraQuotazioneOperationCompleted = AddressOf Me.OnRegistraQuotazioneOperationCompleted
            End If
            Me.InvokeAsync("RegistraQuotazione", New Object() {codCompagnia, codAgenzia, uid, prodottodda, data, azione}, Me.RegistraQuotazioneOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraQuotazioneOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistraQuotazioneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraQuotazioneCompleted(Me, New RegistraQuotazioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sso.uniarea.it/ws/Controlla", RequestNamespace:="http://sso.uniarea.it/ws/", ResponseNamespace:="http://sso.uniarea.it/ws/")>  _
        Public Function Controlla(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Esito
            Dim results() As Object = Me.Invoke("Controlla", New Object() {codCompagnia, codAgenzia, uid})
            Return CType(results(0),Esito)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ControllaAsync(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String)
            Me.ControllaAsync(codCompagnia, codAgenzia, uid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ControllaAsync(ByVal codCompagnia As String, ByVal codAgenzia As String, ByVal uid As String, ByVal userState As Object)
            If (Me.ControllaOperationCompleted Is Nothing) Then
                Me.ControllaOperationCompleted = AddressOf Me.OnControllaOperationCompleted
            End If
            Me.InvokeAsync("Controlla", New Object() {codCompagnia, codAgenzia, uid}, Me.ControllaOperationCompleted, userState)
        End Sub
        
        Private Sub OnControllaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ControllaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ControllaCompleted(Me, New ControllaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://sso.uniarea.it/ws/")>  _
    Partial Public Class Esito
        
        Private erroreField As String
        
        Private codiceField As String
        
        Private messaggioField As String
        
        Private agenziaField As clsAgenzia
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Errore() As String
            Get
                Return Me.erroreField
            End Get
            Set
                Me.erroreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Codice() As String
            Get
                Return Me.codiceField
            End Get
            Set
                Me.codiceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Messaggio() As String
            Get
                Return Me.messaggioField
            End Get
            Set
                Me.messaggioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Agenzia() As clsAgenzia
            Get
                Return Me.agenziaField
            End Get
            Set
                Me.agenziaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://sso.uniarea.it/ws/")>  _
    Partial Public Class clsAgenzia
        
        Private codiceCompagniaField As String
        
        Private codiceAgenziaField As String
        
        Private descrizioneField As String
        
        Private ragioneSocialeField As String
        
        Private iscrizioneRuiField As String
        
        Private indirizzoField As String
        
        Private capField As String
        
        Private localitaField As String
        
        Private provinciaField As String
        
        Private telefonoField As String
        
        Private faxField As String
        
        Private emailField As String
        
        Private profiloAttivazioneField As String
        
        Private licenzaDataInizioField As String
        
        Private licenzaDataFineField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property CodiceCompagnia() As String
            Get
                Return Me.codiceCompagniaField
            End Get
            Set
                Me.codiceCompagniaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property CodiceAgenzia() As String
            Get
                Return Me.codiceAgenziaField
            End Get
            Set
                Me.codiceAgenziaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property RagioneSociale() As String
            Get
                Return Me.ragioneSocialeField
            End Get
            Set
                Me.ragioneSocialeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property IscrizioneRui() As String
            Get
                Return Me.iscrizioneRuiField
            End Get
            Set
                Me.iscrizioneRuiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Cap() As String
            Get
                Return Me.capField
            End Get
            Set
                Me.capField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Localita() As String
            Get
                Return Me.localitaField
            End Get
            Set
                Me.localitaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ProfiloAttivazione() As String
            Get
                Return Me.profiloAttivazioneField
            End Get
            Set
                Me.profiloAttivazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property LicenzaDataInizio() As String
            Get
                Return Me.licenzaDataInizioField
            End Get
            Set
                Me.licenzaDataInizioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property LicenzaDataFine() As String
            Get
                Return Me.licenzaDataFineField
            End Get
            Set
                Me.licenzaDataFineField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub VerificaReteCompletedEventHandler(ByVal sender As Object, ByVal e As VerificaReteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerificaReteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegistraQuotazioneCompletedEventHandler(ByVal sender As Object, ByVal e As RegistraQuotazioneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistraQuotazioneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Esito
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Esito)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ControllaCompletedEventHandler(ByVal sender As Object, ByVal e As ControllaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ControllaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Esito
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Esito)
            End Get
        End Property
    End Class
End Namespace
